### ISSUE TITLE
[found in debug.log] UsersStats pb

### ISSUE THREAD

**Issue by neowutran** [neowutran/ShinraMeter#101]
##### CRASH (version=0.88): #####
지정한 키가 사전에 없습니다.
   위치: System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   위치: DamageMeter.Abnormality.ApplyBuff(Int64 lastTicks)
   위치: DamageMeter.Abnormality.ApplyBuffDebuff(Int64 tick)
   위치: DamageMeter.AbnormalityTracker.DeleteAbnormality(EntityId entity, Int64 ticks)
   위치: DamageMeter.AbnormalityTracker.DeleteAbnormality(SDespawnUser message)
   위치: DamageMeter.NetworkController.PacketAnalysisLoop()
   위치: System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   위치: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   위치: System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.Collections.Generic.KeyNotFoundException: 지정한 키가 사전에 없습니다.
   위치: System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   위치: DamageMeter.Abnormality.ApplyBuff(Int64 lastTicks)
   위치: DamageMeter.Abnormality.ApplyBuffDebuff(Int64 tick)
   위치: DamageMeter.AbnormalityTracker.DeleteAbnormality(EntityId entity, Int64 ticks)
   위치: DamageMeter.AbnormalityTracker.DeleteAbnormality(SDespawnUser message)
   위치: DamageMeter.NetworkController.PacketAnalysisLoop()
   위치: System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   위치: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   위치: System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal

TValue get_Item(TKey)

I haven't looked into it yet, but that can be related to #89 , something somewhere probably modify UsersStats

**Comment by Gl0** [comment]
May be problem appears after reconnect, since we reset entity/player tracker, but don't touch abnormality/damage trackers.

**Comment by Gl0** [comment]
Seems gone after abnormalities refactoring.
