### ISSUE TITLE
[found in debug.txt] data export

### ISSUE THREAD

**Issue by neowutran** [neowutran/ShinraMeter#102]
##### CRASH (version=0.88): #####
동일한 키를 사용하는 항목이 이미 추가되었습니다.
   위치: System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   위치: System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   위치: System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   위치: DamageMeter.DataExporter.Send(Entity boss, String json, Int32 numberTry)
   위치: DamageMeter.DataExporter.Send(Entity boss, String json, Int32 numberTry)
   위치: DamageMeter.DataExporter.Send(Entity boss, String json, Int32 numberTry)
   위치: DamageMeter.DataExporter.Send(Entity boss, String json, Int32 numberTry)
   위치: DamageMeter.DataExporter.<>c__DisplayClass1_0.<ToTeraDpsApi>b__0()
   위치: System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   위치: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   위치: System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.ArgumentException: 동일한 키를 사용하는 항목이 이미 추가되었습니다.
   위치: System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   위치: System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   위치: System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   위치: DamageMeter.DataExporter.Send(Entity boss, String json, Int32 numberTry)
   위치: DamageMeter.DataExporter.Send(Entity boss, String json, Int32 numberTry)
   위치: DamageMeter.DataExporter.Send(Entity boss, String json, Int32 numberTry)
   위치: DamageMeter.DataExporter.Send(Entity boss, String json, Int32 numberTry)
   위치: DamageMeter.DataExporter.<>c__DisplayClass1_0.<ToTeraDpsApi>b__0()
   위치: System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   위치: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   위치: System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal

Void ThrowArgumentException(System.ExceptionResource)

~
=>
https://github.com/neowutran/ShinraMeter/blob/master/DamageMeter.Core/DataExporter.cs#L167
https://github.com/neowutran/ShinraMeter/blob/master/DamageMeter.Core/DataExporter.cs#L189

**Comment by Gl0** [comment]
Forgot that there can be multiple failed posts. Need either change boss to be the key, of the dictionary, either add it's id to the end of the string.

**Comment by neowutran** [comment]
Yup, that or some kind of flash message to display only the last error

**Comment by Gl0** [comment]
Last error is good only for timeout or api error. Normal failed messages need to be shown for all bosses.
