### ISSUE TITLE
Could you make a log can include timestamp for each skills?

### ISSUE THREAD

**Issue by lark983** [neowutran/ShinraMeter#107]
Hello,
Thanks for making ShinraMeter. I enjoy this application a lot. This makes me enjoy Tera much more.
By the way, I got a request and will be very happy if you can make it.

You have made a function that creates excel file for each boss battle, and I think you can make time stamps for each skills.
If you can, we will be able to analyze which skill takes how much time, so we can calculate DPS for each skills. Then, we can judge which skill has higher DPS.

For example, 
 0:00:00 Skill A hits the boss for 1000dmg.
 0:01:00 Skill B hits the boss for 2000dmg.
 0:01:30 Skill C hits the boss for 1500dmg.
 0:02:30 Skill A hits the boss for 1000dmg.

Skill B does 2000dmg and it took 0.5sec. Skill B did 4000 DPS.
Skill C does 1500dmg and it took 1sec. Skill C did 1500DPS.

Please let me know if there is anything I can help you.

Regards,

**Comment by Gl0** [comment]
How do you suggest to distinguish what caused the delay between skills, post-animation of first skill, pre-animation/cast time of second skill, user input delay (caused by proper positioning between skills / skill cooldown / following boss mechanics / etc)?

**Comment by lark983** [comment]
I think it will be very useful if the average time can be displayed that each skill took.

**Comment by Gl0** [comment]
We can't measure it because of things in my previous comment.

**Comment by neowutran** [comment]
Hi ^^
yup, can't do that for the reason Gl0 say.
The only thing we can do that can be somehow related to that, is exporting skills grouped with approximative timestamp (1 second interval, like it's done in the meter core). 
  
But that can be only used to see dps evolution over time, second by second, to detect dps burst. 

Skill dps can be manually calculated (just divide the total damage done for one skill, by the fight duration )

**Comment by Gl0** [comment]
We can change this interval to any other we like, or even create separate skill log structure (which can be useful to find optimal rotations of skills and consumables). But this log has nothing common with the idea of "momentary" skill dps calculation. And even if we could calc it - such dps depends much on rotations glyphs and buffs, so it can not be used to choose what skills to use or not.

**Comment by lark983** [comment]
I got it. Thanks anyway!
And thanks again for this amazing project. I really enjoy this meter a lot.
