### ISSUE TITLE
How do they do it?? (bitmap from stream invalid argument, debug.txt)

### ISSUE THREAD

**Issue by Gl0** [neowutran/ShinraMeter#109]
```
System.ArgumentException: Недопустимый параметр.
   в System.Drawing.Bitmap..ctor(Stream stream)
   в Tera.Game.IconsDatabase.GetBitmap(String iconName)
   в DamageMeter.ExcelExport.CreateUserSheet(ExcelWorkbook wb, Members user)
   в DamageMeter.ExcelExport.ExcelSave(EncounterBase data)
   в DamageMeter.DataExporter.<>c__DisplayClass1_0.<ToTeraDpsApi>b__0()
   в System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal
```

**Comment by neowutran** [comment]
In that case, that would means the program find the file, but the file is not an image? 
yeah, sometime in the log, that just magic.

**Comment by Gl0** [comment]
May be corrupted archive. But why we haven't seen such error earlier, same icons are loaded into detailed skill stats.

**Comment by neowutran** [comment]
On autoupdate, I verify the checksum of the archive

**Comment by Gl0** [comment]
All this errors are in russian, may be from one user. That may download it from site without autoupdate.

**Comment by neowutran** [comment]
yup, can't really do anything against that. Let just ignore it

**Comment by Gl0** [comment]
There are another similar error, but it complains on the whole archive structure. But that one is compiled by user, so there can be really something wrong with contents.
Add timestamp to debug.php, plz =)

**Comment by neowutran** [comment]
added the timestamp

**Comment by Gl0** [comment]
And it would be nice to add some anonymous way to know, whether similar errors are coming from one meter or not (hash from source ip or something like that).

**Comment by neowutran** [comment]
good

**Comment by Gl0** [comment]
Don't see anymore, seems that was threading issue with saving multiple excel files at one time.
