### ISSUE TITLE
Tw Server  Updated ninja version

### ISSUE THREAD

**Issue by q848899** [neowutran/ShinraMeter#114]
Tw Server  Updated ninja version  the pugin not work please update thanks

**Comment by Gl0** [comment]
Update will be much faster, if someone publish link to fresh opcode & unpacked datacenter files here after each update, like KR server users do.

**Comment by q848899** [comment]
What datacenter files   I can offer

**Comment by Gl0** [comment]
> How to get opcode:
> 
> GoneUp method: https://github.com/GoneUp/Tera_PacketViewer/tree/master/Opcode%20DLL
> How to read the database: 
> 
> https://github.com/gothos-folly/TeraDataTools

**Comment by q848899** [comment]
I can't  Make a c++  0 0  SOR

**Comment by neowutran** [comment]
sb send me opcode + the new database. 
Pushed the opcode, database is on the cloud

**Comment by Gl0** [comment]
Don't see it on cloud.
Btw, I wonder whether new KR crypto arrived to TW or not.

**Comment by neowutran** [comment]
The upload crashed x) re uploading. 
We will see, I m making the 0.93 tonigh, if tomorrow people still can't use it on TW, I guess I will need to test it

**Comment by sb032835** [comment]
meter work well on TW ^^
