### ISSUE TITLE
[debug.txt] Abnormality clone

### ISSUE THREAD

**Issue by neowutran** [neowutran/ShinraMeter#116]
1461714366 04041e3c2cbc82410c42e79118f0d1574efb3d3d95718b0ac213039a925a86b63be301a36ac91ef084ad83ac66b3023d740485b2a3639902100d1c0c344bbdf7 ##### CRASH (version=0.94): #####
동일한 키를 사용하는 항목이 이미 추가되었습니다.
   위치: System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   위치: System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   위치: System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   위치: System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   위치: Tera.Game.AbnormalityStorage.Clone(NpcEntity boss) 파일 E:\ShinraMeter\TeraCommon\Game\Services\AbnormalityTracker.cs:줄 57
   위치: DamageMeter.NetworkController.UpdateUi() 파일 E:\ShinraMeter\DamageMeter.Core\NetworkController.cs:줄 117
   위치: DamageMeter.NetworkController.CheckUpdateUi() 파일 E:\ShinraMeter\DamageMeter.Core\NetworkController.cs:줄 444
   위치: DamageMeter.NetworkController.PacketAnalysisLoop() 파일 E:\ShinraMeter\DamageMeter.Core\NetworkController.cs:줄 203
   위치: System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   위치: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   위치: System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.ArgumentException: 동일한 키를 사용하는 항목이 이미 추가되었습니다.
   위치: System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   위치: System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   위치: System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   위치: System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   위치: Tera.Game.AbnormalityStorage.Clone(NpcEntity boss) 파일 E:\ShinraMeter\TeraCommon\Game\Services\AbnormalityTracker.cs:줄 57
   위치: DamageMeter.NetworkController.UpdateUi() 파일 E:\ShinraMeter\DamageMeter.Core\NetworkController.cs:줄 117
   위치: DamageMeter.NetworkController.CheckUpdateUi() 파일 E:\ShinraMeter\DamageMeter.Core\NetworkController.cs:줄 444
   위치: DamageMeter.NetworkController.PacketAnalysisLoop() 파일 E:\ShinraMeter\DamageMeter.Core\NetworkController.cs:줄 203
   위치: System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   위치: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   위치: System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal

**Comment by Gl0** [comment]
Try to push latest version, may be it helps. There are more accurate player and userentity updates and  equivalents, that may resolve this issue. The only way to achieve this error that I see - update of the object that is key of the dictionary in the way changing it hashcode, so that it not found and added twice. But at the moment of clone hashcodes are the same and it throws tis error.

**Comment by Gl0** [comment]
Need urgent update, critical bug in 0.95

**Comment by Gl0** [comment]
Seems all dictionary cloning issues finally fixed.
