### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by sb032835** [neowutran/ShinraMeter#117]
2016-04-28 22:19:19,174 [10] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### CRASH (version=0.95): #####
並未將物件參考設定為物件的執行個體。
   於 Tera.Game.Death.get_Dead() 於 E:\ShinraMeter\TeraCommon\Game\Abnormality\Death.cs: 行 66
   於 Tera.Game.AbnormalityStorage.<>c.<EndAll>b__17_2(KeyValuePair`2 x) 於 E:\ShinraMeter\TeraCommon\Game\Abnormality\AbnormalityStorage.cs: 行 149
   於 System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   於 Tera.Game.AbnormalityStorage.EndAll(Int64 ticks) 於 E:\ShinraMeter\TeraCommon\Game\Abnormality\AbnormalityStorage.cs: 行 149
   於 DamageMeter.NetworkController.PacketAnalysisLoop() 於 E:\ShinraMeter\DamageMeter.Core\NetworkController.cs: 行 400
   於 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Threading.ThreadHelper.ThreadStart()
Tera.Core
System.NullReferenceException: 並未將物件參考設定為物件的執行個體。
   於 Tera.Game.Death.get_Dead() 於 E:\ShinraMeter\TeraCommon\Game\Abnormality\Death.cs: 行 66
   於 Tera.Game.AbnormalityStorage.<>c.<EndAll>b__17_2(KeyValuePair`2 x) 於 E:\ShinraMeter\TeraCommon\Game\Abnormality\AbnormalityStorage.cs: 行 149
   於 System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   於 Tera.Game.AbnormalityStorage.EndAll(Int64 ticks) 於 E:\ShinraMeter\TeraCommon\Game\Abnormality\AbnormalityStorage.cs: 行 149
   於 DamageMeter.NetworkController.PacketAnalysisLoop() 於 E:\ShinraMeter\DamageMeter.Core\NetworkController.cs: 行 400
   於 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal

**Comment by neowutran** [comment]
should be fixed with 0.96

**Comment by neowutran** [comment]
btw, for teradps.io, TW name need to be censored or not?

**Comment by sb032835** [comment]
TW don't need to censored 
TTera have not block meter
thank you
