### ISSUE TITLE
Using meter with proxy

### ISSUE THREAD

**Issue by GeneralLuke** [neowutran/ShinraMeter#120]
I've been trying to figure out how to use this thing with WTFast. I've switched to raw socket mode and made the exception on Windows Firewall, but when I try to put in an IP like it says on the guide, the program won't open. It opens and seems to run fine when I take out the line with the IP. I'm also not sure which IP I'm supposed to put in because there are 4 different ones with WTFast. Is there any detailed guides for this? I'm not knowledgeable in this at all.

**Comment by Gl0** [comment]
There is small mistake in the guide, servers.txt format had been changed since last update of this guide. There must be 2 spaces between region and server name fields.

**Comment by GeneralLuke** [comment]
Ah, I see. That fixed the issue. Thank you.
