### ISSUE TITLE
Pressing on "setting" problem

### ISSUE THREAD

**Issue by Frozenteer** [neowutran/ShinraMeter#121]
when i press on the setting button (the wheel) it appears a bit far from the wheel itself and the two options close themselves after 0.2
 second so i cant even manage to click it that fast it literally stays there for 0.2sec than disappearing by itself
![pic](https://cloud.githubusercontent.com/assets/19182707/15007229/d42b5130-11df-11e6-8f69-8469f974c01e.png)

**Comment by Gl0** [comment]
That's simple context menu with transparent background. If it disappearing - probably it is problem with mouse button that doubleclicks. You may try to use right mouse button for it.

**Comment by Gl0** [comment]
There is a problem when using left click on this button if main window is docked to right border of screen. Will be fixed in next release.Use right mouse button or move window away from screen border as a workaround with current version.
