### ISSUE TITLE
After last update, i can't see the Timers

### ISSUE THREAD

**Issue by Reny900** [neowutran/ShinraMeter#122]
As my title says:
Server is Killian (EU)
Just finished an Abscess Hard run and this is what i see:
![death timers](https://cloud.githubusercontent.com/assets/19189602/15017091/743a9562-1214-11e6-98cc-010e88fc3622.JPG)
Meanwhile, on the excel report of the other run yesterday it's fine:
![death 2](https://cloud.githubusercontent.com/assets/19189602/15017163/bccfb7bc-1214-11e6-8d81-3d94da49eecd.JPG)
Any help on this?
Even other dungeons , the death timers/aggro timers on the UI are on 00:00 but are fine on the excel report

**Comment by Gl0** [comment]
Already fixed https://github.com/neowutran/ShinraMeter/commit/296cd2bc442dd5a6b3bb0f4825693f316ef56227

**Comment by Reny900** [comment]
I see you've fixed it. I even downloaded the new version, but in every single dungeon i can't keep up the aggro timers/death timers/death count.
The fresh new version 0.98 on your download list has this problem

**Comment by neowutran** [comment]
Yup, know bug in the 0.98, will be fixed with 0.99
