### ISSUE TITLE
Compile new version

### ISSUE THREAD

**Issue by robin344** [neowutran/ShinraMeter#126]
Can u compile new version of DPS meter please, i'm not able to update from v.0.96. Thanks!

**Comment by Gl0** [comment]
You can always download fresh version from https://cloud.neowutran.ovh/index.php/s/e7arRRxkHEIkzU1

**Comment by robin344** [comment]
nice, maybe change link here http://forum.teratoday.com/topic/1316-shinrameter-open-source-tera-dps-meter/

**Comment by neowutran** [comment]
yup x) thanks, just updated teratoday link
