### ISSUE TITLE
Excel export not working

### ISSUE THREAD

**Issue by Casanova** [neowutran/ShinraMeter#129]
Hello there,

The Excel exports don't work anymore. I have noticed that there is a new field in the configuration file, I think it's to set the folder where the extracted data should be sent, but I still haven't figured it out.

Kind regards,

Casanova

**Comment by neowutran** [comment]
The new default directory is "My Documents/ShinraMeter", check here

**Comment by neowutran** [comment]
And yes, the new field in the config file is to set the directory where excel file are send

**Comment by Casanova** [comment]
OK, I'll check then.
I have tried [C:\Test] in the new field, but it didn't work. Maybe it needs some double quotes or something.

Thanks a lot for the quick replay :)

Cheer,

**Comment by pozso1234** [comment]
This function not work yet . It dont export file to the destination location.
