### ISSUE TITLE
One Line Paste

### ISSUE THREAD

**Issue by monster528** [neowutran/ShinraMeter#130]
is it possible to make the damage taken/dps turn into a single line when copy/pasting to chat instead of spamming 5+ messages per party member

**Comment by neowutran** [comment]
yes, configure what and how you want to paste: 
https://github.com/neowutran/ShinraMeter/wiki#configuring-hotkeys

**Comment by monster528** [comment]
thanks for the reply! unfortunately I have no idea what im doing. Im assuming you have to change the part under the <string> i tried a few different things but it just broke it. Could you tell me exactly what I would have to do to turn it into a single sentence?

**Comment by neowutran** [comment]
the symbole "\" means "new line". So just remove this symbole when you see it between <header>....</header> and between <content>...</content>

**Comment by neowutran** [comment]
Like that for example:
 ```
 <header>Damage Done @ {encounter} {timer} {partyDps} {enrage}:</header>
 <content>[{class}] {name}: {damage_percentage} | {crit_rate} Crit | {global_dps}</content>
```

**Comment by monster528** [comment]
thank you for taking the time and i appreciate what you do for all of us
