### ISSUE TITLE
[request]how can i make shinra work with pingzapper

### ISSUE THREAD

**Issue by fakezilla** [neowutran/ShinraMeter#132]
I have to use pingzapper(the best tunnel for me) but can't make it work with shinra, im using TCPview to try to find the IP to replace in the servers.txt but the only one with activity is "xx.xx.xx.xxx.rdns.asXXXXX.net" not expert in this area but assume is the reverse adress for the "xx.xx.xx.xxx",  and also I have no idea what number to set in the "XXXX" after the "NA", can you help me ?

**Comment by Gl0** [comment]
Try 127.0.0.1, Our user report that it works with wtfast this way despite of seeing many remote ip in resource manager.

**Comment by fakezilla** [comment]
Tried that now and don't work :(, tried the network ip too and same result, tried with battle ping too that is almost as good as pingzapper and same results...there is anything else that can be done ?

**Comment by Gl0** [comment]
Rechecked.
Pingzapper is ssh-tunnel proxy, and meter work fine with it via 127.0.0.1 (and only via 127.0.0.1, there are no other connections from Tera.exe while proxy is active).

**Comment by fakezilla** [comment]
Then idk what to do, maybe some problem in my pc ? don't have any vpn installed or server, i can ping 127.0.0.1 but if i type in browser says can't connect, not sure if that is what supose to happen, i'll continue to try and search for a solution, if you have any ideas i appreciate and thanks for the support so far.

**Comment by Gl0** [comment]
you don't need to open 127.0.0.1 in browser.
Recheck that you are doing all right
https://github.com/neowutran/ShinraMeter/issues/123#issuecomment-217729903
Bypass all about finding ip - it's 127.0.0.1 in your case.

**Comment by fakezilla** [comment]
Thank you so much! Did step by step and worked!! Thank you very much!!!

**Comment by atecdeveloper** [comment]
I am trying the same think, im using pingzapper, put 127.0.0.20 NA  VPN in the end of server.txt, changed flag to false, opened firewall exception, shinra doesnt even connect, it always says no server,

**Comment by Gl0** [comment]
Remove this string from servers.txt, pingzapper use default hardcoded ip. 
Check that config\windows.xml contains `<winpcap>false</winpcap>`, if there is `<winpcap>true</winpcap>` - change `true` to `false`, save and close.
Run add_firewall_exception.bat with admin privileges or [add firewall rule manually](https://github.com/neowutran/ShinraMeter/wiki/Window-firewall).
Start meter. Restart tera.

**Comment by atecdeveloper** [comment]
So i dont need to change anything on server.txt?

**Comment by Gl0** [comment]
You can delete it so it would be reset to default.

**Comment by atecdeveloper** [comment]
I did as you said, it open SM UI and everything but the meter remains at 0. Maybe cause im using Tera-proxy + pingzapper?

**Comment by Gl0** [comment]
most likely you messed up firewall rule
