### ISSUE TITLE
paste speed

### ISSUE THREAD

**Issue by alexiel31** [neowutran/ShinraMeter#133]
Hi, is that possible to add a timer between each post when paste ?
Because of current speed is too high, it sometimes paste only 1 or 2 lines instead of all.
actualy, i need to paste it 4 to 7 times in order for it to show off correctly.
thank you in advance for your help

**Comment by Gl0** [comment]
Are you sure that problem with paste speed, and not with some ingame focus changes while pasting?
Pasting stops if any window (such as roll) appears in game.

**Comment by alexiel31** [comment]
nope, i pasted after roll, and no other window opened

**Comment by Gl0** [comment]
There are already bunch of pauses in line feed implementation.
We may increase them a bit. But not sure which one is failing in your case. It can be VK_RETURN keydown state time, pause between keyup and next keydown, or timeout before or after it for the game to complete previous string pasting or entered string sending. All these things can be increased separately. But we shouldn't increase them all too much...

**Comment by neowutran** [comment]
It s the return key that cause problem. This key + flash UI => no  good. 
Maybe a parameter can be added in the config file to increase a little the pause before / after the return

**Comment by alexiel31** [comment]
If this can be done, it would be the best :tada:  (for my case at least)
I don't know if this can be done, or how. So if you can manage to do this, it would be awesome & I'll be very grateful :)
in the hope that you come back with good news, thank you for your time & help :)
you've done a great job so far :v:

**Comment by Gl0** [comment]
Hope thats enough, and your problem is not with other delays.

**Comment by neowutran** [comment]
@alexiel31 you succeded to paste correctly with the new parameters?
