### ISSUE TITLE
Doesn't show in game

### ISSUE THREAD

**Issue by Cellie5400** [neowutran/ShinraMeter#134]
Hello,
i'm sorry for my english. I installed DPS meter. Everything is ok. It shows my DPS, but when i turn on Tera it doesn't show in the game. I must 'turn off' Tera and then I can see it.

For example. 

I turn on DPS meter (that i can see on my desktop). Then I turn on Tera. But in Tera I can't see that meter. I must throw Tera down. 

I hope you understand me.

Thank you,
Cell

https://cloud.githubusercontent.com/assets/19779823/15825805/758dfed0-2c05-11e6-84cc-262a2a8532e0.png - When I turn on DPS meter (screened on desktop)

https://cloud.githubusercontent.com/assets/19779823/15825845/994b6f74-2c05-11e6-9cef-d4fe3df68928.png - When I turn on Tera (DPS meter is nowhere)

https://cloud.githubusercontent.com/assets/19779823/15825877/bb22c8f4-2c05-11e6-8652-819ed853a249.png - After i kill something (So DPS meter is ok, but i can't see it in game)

**Comment by Gl0** [comment]
Don't use fullscreen game mode.

**Comment by Cellie5400** [comment]
Thank you
