### ISSUE TITLE
new fonction 

### ISSUE THREAD

**Issue by lofuy** [neowutran/ShinraMeter#140]
Can you implement with a new button whitch show skill's order of the player. And if it is possible draw one chain of skill :).

**Comment by neowutran** [comment]
In the current state that is not possible. It will be possible once I finish to refactor the backend of the meter, but I m slow. So maybe next month

**Comment by neowutran** [comment]
Added basic skill logs with 1.16 ^^ & what do you means by chain of skill? ^^
