### ISSUE TITLE
No more counting Heal and or mana

### ISSUE THREAD

**Issue by Reny900** [neowutran/ShinraMeter#148]
I can't see the heals of the priest/mystic e/o the mana i recover from them or the potions (glistening included)
Is something wrong with my version of the Shinra ? (v1.14)
![yakiii mana](https://cloud.githubusercontent.com/assets/19189602/16635996/ac67ef1e-43d5-11e6-8451-01e754cdfd67.JPG)
![heal yakiii](https://cloud.githubusercontent.com/assets/19189602/16635997/ac6b15f4-43d5-11e6-9886-2e30590f78d1.JPG)
![damage yakiii](https://cloud.githubusercontent.com/assets/19189602/16635998/ac70dde0-43d5-11e6-97b7-d5976a59c5e0.JPG)

**Comment by neowutran** [comment]
It s a know bug with 1.14, should be mostly fixed with 1.15 (will be released today)

**Comment by Reny900** [comment]
With the new update, it now counts evrything!
Last exception for Gilliglade (where the dps show full empty, even the DPS skill [EU:Killian]) but it's gilliglade after all who cares!

**Comment by neowutran** [comment]
ok ^-^ hum, the dps shouldn't be empty for ghilliglade, seems like I still have some bugs to find
