### ISSUE TITLE
ShinraMeter 1.15 crashing after start.

### ISSUE THREAD

**Issue by Jeka1980** [neowutran/ShinraMeter#152]
After Update from 1.14 to 1.15 ShinraMeter crashing after start. Error log:

2016-07-10 00:08:03,484 [1] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### CRASH (version=1.15): #####
Couldn’t register the hot key.
   в DamageMeter.KeyboardHook.RegisterHotKey(ModifierKeys modifier, Keys key) в G:\ShinraMeter\DamageMeter.Core\KeyboardHook.cs:строка 132
   в DamageMeter.KeyboardHook.Register() в G:\ShinraMeter\DamageMeter.Core\KeyboardHook.cs:строка 102
   в DamageMeter.KeyboardHook.RegisterKeyboardHook() в G:\ShinraMeter\DamageMeter.Core\KeyboardHook.cs:строка 89
   в DamageMeter.UI.MainWindow.UpdateKeyboard(Object o, EventArgs args) в G:\ShinraMeter\DamageMeter.UI\MainWindow.xaml.cs:строка 408
   в System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.DispatcherOperation.InvokeImpl()
   в System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   в MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Windows.Threading.DispatcherOperation.Invoke()
   в System.Windows.Threading.Dispatcher.ProcessQueue()
   в System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   в System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   в System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   в System.Windows.Application.RunDispatcher(Object ignore)
   в System.Windows.Application.RunInternal(Window window)
   в System.Windows.Application.Run(Window window)
   в System.Windows.Application.Run()
   в DamageMeter.UI.App.Main() в G:\ShinraMeter\DamageMeter.UI\obj\Debug\App.g.cs:строка 0
DamageMeter
System.InvalidOperationException: Couldn’t register the hot key.
   в DamageMeter.KeyboardHook.RegisterHotKey(ModifierKeys modifier, Keys key) в G:\ShinraMeter\DamageMeter.Core\KeyboardHook.cs:строка 132
   в DamageMeter.KeyboardHook.Register() в G:\ShinraMeter\DamageMeter.Core\KeyboardHook.cs:строка 102
   в DamageMeter.KeyboardHook.RegisterKeyboardHook() в G:\ShinraMeter\DamageMeter.Core\KeyboardHook.cs:строка 89
   в DamageMeter.UI.MainWindow.UpdateKeyboard(Object o, EventArgs args) в G:\ShinraMeter\DamageMeter.UI\MainWindow.xaml.cs:строка 408
   в System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.DispatcherOperation.InvokeImpl()
   в System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   в MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Windows.Threading.DispatcherOperation.Invoke()
   в System.Windows.Threading.Dispatcher.ProcessQueue()
   в System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   в System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   в System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   в System.Windows.Application.RunDispatcher(Object ignore)
   в System.Windows.Application.RunInternal(Window window)
   в System.Windows.Application.Run(Window window)
   в System.Windows.Application.Run()
   в DamageMeter.UI.App.Main() в G:\ShinraMeter\DamageMeter.UI\obj\Debug\App.g.cs:строка 0
System.Collections.ListDictionaryInternal

Void RegisterHotKey(ModifierKeys, System.Windows.Forms.Keys)

**Comment by Gl0** [comment]
There was added hotkey for saving excel files on demand. Seems I've chosen one of your hotkeys for it as default. Just change it in hotkeys.xml (or disable via key "None")

**Comment by Delvertico** [comment]
I've the same error and don't know how to solve this. 
Can someone explain me what i can do?

**Comment by Jeka1980** [comment]
I've fix this problem - in hotkeys.xml just disable all via "None" and enable only "paste" and "reset" - all works perfect

**Comment by Delvertico** [comment]
So I've to rewrite in Editor?  But where I have to disable or enable that things?

Sorry, but I dont know ^^'

<hotkeys>
  <paste>
    <ctrl>False</ctrl>
    <shift>False</shift>
    <window>False</window>
    <key>Home</key>
  </paste>
  <reset>
    <ctrl>False</ctrl>
    <shift>False</shift>
    <window>False</window>
    <alt>False</alt>
    <key>Delete</key>
  </reset>
  <reset_current>
    <ctrl>True</ctrl>
    <shift>False</shift>
    <window>False</window>
    <alt>False</alt>
    <key>Delete</key>
  </reset_current>
  <excel_save>
    <ctrl>True</ctrl>
    <shift>False</shift>
    <window>False</window>
    <alt>False</alt>
    <key>Next</key>
  </excel_save>
  <click_throu>
    <ctrl>True</ctrl>
    <shift>False</shift>
    <window>False</window>
    <alt>False</alt>
    <key>PageUp</key>
  </click_throu>
  <copys>
    <copy>
      <ctrl>True</ctrl>
      <shift>False</shift>
      <window>False</window>
      <key>End</key>
      <string>
        <header>Damage Taken @ {encounter} {timer}:\</header>
        <content>[{class}] {name}: Hits: {hits_received} = {damage_received}; Death {deaths} = {death_duration} Aggro {aggro} = {aggro_duration}\</content>
        <footer></footer>
        <order_by>hits_received</order_by>
        <order>descending</order>
      </string>
    </copy>
    <copy>
      <ctrl>False</ctrl>
      <shift>True</shift>
      <window>False</window>
      <key>End</key>
      <string>
        <header>Damage Done @ {encounter} {timer} {partyDps} {enrage}:\</header>
        <content>[{class}] {name}: {damage_percentage} | {crit_rate} Crit | {global_dps}\</content>
        <footer></footer>
        <order_by>damage_percentage</order_by>
        <order>descending</order>
      </string>
    </copy>
  </copys>
</hotkeys>

**Comment by neowutran** [comment]
You already have one program using one of these hotkeys. So you need to change or remove the hotkey.
 
 If the problematic hotkey is PageUp, then change `<key>PageUp</key>` by something else or remove it using `<key>None</key>`. 

The list of values available for `<key>...</key>` is here: https://msdn.microsoft.com/en-us/library/system.windows.forms.keys%28v=vs.110%29.aspx

**Comment by Delvertico** [comment]
Perfect, now it works! Thank you so much :D

**Comment by neowutran** [comment]
=)
