### ISSUE TITLE
Teradps.io weird issue (Chrome)

### ISSUE THREAD

**Issue by Reny900** [neowutran/ShinraMeter#153]
The website looks like this and can't interace with the menu
![terados google](https://cloud.githubusercontent.com/assets/19189602/16713088/82bfe850-469c-11e6-938e-6e6d5251881c.JPG)

**Comment by Gl0** [comment]
teradps.io questions should be sent to [discord](https://discord.gg/0wjLnPs6HoNFxv6O), we have no access to the site. But that particular issue is probably caused by adblocker.

**Comment by Reny900** [comment]
How ? i deactivated it and now it's back to normal, but i see no ads, how that happened?

**Comment by Gl0** [comment]
Site is using framework that support google adsence. Not sure how it's used now (haven't ever seen site code), but it's capable to show google ads, and your adblocker block it.
