### ISSUE TITLE
TWTERA opcode

### ISSUE THREAD

**Issue by sb032835** [neowutran/ShinraMeter#154]
https://onedrive.live.com/?id=19D3D9732B5ECAB6%21203&cid=19D3D9732B5ECAB6

**Comment by Gl0** [comment]
Thanks.
All regions except KR now have the same version of the game.

**Comment by sb032835** [comment]
but I change new opcode
meter can't work

TW server got merged

**Comment by Gl0** [comment]
update Tera.Core

**Comment by sb032835** [comment]
1.17 work well
