### ISSUE TITLE
ShinraMeter.exe disappears??

### ISSUE THREAD

**Issue by Delvertico** [neowutran/ShinraMeter#155]
I downloadet the new update from the website because the autoupdater tells me that. 
Now if I want to open the ShinaMeter, the ShinraMeter.exe disappears / delete itself?

**Comment by neowutran** [comment]
the file "ShinraMeter.exe" is deleted from your computer? check if you antivirus didn't deleted it

**Comment by Delvertico** [comment]
oh ... that was it. Thank you!

**Comment by Gl0** [comment]
What reason was stated by antivirus?
