### ISSUE TITLE
tw server can't updata teradps.io

### ISSUE THREAD

**Issue by hap0328** [neowutran/ShinraMeter#157]
I use 1.17v shinra, but Since 7/14 teradps.io have not show new data.
I can't see any new data on teradps.io from tw server.
progrom show "sorry, it seems your server isn't supported."
TW Server Merge, new name is 提雅拉尼亞.
ip is 220.228.174.67.

**Comment by neowutran** [comment]
ok, will make a new release soon. 
You can try to replace the server file with this one: https://github.com/neowutran/TeraDpsMeterData/blob/master/servers.txt

If you can also check if the server id is still the same after the merge ^^ (you need to use wireshark, read the xml server file & extract the server id)

**Comment by sb032835** [comment]
hi
I have  sent an email to you,there are xml file
please check
server ID <2800> IP< 220.228.174.67> Name<提雅拉尼亞>

**Comment by neowutran** [comment]
should be fixed with 1.18
