### ISSUE TITLE
KTera Opcodes + DC Unpacked +S1UI.zip

### ISSUE THREAD

**Issue by badgon** [neowutran/ShinraMeter#158]
[KTera Opcodes + DC Unpacked ](https://drive.google.com/folderview?id=0Bzkk4M4rVzwScjNGVV9RTTZLZ2s&usp=sharing)

**Comment by Gl0** [comment]
New potions arrived, that have both stats and regen effect - need to change hotdot database format to support multiple types of effects at one time.

**Comment by neowutran** [comment]
& thanks =)
