### ISSUE TITLE
Missing Window.exe file

### ISSUE THREAD

**Issue by chrisljames90** [neowutran/ShinraMeter#159]
I have downloaded this a few time and the window.exe file is missing, when i try to open the launcher i get an error saying "Windows cannot find ShinraMeter.exe. make sure you typed the name correctly, and then try again, after this error shows the shinra meter application goes away and takes me downloading a brand new file to get it back.

**Comment by Gl0** [comment]
Check your antivirus (avast?), probably it doesn't like our meter

**Comment by neowutran** [comment]
too old & no response, closing
