### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Honeypietart** [neowutran/ShinraMeter#16]
Hi, any time I try to interact with the DPS meter it crashes. For example, when I try to look at skills or move the meter around, it just crashes and exits. Any ideas?

**Comment by neowutran** [comment]
Hi, as I m not able to reproduce this crash, I will add a logger tomorrow. 
So when the dps meter will crash, details will be written in a file.

**Comment by neowutran** [comment]
Hi, just added a logger.
If the dps meter crash, you will have a file "error.log" full of data. 
Copy paste this file here and I should be able to fix the bug
