### ISSUE TITLE
Meter not showing in game

### ISSUE THREAD

**Issue by Vladekxz** [neowutran/ShinraMeter#161]
I haven't been able to make the meter work properly, I can see it on my desktop, and shows the dps but I can't manage to make it show in game

Note:I have tried using windowed mode, windowed fullscreen and still doesn't work

**Comment by Gl0** [comment]
Check "Stay topmost" setting in context menu.

**Comment by hollaterin** [comment]
happens to me too..doesnt work :(

**Comment by hollaterin** [comment]
ive excluded it from my antivirus and checked stay topmost

**Comment by neowutran** [comment]
check that you are playing in windowed or windows(fullscreen) mode.
Fullscreen mode doesn't work with the meter

**Comment by hollaterin** [comment]
i have, still doesnt work. Does using WTFAST have anythinf to do with it?

**Comment by Gl0** [comment]
No, just use game in windowed mode + stay topmost setting active.

**Comment by Vladekxz** [comment]
Sorry for not replying before, my ISP had some problems, anyways even doing anything you guys said, I haven't managed to fix the issue :/ got the stay topmost setting active, windowed mode, checked antivirus and also the always show setting is active

**Comment by Gl0** [comment]
recheck that game is not in fullscreen.
