### ISSUE TITLE
Crash @ TERA-Launch "Couldn’t register the hot key."

### ISSUE THREAD

**Issue by Reinforce418** [neowutran/ShinraMeter#162]
On my computer ShinraMeter crashes when I launch TERA.
The message is: 
2016-07-23 12:54:30,190 [1] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### CRASH (version=1.18): #####
Couldn’t register the hot key.

Same happend when I use v 1.15 and 1.17. 

Between 2016-07-08 and 2016-07-16 ShinraMeter worked fine mostly on version 1.15.
Nothing on my computer has changed since then.

[error_log.zip](https://github.com/neowutran/ShinraMeter/files/379521/error_log.zip)

**Comment by neowutran** [comment]
This error mean that you already have another software running that use the same hotkeys as the ShinraMeter. Modify the shinra hotkeys or close the other software

**Comment by Reinforce418** [comment]
All right, I'll do this.

Thank you for your response.
