### ISSUE TITLE
Meter crashing after some time in TERA

### ISSUE THREAD

**Issue by Gornan258** [neowutran/ShinraMeter#163]
After about 15 - 60 mins in game Shinra Meter is crashing for me, here you have error log

[error.zip](https://github.com/neowutran/ShinraMeter/files/380580/error.zip)

**Comment by Gl0** [comment]
This is probably bad network card / drivers issue. meter receive packet that is not valid at tcp level.

**Comment by Gornan258** [comment]
Updated my network card drivers and still same.

**Comment by Gl0** [comment]
You may play with offloading options (try them on or off) in card properties, may be that help or try another card.

**Comment by Gornan258** [comment]
tried both ways on offloading and it didn't help at all.

**Comment by neowutran** [comment]
ok, will fix this issue by discaring incorrect packet instead of making the meter crash. 
(adding try/catch around the check & discaring the packet if an exception is raised)
