### ISSUE TITLE
Skills Window default location cannot be altered

### ISSUE THREAD

**Issue by kevorkien** [neowutran/ShinraMeter#164]
Is it possible to make it so the windows remember where they were last left?
**Issue**: Player Skill Breakdown Window default opening location cannot be altered.

I have TERA open on my primary monitor, ShinraMeter open on my 2ndary.
While I could change the starting location of main window (via the windows.config file)
I couldn't find a way to do the same for the Player Skills window.

Consequently, every time I click on a player, the skills window inevitably pops up behind my TERA window, so then I have to minimise it to see the skill window... drag it over to the other monitor....
re-engage the fullscreen display, and then do it all again next time.

Or perhaps I've accidentally overlooked something?
Regards,

Aeon

**Comment by neowutran** [comment]
The location of the Player Skill Breakdown Window is not saved atm
so, for a next release

**Comment by Gl0** [comment]
Not sure that saving it is good idea, since there can be several breakdown windows open at one time. Which one to save? Last opened? Last closed? + other windows are also opened in strange places.
We can open it in the center of current meter screen or align it to meter window (left/right/down, need to check screen boundaries so that it wouldn't get out of it). But the most difficult thing is to determine, where to place second/third/etc details window.

**Comment by kevorkien** [comment]
Well there's a tonne of conditional, best fit, solutions you could try and create the the BEST place. In my experience though (thanks Samsung Galaxy) trying to over-engineer a solution to out-think people before they **maybe, but might not** even think it, is at best going to help some specific people save a small amount of time but more likely to frustrate, confuse and seem counter intuitive to everyone else. AND in the process consume a lot of time and effort to create.

> But the most difficult thing is to determine, where to place second/third/etc details window.

Currently they're all stacked....  how bout a simple, diagonal-cascade from the centre of whichever monitor the DPS meter is in. The mouse will be nearby to move them as they popup.

**Comment by Gl0** [comment]
That's the way I've done it in Casual. But there is one difference - Shinra windows are semi-transparent and such cascade will be looking not so good as expected...

**Comment by kevorkien** [comment]
Agreed, and I did consider the transparency, but this is already happening now, only without the added benefit of monitor choice. The solution won't be the final one no doubt, but an effective interim improvement over the current state until you decide how you want to handle them properly  --  if something like this doesn't take you too long to code up, that is.

**Comment by neowutran** [comment]
The lazy thing I can do is to make the skill windows appear at the exact same spot as the main window. 
- Should be on the same screen as main window so the main problem is solved
- But, you will have to move the windows if you want to see multiple skill window. 

I can't find a more lazy & easy way to solve the pb x)

**Comment by neowutran** [comment]
@kevorkien working better with the new version?
