### ISSUE TITLE
Meter crashing after updating to V1.20

### ISSUE THREAD

**Issue by dimourios** [neowutran/ShinraMeter#167]
Basically, it does the connection to the server but it crashes a few seconds later.
I've attached the error.log file content below.

[errorlog.txt](https://github.com/neowutran/ShinraMeter/files/396380/errorlog.txt)

**Comment by neowutran** [comment]
region?

**Comment by Gl0** [comment]
Bad... seems they can update datacenter and opcodes without touching client version... Or may be opcode version is not always in the first position of versions array.

**Comment by neowutran** [comment]
huehuehue just EU update it seems, will get new datacenter & opcode x)

**Comment by dimourios** [comment]
Yep its Killian ..

**Comment by probatya** [comment]
RU region crashes too, server Arun

**Comment by Gl0** [comment]
Только что зашел на арун - никаких проблем.
