### ISSUE TITLE
Issue with Borderless Windowed using Win 10 Anniversary

### ISSUE THREAD

**Issue by TChan626** [neowutran/ShinraMeter#169]
When the meter is on top of the game running in Borderless Windowed, the [Windows taskbar will be on top of the game](http://puu.sh/qqVda/e835da20a3.png). When the meter is dragged onto another monitor, it works like normal (taskbar is hidden when the game is in focus). Happened after I changed to Windows 10 Anniversary update and happens with both Show always on and off. Transparency is off in the config but I don't think that has to do with the problem.

**Comment by Gl0** [comment]
Seems it's windows bug, and appears with any "always on top" application. There are a lot of whine in internet about it.

**Comment by Gl0** [comment]
You may try to use https://github.com/Codeusa/Borderless-Gaming instead of windowed fullscreen. Not tested it myself, but seen mentions that it helps with some games & this bug.

**Comment by Gl0** [comment]
Fixed via hiding meter from taskbar.
