### ISSUE TITLE
Mystc/Priest wtih 0% crits in the DPSmeter window

### ISSUE THREAD

**Issue by Reny900** [neowutran/ShinraMeter#170]
As the title says it's been 1 or 2 days that this is happening.

**Comment by Gl0** [comment]
Just checked - it shows correct both dps critrate and heal critrate. May be you switched mode to dps and don't use damage skills or contrary - switched to heal, but doing only damage?

**Comment by neowutran** [comment]
Look the skills details to check if everything is normal, & with screenshot will be better too (main windows + skill details of the problematic healer, (heal tab & dps tab))

**Comment by neowutran** [comment]
https://github.com/neowutran/ShinraMeter/issues/184
