### ISSUE TITLE
Still cant get the meter to work with wtfast

### ISSUE THREAD

**Issue by hollaterin** [neowutran/ShinraMeter#171]
I have winpcap

I just cant seem to figure out which vpn my wtfast is using. I always put it to automatic detection. please help.

**Comment by hollaterin** [comment]
wwhen i look through resource monitor, theres like 10 wttfast and alot of tera launchers.

**Comment by Gl0** [comment]
Just switch to raw sockets and add firewall exception. Latest version of meter work with wtfast without any other configuration.

**Comment by hollaterin** [comment]
was working last 2 days. now its not =/

**Comment by hollaterin** [comment]
im launching the meter through admin
and then wtfast. am i doing something wrong?

**Comment by Gl0** [comment]
May be you moved meter, so that firewall rule doesn't applied anymore?

**Comment by hollaterin** [comment]
nope same folder, ive allowed my firewall to allow it

**Comment by Gl0** [comment]
Recheck that you have `<winpcap>false</wipcap>` in window.xml and that firewall rule contains full path to meter exe.

**Comment by hollaterin** [comment]
yeah..that part im not very sure

**Comment by hollaterin** [comment]
got it,

the meter doesnt launch sometimes. been reinstalling just to open it.

**Comment by neowutran** [comment]
do you have information on why the meter doesn't launch sometimes? 
Your antivirus try to block it or something?
