### ISSUE TITLE
Can't use NumPad keys

### ISSUE THREAD

**Issue by Recupel** [neowutran/ShinraMeter#172]
Using the 1.21 version, having this http://puu.sh/qrUuv/995d0b94cb.png in my config file.
(Following the enumeration of https://msdn.microsoft.com/en-us/library/system.windows.forms.keys%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396)

Getting this http://puu.sh/qrUxI/1bf3a2cc63.png on launch resulting in a fatal error.

Numpad7 instead of NumPad7?

**Comment by Gl0** [comment]
May be you have Numpad7 specified for some other action?
Or you are changing not a working copy of file.

**Comment by neowutran** [comment]
https://github.com/neowutran/ShinraMeter/blob/master/Data/HotkeysData.cs#L212

**Comment by Gl0** [comment]
Yeah, my fault... Checked it on not copy section.

**Comment by Gl0** [comment]
fixed
