### ISSUE TITLE
JP LangPack

### ISSUE THREAD

**Issue by radasuka** [neowutran/ShinraMeter#173]
[LangPack](https://drive.google.com/open?id=0B-bSenHtWgUsczVjLU51NlFxR0k)

**Comment by Gl0** [comment]
Thanks, we will need more strings soon.=)

**Comment by Gl0** [comment]
Added a bunch of new strings - translate them, please, check https://raw.githubusercontent.com/neowutran/ShinraMeter/master/Lang/LP.resx , all new strings are below "Your_computer_is_too_slow".

**Comment by NakagawaDPS** [comment]
Added Japanese Data.
[LangPack_JP](https://drive.google.com/open?id=0B-F5DGVbXr6bSnp3V1BCVU54NEk)

*Some of the text has not been translated . ( Use location unknown)

Thank you always update!

**Comment by radasuka** [comment]
new LangPack
[LangPack](https://drive.google.com/open?id=0B-bSenHtWgUsYlo0WjJCZzJ1OFk)

@NakagawaDPS 
Thank you fix

**Comment by Gl0** [comment]
Thanks.=)

**Comment by Gl0** [comment]
Another strings added.=)

**Comment by radasuka** [comment]
added.
[LangPack](https://drive.google.com/open?id=0B-bSenHtWgUsam1SVFNuTnRfcEk)

**Comment by Gl0** [comment]
Thanks, probably tomorrow we'll release new version to public with it.

**Comment by radasuka** [comment]
fix ja strings.
[LangPack](https://drive.google.com/open?id=0B-bSenHtWgUsNGdfbTJsU0k0R2M)
