### ISSUE TITLE
TW LangPack

### ISSUE THREAD

**Issue by sb032835** [neowutran/ShinraMeter#175]
[TW LangPack](https://drive.google.com/open?id=0B1-zuiIGIqVuRW85Rlh4bDhZMlU)

**Comment by Gl0** [comment]
We should mark it as zh-TW or the whole zh?

**Comment by sb032835** [comment]
zh-tw

**Comment by sb032835** [comment]
revised XD 
TW LangPack[https://drive.google.com/open?id=0B1-zuiIGIqVuRW85Rlh4bDhZMlU](url)

**Comment by Gl0** [comment]
You'd better send resx (or even pull request with changes=). resx is compiled to dll automatically.

**Comment by sb032835** [comment]
[ShinraMeter/Lang/LP.zh-TW.resx](https://github.com/neowutran/ShinraMeter/blob/master/Lang/LP.zh-TW.resx) is correct
but use VS open file(ShinraMeter-master) have miss two stings
like this[http://imgur.com/a/MqlZa]

**Comment by Gl0** [comment]
There were extra spaces that made data elements not valid. fixed.
