### ISSUE TITLE
Meter doesn't show how many times a healer uses heal/mana charge

### ISSUE THREAD

**Issue by Ahron112** [neowutran/ShinraMeter#177]
Meter only shows their dps, buff, skilldealt, and skill received, but doesn't show anything for mana or heal.
I've tried reinstalling, but it doesn't help. :/

**Comment by Ahron112** [comment]
rip, no one knows?

**Comment by Gl0** [comment]
Just checked it right now, showed correctly both direct heal and HOT. Note that you can see HOT only if it applied to you, or if you applied it on someone. Game doesn't send packets with this info to not affected players.

**Comment by Ahron112** [comment]
But it doesn't show me anything even if it applies to me. Is there something I need to change through settings?

**Comment by Ahron112** [comment]
![2016-08-15_1231](https://cloud.githubusercontent.com/assets/20966972/17676620/4c26c0de-62e4-11e6-85a8-d41840706347.png)
![2016-08-15_1231](https://cloud.githubusercontent.com/assets/20966972/17676638/5b67ded4-62e4-11e6-911a-4409dfa335d4.png)

These always show up blanks

**Comment by neowutran** [comment]
screen of SkillDealt / SkillReceived for the same encounter? 
(Screen of everything if you can: main windows + skillDealt + SkillReceived + Heal + Dps , to have full data)

**Comment by Ahron112** [comment]
Oh! I figured out what was wrong, I changed the "paste dps => CTRL Insert" before and it didn't work, so I didn't touch the hotkeys this time and it finally showed the stats. Ty for the help ^^

**Comment by Gl0** [comment]
strange, hotkeys should not affect gui...

**Comment by Ahron112** [comment]
That's what I thought, but that was the only thing I changed, so I decided not to mess with it this time. Also, the icon for mana charge doesn't show on the meter, thought I'd let you know. :D

**Comment by Gl0** [comment]
Manacharge is applied as dot, but my parser extract only glyph and item icons for now.
Probably I'll add direct skill abnormals soon.
