### ISSUE TITLE
Win10 - No error, it stops counting dps

### ISSUE THREAD

**Issue by Reny900** [neowutran/ShinraMeter#178]
A friend of mine is having problem to get Shinrameter to work. It detects the server as it changes icon when he logs in various character in differents guild, but it stops there.
Is any way i can help you/him?
The error.log file is empty

**Comment by Gl0** [comment]
It stops or icon keep changing on further relogs? If icon keeps changing - than it isn't stopped. May be some option like "count only bosses" enabled?

**Comment by Gl0** [comment]
Recheck, whether it happens after 1.28.
Added "unfreeze" workaround, that stops waiting for missing data after 300 buffered packets, and trying to parse all queue.
