### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by Vaernil100** [neowutran/ShinraMeter#179]
Whenever I download the file, as soon as i click on the shinrameter.exe file it changes into a shinrameter.config file and i cannot do anything with it. Does anyone know why this is happening and how i can fix it?

**Comment by Gl0** [comment]
Check your antivirus.

**Comment by Vaernil100** [comment]
So i managed to install it now, but when i start it, it immediately shuts down after like 3 secs.

**Comment by Gl0** [comment]
By default meter is minimized to tray until you run tera.
