### ISSUE TITLE
shinra meter no show dps

### ISSUE THREAD

**Issue by theolyte** [neowutran/ShinraMeter#18]
Hi,

How i can fix it ?

It work, screen appears but no dps on it... May be i must change some files or add some files what is the way for he work pls ?

**Comment by neowutran** [comment]
Are you using a VPN / Proxy (like WFast or other?) 
You play on NA? EU? RU? 
What server?

**Comment by theolyte** [comment]
hi,

i play on eu.

I dnt use VPN.

I play on killian.

2016-01-23 14:43 GMT+01:00 neowutran <notifications@github.com>:

**Comment by neowutran** [comment]
Then verify you have .NET 4.6 framework installed and Winpcap

**Comment by theolyte** [comment]
I did it. its installed.

2016-01-23 14:58 GMT+01:00 neowutran <notifications@github.com>:

**Comment by neowutran** [comment]
Then, for now, I have no idea on what is happening on your PC. Try to use another dps meter.

The last idea I have is to try the dps meter with a wifi connexion & to try it with a ethernet cable, to check if there is any difference.
