### ISSUE TITLE
2 Monitors

### ISSUE THREAD

**Issue by Xiuhh** [neowutran/ShinraMeter#183]
I -usually- have 2 monitors set up, but today I had to disconnect my 2nd one (where the meter sits) while my pc was off. Started it up, and the meter loads .. but it's virtually placed on the 2nd monitor which is no longer connected. It's not a huge deal since I can still paste it into a private channel to see it, just a little inconvenient.

**Comment by Gl0** [comment]
Just open window.xml and change coords to zero. Or just delete this file (will loose not default settings if any).

**Comment by Xiuhh** [comment]
Awesome, thanks :)
