### ISSUE TITLE
Meter doesn't show HOT and Mana

### ISSUE THREAD

**Issue by Ahron112** [neowutran/ShinraMeter#184]
For some reason my meter doesn't show the data for HOT/mana again. Is this happening to someone else too?

**Comment by Dominik1912** [comment]
I have the same problem. I tried to download the meter again, use Raw Socket instead of Winpcap but nothing works. Everything else shows correctly.

**Comment by neowutran** [comment]
What class are you playing?
what HOT/DOT/mana did you expected to see & from who?
Any way to reproduce the issue?

**Comment by hap0328** [comment]
every class can't show this data.
Probably after v1.20 this bug come into existence.
![hot and mp bug](https://cloud.githubusercontent.com/assets/17157257/18037899/f0a97d4a-6dc0-11e6-8330-8716cb575540.jpg)

**Comment by Ahron112** [comment]
I play a priest, and I'd click my name to see the stats, but it's always empty. If I go on a dps, and click on the healers stats, it doesn't show anything either.

**Comment by neowutran** [comment]
try with a fresh 1.25 without your config file. 
atm I unable to reproduce this bug so until I success to reproduce this error, I won't be able to fix it. 
This bug always happens? You NEVER see anything in the heal/mana section? 
on what server/region are you playing? any additional information that could help me to reproduce this bug?

**Comment by Ahron112** [comment]
The first time this happened, I changed the hot keys to shift + end (to paste dps) and that didn't show HOT/mana for me until I reinstalled and left the keys alone. After the update I couldn't see the stats anymore (even tried reinstalling)

I am from NA, Celestial Hills.

**Comment by Ahron112** [comment]
and I will try the 1.25 right now, I am currently on 1.24

**Comment by Dominik1912** [comment]
Just now I tested the new version 1.25. For me it didn't change anything. Still no Heal, Mana showing.

> You NEVER see anything in the heal/mana section? 

No, I **never** see anything. Regardless which class i'm trying.

> on what server/region are you playing?

I'm playing Priest on EU Kaidun.

> any additional information that could help me to reproduce this bug?

I'm just playing normal. I can't help with this one because for me it didn't show anything to begin with.

**Comment by neowutran** [comment]
I got some data from someone with the same issue (EU - Killian, was running a DSU with him)

Heal crit% show 0% 
In skills details: Dps tab contains data. Heal tab is empty, Mana tab is empty, Buff contains data, SkillDealt contains data, SkillReceived contains data
He ALWAYS have this issue 
( 8 gb of ram, windows 7 64 bits ultimate, .net4.6 installed, avast antivirus but doesn't seem to block the meter) 



Any of you with this issue can try to run the meter from the source code directly with visual studio, debug mode? just to be sure

**Comment by neowutran** [comment]
try to use this version: 
https://cloud.neowutran.ovh/index.php/s/7vYT08eYnHHhQW4

Tell me if something change

**Comment by Dominik1912** [comment]
That´s what I want to see!
Your debug version works just fine for me.

![dmgmeterheal](https://cloud.githubusercontent.com/assets/21266258/18109564/625e6e26-6f12-11e6-8f93-167020010455.PNG)
![dmgmetermana](https://cloud.githubusercontent.com/assets/21266258/18109565/62604de0-6f12-11e6-8d9d-22aa851093e5.PNG)

**Comment by Gl0** [comment]
my woodoo magic worked =)

**Comment by neowutran** [comment]
thanks you grand master =D your magic is very effective =p

**Comment by neowutran** [comment]
can you check that this version is working too? 
https://cloud.neowutran.ovh/index.php/s/AqND6snpaTVNBxr

**Comment by Dominik1912** [comment]
Works fine. The Heal crit % also shows correctly.

**Comment by neowutran** [comment]
ok releasing the fix as 1.26

**Comment by Ahron112** [comment]
Unfortunately, updating to 1.26 didn't work for me ><
![2016-08-31_0201](https://cloud.githubusercontent.com/assets/20966972/18122634/30a81320-6f1f-11e6-961c-adae7d837fef.png)
![2016-08-31_0202](https://cloud.githubusercontent.com/assets/20966972/18122631/30a6646c-6f1f-11e6-9035-0fe96eb99ee4.png)
![2016-08-31_0202_001](https://cloud.githubusercontent.com/assets/20966972/18122633/30a6b610-6f1f-11e6-9b45-3d6c96978f4d.png)
![2016-08-31_0202_002](https://cloud.githubusercontent.com/assets/20966972/18122632/30a690d6-6f1f-11e6-9e50-783cd792a571.png)

**Comment by Ahron112** [comment]
Should I open this issue again? Or is this okay even though it's closed?

**Comment by Ahron112** [comment]
![2016-08-31_0205](https://cloud.githubusercontent.com/assets/20966972/18122681/67d66e82-6f1f-11e6-8c34-b24847ddf48e.png)

**Comment by neowutran** [comment]
@Dominik1912 
1.26 is working well for you?

@hap0328 
working or not for you?

**Comment by Ahron112** [comment]
I'm going to try restarting my computer and redownload shinra 1.26 again.

**Comment by Ahron112** [comment]
Ok, after doing reinstalling shinra completely and restarting my computer, the meter works perfectly (including mana/HOT).  Whenever I use Shinra, I ALWAYS right click the icon and go through the config section and check "count bosses only, detect bosses by HP bar, count party members only, stay topmost, and invisible when no stats." Then I decided to test it out once more and it didn't show any stats for mana/HOT.

"Count bosses only and detect bosses by HP bar" = doesnt show mana/HOT
"Count party members, stay topmost, and invisible when no stats = show ONLY mana

right now I have it at "stay topmost and invisible when no stats and it shows everything. 

Not sure if this only happens to me or not, but hopefully this will be helpful!

**Comment by Gl0** [comment]
thats much clearer - will fix soon.

**Comment by Gl0** [comment]
When "Count party members" set, it shows only heals that applied to party, that's expected behavior. Bug was only in "Count only bosses". And it was from the beginning of this feature, much earlier than 1.20, my fault... =(

**Comment by Ahron112** [comment]
Everything works now! Tyvm ^_^
