### ISSUE TITLE
[REQ] Select language

### ISSUE THREAD

**Issue by wjdgns421** [neowutran/ShinraMeter#187]
i tried change <language>en-US<language> / <ui-language> but it didn't change.
can you add select language system?

**Comment by Gl0** [comment]
Just checked `<ui_language>en-US</ui_language>` - working as expected.

**Comment by wjdgns421** [comment]
try ui language is fine but dps meter's main ui wasn't changed

**Comment by Gl0** [comment]
Skill/monster/abnormality names depends on game region. You can override it using `<language>NA</language>` or `<language>EU-EN</language>` (they are different). But that may cause missing abnormals and skill/monster names if your game region have something that not exists on NA/EU.

**Comment by wjdgns421** [comment]
oh..... 
I just want to see dps on eng. korean's dps mark is too inconvenience. 
but eng is simple. like. 1.00M/S .800kb/s , Can i set only dps language?

**Comment by Gl0** [comment]
that should be ok with just ui_language

**Comment by wjdgns421** [comment]
![ui1](https://cloud.githubusercontent.com/assets/20179497/18248359/9787e0ba-73b2-11e6-929d-d2cf7477f5f5.png)
i mean that square.
i set language / ui_language / na/na. 
when i closed ShinraMeter.exe, `<language>Auto</language>` back ui still na
and dps word still korean.   v1.27

**Comment by Gl0** [comment]
should be ok with `<ui_language>en-US</ui_language>` in 1.28

**Comment by wjdgns421** [comment]
thx, i'll be waiting
