### ISSUE TITLE
The new servers were added.

### ISSUE THREAD

**Issue by dawma** [neowutran/ShinraMeter#188]
(ShinraMeterFolder)\resources\data\servers.txt

"183.110.3.5 KR 7 엘리온의 투지"

After auto-update, I manually add that string for new server.

It's not such hard work for some user.

And I think developers can add that string to update file easily.

But most end user think Meter dosen't work in new server appropriately.

I'm not skilled to github system and English.

I think developers or others can improve users' accessiblity.

Thank you.

**Comment by Gl0** [comment]
We can't know that something changed in regions other than we play, until someone send us feedback. 
You are welcome.=)
