### ISSUE TITLE
disable slidebar?

### ISSUE THREAD

**Issue by Delvertico** [neowutran/ShinraMeter#190]
Is it possible to disable the slidebar for a better overview?
I've the ShinraMeter on a 2nd screen and it's awkwardly to switch during gaming

**Comment by neowutran** [comment]
slidebar? the one for the numbers of player? you can configure the number of player in the config file "window.xml":
` <number_of_players_displayed>5</number_of_players_displayed>`
to maybe something like 
` <number_of_players_displayed>15</number_of_players_displayed>`

**Comment by Delvertico** [comment]
Yes, now it's better. Thank you :)
