### ISSUE TITLE
crashes when I right click to see player skills 

### ISSUE THREAD

**Issue by NovaSilent** [neowutran/ShinraMeter#192]
@neowutran Hello it takes dps down just fine but when i go to right click on someones name to see there skill dps % it will immediately crash and i don't understand the issue v.v any help or advice would be helpful.

**Comment by neowutran** [comment]
I think I know from where it come. but : 

Do you have additionnal informations? 
What boss did you fight? The player you clicked on, did he hit the boss? did he get hit by the boss?

**Comment by NovaSilent** [comment]
I tested it on open world bams without being in parties. Specifically the ruins at high watch outskirts and when I would go to click my name it would crash immediately upon bringing up the window

**Comment by neowutran** [comment]
ok ^^ I know from where the bug come
Will be fixed in 1.32

**Comment by NovaSilent** [comment]
Alright to and good work so far ^^

**Comment by NovaSilent** [comment]
Ty*
