### ISSUE TITLE
Custom sounds

### ISSUE THREAD

**Issue by Tsuchikure** [neowutran/ShinraMeter#193]
Using custom sounds for the new alert when getting a whisper or negotiation works great. The only problem is that when the meter updates, it appears to remove the sound file without any notice and causes the meter to instantly crash upon receiving a whisper or negotiation in-game.

 This is mainly a problem because it's unexpected. Any way to keep the files intact when updating the meter? If possible i'd like to just have it in there at all times instead of keeping a copy on my desktop somewhere.

**Comment by Gl0** [comment]
probably we need to add config dir for custom sound lookup

**Comment by Gl0** [comment]
as a workaround you can place it there and write something like `..\config\mysound.mp3`

**Comment by neowutran** [comment]
should be good, double click on text box to select the sound file you want directly
+, the ./sound/ folder won't be deleted on update
