### ISSUE TITLE
Crashing after every notification

### ISSUE THREAD

**Issue by TChan626** [neowutran/ShinraMeter#194]
I've been crashing after most, if not every, notification. Notifications are showing up visually, but there's no audio cue. After that, I see that there's an error message saying that the meter broke and then it stops responding. I'm using Windows 10 Home with the Anniversary Update. 

Here's the error.txt: http://pastebin.com/9biZ97Mi

I'm assuming the issue might be because I'm using VoiceMeeter to separate audio tracks (set up so I can mute Teamspeak/Discord on stream), but I could be wrong.

**Comment by neowutran** [comment]
ok ^^ & maybe, will try to install VoiceMeeter to check if it come from that + how to fix that if it come from VoiceMeeter

**Comment by neowutran** [comment]
Can you try with 1.39 or 1.40 if you still have the pb?

**Comment by TChan626** [comment]
1.39 or later of which program?

**Comment by Gl0** [comment]
meter, of cause )

**Comment by TChan626** [comment]
I tried 1.41 and didn't get any notification when someone used an @ in guild chat or when someone negotiated me. The meter itself works though.

**Comment by neowutran** [comment]
you receive notification only when you are NOT on the tera windows ^^ that was the case?

**Comment by TChan626** [comment]
Yes I was alt tabbed with the focus on another program (Chrome) when I got the mention/negotiation. There was no sound or visual notification.

**Comment by neowutran** [comment]
ok ^^ some things to checks ^^ can you send me your window.xml config file? So I can check if it s not a weird configuration

**Comment by TChan626** [comment]
http://pastebin.com/b22D2BHu

**Comment by neowutran** [comment]
ok thanks ^^ found the bug for visual notification, will be fixed in 1.42
can you send me the content of you "error.log" file?

**Comment by TChan626** [comment]
Ok, 1.42 seems to have fixed both notifications not showing up and the meter crashing. I'm not hearing any sound notification though.

**Comment by neowutran** [comment]
anything in the "error.log" file?

**Comment by TChan626** [comment]
2016-09-16 16:21:27,550 [21] ERROR ShinraMeter [(null)] - ##### (version=1.42):
##### Debug: SCreatureChangeHP need rootowner update3: 0 -> Npc 118 6000
2016-09-16 16:21:28,309 [20] ERROR ShinraMeter [(null)] - ##### (version=1.42):
##### Debug: SCreatureChangeHP need rootowner update3: 0 -> Npc 118 6000
2016-09-16 16:21:28,309 [21] ERROR ShinraMeter [(null)] - ##### (version=1.42):
##### Debug: SCreatureChangeHP need rootowner update3: 0 -> Npc 118 9000
2016-09-16 16:21:28,340 [19] ERROR ShinraMeter [(null)] - ##### (version=1.42):
##### Debug: SCreatureChangeHP need rootowner update3: 0 -> Npc 118 9000
2016-09-16 16:21:28,340 [17] ERROR ShinraMeter [(null)] - ##### (version=1.42):
##### Debug: SCreatureChangeHP need rootowner update3: 0 -> Npc 118 9000


Just that
