### ISSUE TITLE
MIssing damage dealth in every version.

### ISSUE THREAD

**Issue by nunopitbull** [neowutran/ShinraMeter#195]
Can you please just make the Damage done pasted line like this by default?

        <content>[{class}] {name}: {damage_percentage} ({damage_dealt}) | Crit: {crit_rate} | {global_dps}\</content>

Its boring to add it every single time you update, cause the update requires to re-downlaod a full new version instead a "usual" update...

**Comment by Gl0** [comment]
More than 4000 users use auto update "as usual" without issues. And even if you re-download meter manually - you can use your config files from previous version.

**Comment by nunopitbull** [comment]
Aw then i've been doing smth wrong? When I turn on PC and I have a update, it opens me a webpage to download . It doesnt auto updates itself :o
Maybe you can fix that? Or change the way it works?

**Comment by nunopitbull** [comment]
(but you could add that line as I have to default :P It stays well organized and detailed ^^

**Comment by Gl0** [comment]
It opens web page with list of changes **after** update

**Comment by nunopitbull** [comment]
aw...I don't evne notice that. Ok ty. I'll keep an eye on it
