### ISSUE TITLE
Crash on logging out (error.log)

### ISSUE THREAD

**Issue by nunopitbull** [neowutran/ShinraMeter#196]
2016-09-16 12:51:46,811 [6] ERROR ShinraMeter [(null)] - ##### (version=1.36):
##### Debug: DATABASE FAILURE: skill source: PlayerSource is null.SourceEntity = Source = source = 91-9B-05-00-00-80-04-00entitysource = 
2016-09-16 12:51:46,847 [9] ERROR ShinraMeter [(null)] - ##### (version=1.36):
##### CRASH #####
O valor não pode ser nulo.
Nome do parâmetro: key
   em System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   em System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   em DamageMeter.Database.Database.GetSkills(Int64 beginTime, Int64 endTime) em G:\Shinra2\DamageMeter.Core\Database\Database.cs:line 322
   em DamageMeter.DataExporter.GenerateStats(NpcEntity entity, AbnormalityStorage abnormals) em G:\Shinra2\DamageMeter.Core\DataExporter.cs:line 64
   em DamageMeter.DataExporter.Export(SDespawnNpc despawnNpc, AbnormalityStorage abnormality) em G:\Shinra2\DamageMeter.Core\DataExporter.cs:line 190
   em DamageMeter.NetworkController.PacketAnalysisLoop() em G:\Shinra2\DamageMeter.Core\NetworkController.cs:line 465
   em System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.ArgumentNullException: O valor não pode ser nulo.
Nome do parâmetro: key
   em System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   em System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   em DamageMeter.Database.Database.GetSkills(Int64 beginTime, Int64 endTime) em G:\Shinra2\DamageMeter.Core\Database\Database.cs:line 322
   em DamageMeter.DataExporter.GenerateStats(NpcEntity entity, AbnormalityStorage abnormals) em G:\Shinra2\DamageMeter.Core\DataExporter.cs:line 64
   em DamageMeter.DataExporter.Export(SDespawnNpc despawnNpc, AbnormalityStorage abnormality) em G:\Shinra2\DamageMeter.Core\DataExporter.cs:line 190
   em DamageMeter.NetworkController.PacketAnalysisLoop() em G:\Shinra2\DamageMeter.Core\NetworkController.cs:line 465
   em System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal

Int32 FindEntry(TKey)

**Comment by nunopitbull** [comment]
Translation off:
O valor não pode ser nulo. = value can't be null
Nome do parâmetro: key = Parameter name: key

**Comment by Gl0** [comment]
Yeah, known bug, fixing now.
