### ISSUE TITLE
Meter doesn't automatically reset a new fight

### ISSUE THREAD

**Issue by Cupcakes123** [neowutran/ShinraMeter#198]
Not sure if anyone else has this issue, but my meter doesn't seem to know when a new fight starts. So it'll keep displaying the previous one.

**Comment by Gl0** [comment]
where does it happen, what boss?

**Comment by Cupcakes123** [comment]
In SSH. It shows the first boss's stats, but it didn't for the second or third :C

**Comment by Cupcakes123** [comment]
I pressed "Delete" and it erased everything, but it still doesn't reset it. My configs are stay topmost, count bosses only, count party members only, and invisible when no stats.

**Comment by Gl0** [comment]
So, problem is not "no reset" but "stop counting".
Is there anything in error.log?

**Comment by Cupcakes123** [comment]
Where can I find the error.log?

**Comment by Gl0** [comment]
near shinrameter.exe

**Comment by Cupcakes123** [comment]
is this it? 

2016-09-18 15:32:57,272 [6] ERROR ShinraMeter [(null)] - ##### (version=1.44):
##### Debug: Low priority Received: 44942028
44942172: 32
44942204: 16
44942220: 16
44942236: 151
44942387: 42
44942429: 32
44942461: 29
44942490: 75
44942565: 20
44942585: 20
Queue length:1001
New Queue length:1001
2016-09-18 15:33:23,083 [8] ERROR ShinraMeter [(null)] - ##### (version=1.44):
##### Debug: Low priority Received: 44956321
44956425: 16
44956441: 16
44956531: 20
44956551: 20
44956612: 16
44956628: 190
44956818: 42
44956860: 32
44957070: 20
44957090: 20
Queue length:1001
New Queue length:1001
2016-09-18 15:33:23,280 [6] ERROR ShinraMeter [(null)] - ##### (version=1.44):
##### Debug: Low priority Received: 44956457
44956531: 20
44956551: 20
44956612: 16
44956628: 190
44956818: 42
44956860: 32
44957070: 20
44957090: 20
44957110: 12
44957122: 25
Queue length:1001
New Queue length:1001
2016-09-18 15:33:23,329 [9] ERROR ShinraMeter [(null)] - ##### (version=1.44):
##### Debug: Low priority Received: 44956571
44956612: 16
44956628: 190
44956818: 42
44956860: 32
44957070: 20
44957090: 20
44957110: 12
44957122: 25
44957147: 29
44957176: 16
Queue length:1001
New Queue length:1001
2016-09-18 15:33:23,483 [19] ERROR ShinraMeter [(null)] - ##### (version=1.44):
##### Debug: Low priority Received: 44956892
44957070: 20
44957090: 20
44957110: 12
44957122: 25
44957147: 29
44957176: 16
44957213: 16
44957229: 151
44957380: 37
44957396: 21
Queue length:1001
New Queue length:1001
2016-09-18 16:09:29,866 [39] ERROR ShinraMeter [(null)] - ##### (version=1.44):
##### Debug: Low priority Received: 5185906
5186088: 47
5186954: 47
5187001: 47
5187048: 44
5187092: 47
5187139: 135
5187274: 47
5187321: 20
5187341: 20
5187361: 47
Queue length:1001
New Queue length:1001
2016-09-18 16:09:29,889 [44] ERROR ShinraMeter [(null)] - ##### (version=1.44):
##### Debug: Low priority Received: 5186135
5186954: 47
5187001: 47
5187048: 44
5187092: 47
5187139: 135
5187274: 47
5187321: 20
5187341: 20
5187361: 47
5187408: 47
Queue length:1001
New Queue length:1000
2016-09-18 16:10:26,895 [40] ERROR ShinraMeter [(null)] - ##### (version=1.44):
##### Debug: Low priority Received: 5912024
5912340: 47
5912387: 20
5912407: 42
5912449: 115
5912564: 20
5912584: 75
5912659: 20
5912679: 20
5912699: 20
5912719: 20
Queue length:1001
New Queue length:1001
2016-09-18 16:36:33,885 [42] ERROR ShinraMeter [(null)] - ##### (version=1.44):
##### Debug: Low priority Received: 24324286
24324355: 103
24324680: 20
24324700: 20
24324720: 21
24324741: 77
24324818: 17
24324835: 37
24324872: 20
24324892: 20
24324912: 21
Queue length:1001
New Queue length:1001
2016-09-18 16:36:33,889 [45] ERROR ShinraMeter [(null)] - ##### (version=1.44):
##### Debug: Low priority Received: 24324458
24324680: 20
24324700: 20
24324720: 21
24324741: 77
24324818: 17
24324835: 37
24324872: 20
24324892: 20
24324912: 21
24324933: 37
Queue length:1001
New Queue length:1001

**Comment by Gl0** [comment]
That means, that your meter is missing some packets either due to CPU overload, or some network card issues. You may try to increase meter priority by changing `<low_priority>true</low_priority>` to `<low_priority>false</low_priority>` in ./resources/config/window.xml. That may help, if CPU overloaded.

**Comment by Gl0** [comment]
Probably it will show stats for new boss after some time (if missed packet is not boss spawn), when unfreezing workaround do it's job and stop waiting for missed packet. But that may be a huge delay, now meter id waiting for 1000 packets in queue before ignoring missed one.

**Comment by Cupcakes123** [comment]
Oh ok, so the issue was on my end, thank you!
