### ISSUE TITLE
Unable to contact update server 

### ISSUE THREAD

**Issue by dovah4056** [neowutran/ShinraMeter#20]
Can you please add a feature that autoupdate can be on/off?Thank you

**Comment by dovah4056** [comment]
And heres the translated version I had made for Taiwan server,it's been test and work fine
https://drive.google.com/open?id=0B2yM2zeKXO3NODNnXzZrMWhKZ0E
Thank you for making this meter, Great work

**Comment by neowutran** [comment]
Thanks, I will add an option in the xml file for that

**Comment by neowutran** [comment]
done, will be in the next release
