### ISSUE TITLE
[Request] Inspect

### ISSUE THREAD

**Issue by facecatt** [neowutran/ShinraMeter#200]
Hi,

I have a request about "/inspect + name" function on TERA, atm its really boring to write "ù é è ç ï î ü û etc..".
I already try some things with a macro software and i found a temporary solution with "add friend" but its not really op so i just want to know if you can add this feature in the future (like press "KEY" for inspect) when anyone apply in your party

Thanks in advance.

**Comment by Gl0** [comment]
We can copy "/invite <Name>" to clipboard on apply request.

**Comment by facecatt** [comment]
i was thinking for an autodetect + copy/paste the name 
To not write /inspect and the name

**Comment by Gl0** [comment]
you can paste it via hotkey in shinra starting at v1.45

**Comment by facecatt** [comment]
You just update it atm ^^ so ty and i gonna try it and give you feedbacks

**Comment by facecatt** [comment]
Hi,
Apparently didnt work, tried with friend and not, raid and normal party and shinra do nothing when anyone apply
Best Regards

**Comment by Gl0** [comment]
Have you checked clipboard content after apply request?

**Comment by facecatt** [comment]
yes and is an URL

**Comment by Gl0** [comment]
will be fixed in 1.46

**Comment by facecatt** [comment]
k thanks

**Comment by neowutran** [comment]
https://github.com/neowutran/ShinraMeter/commit/2a001625dfd855ef8a7f5770a4e34feabf85b964

**Comment by sb032835** [comment]
HI
TW TERA can't use "/inspect id"
we need to use chinese "/查看 id"
and I can't copy paste /inspect id when someone apply my party in V1.45

**Comment by facecatt** [comment]
yeah he told us it will be fixed on 1.46 (for autocopy /inspect + name)

**Comment by Gl0** [comment]
Ok, will add region-specific code.

**Comment by Gl0** [comment]
Need JP an KR commands, if /inspect is not working there
