### ISSUE TITLE
Skill contagion mystic not appear in the record

### ISSUE THREAD

**Issue by realiance** [neowutran/ShinraMeter#206]
I want know if shinra does not register the debuff ''contagium''of mystic, as well as '' mana charge '' Priest  (I know are different skills) I play with mystic and priest

**Comment by Gl0** [comment]
Each moongourd record with mystic shows Contagion in debuffs.

**Comment by Gl0** [comment]
If you mean damage, inflicted by this skill - it can be seen only by mistic's meter.
As well as mana charge can be seen only by priest's meter and his target's meter.

**Comment by realiance** [comment]
thanks guys but im a noob, but how do I appear in the meter? or look. idw

**Comment by Gl0** [comment]
Rechecked with my mystic - seen both debuff (if fighting against boss) and dot (if there are someone near target to apply it).
Notice, that dot may have another name, but same icon.

**Comment by realiance** [comment]
Thak you all
