### ISSUE TITLE
[Request] CopyPaste

### ISSUE THREAD

**Issue by luxurymini** [neowutran/ShinraMeter#207]
[ 1 ]
When you paste a chat,( "professional", "name", "damage", etc. ) i want printing same padding size
I want adding option in hotkey.xml. For example,
Current :
    [{class}] {name}: {global_dps} ( {damage_percentage} ) | C {crit_rate} | D {deaths}
    print :  
           [Brawler] 루니B : 123.4만/s ( 56% ) | C 0% | D 0
           [Archer] 한글여섯글자 : 1.299만/s ( 44% ) | C 80% | D 0

I want :
    print :  
           [Brawler] __________루니 : 123.4만/s ( 56% ) | C__0% | D__0
           [ Archer] 한글여섯글자 : ___1.9만/s ( 44% ) | C 80% | D 10
           This editor does not enter spaces, just one space.  "_"  mean space
    Align the columns and rows. Much better view!!

[ 2 ]
    class name is not translated in the local language.

**Comment by Gl0** [comment]
Hm... implemented this, but it's not working correctly due to not monospaced font used by tera. At least on RU. 
Spaces have significantly less width than normal chars. Not sure, how to deal with it

**Comment by Gl0** [comment]
using double spaces instead of single for padding looks more good, but anyway names with a majority of thin letters will look more condensed than written by CAPS... probably need some real width estimator based on game font.

**Comment by Gl0** [comment]
Managed, how to make it beautiful. But need font files and names from all localizations.
Estimating via standard MS fonts looks bad.
needed files:
`\TERA\S1Game\CookedPC\Art_Data\Packages\S1UI\fonts_*.gpk `
NA and EUR use the same fonts, so needed only one from any of them + TW and JP (RU & KR already here)

**Comment by sb032835** [comment]
https://1drv.ms/u/s!ALbKXitz2dMZhN4b

**Comment by Gl0** [comment]
thanks.
Seems it's time to change autoupdate system, archived fonts have the same size as all other meter components...
