### ISSUE TITLE
ShinraMeter 1.45 doesn't work with VPN

### ISSUE THREAD

**Issue by kiwyna90** [neowutran/ShinraMeter#208]
Hello! This tool is very simple and useful!
It works without a VPN 
but i need to run a VPN for fix my latency...
and I did this:
in resources\config\window.xml
`<winpcap>false</winpcap>`
in resources\data\servers.txt
i added
`xxx.xxx.xxx.xxx NA VPN`
--- with 2 spaces between region and server name! 

but it's not working.
Help me... I'm playing on Tera NA and I'm using PureVPN.
Thanks in advance!

**Comment by Gl0** [comment]
What protocol are you using? OpenVPN, for example, should work even with winpcap enabled.
Anyway, PureVPN - is native vpn solution, that doesn't require servers.txt modification.
If it's not working with winpcap disabled - recheck firewall rule.

**Comment by kiwyna90** [comment]
My firewall is disabled in Windows 10! I dont use it 💃 
I tried to run with winpcap enabled and without servers.exe modification... but it doesn't work!

How can i check what protocol am I using... ?

**Comment by Gl0** [comment]
I don't have PureVPN client app, but it seems have choice for protocol.
+They support a bunch of protocols that works even via native windows connection setup dialog or on home router.

**Comment by kiwyna90** [comment]
Yes, i figured out! :D I'm using PPTP protocol! What kind of protocol can I use? Any suggestion?

**Comment by Gl0** [comment]
when pptp is set up by windows it works with meter in raw sockets mode.

**Comment by kiwyna90** [comment]
Raw sockets without VPN works... but i need to run with VPN.

**Comment by Gl0** [comment]
try to setup connection via windows, not client app. or try openvpn protocol

**Comment by kiwyna90** [comment]
I setup a VPN connection PPTP via windows (without using client) but it doesn't work...

**Comment by Gl0** [comment]
Rechecked right now with PPTP - meter is working well in raw sockets mode. Probably you messed something with configuration. May be changed not actual config file. Or firewall issue (it's may be disabled for your normal network connection, but enabled for dial up).
If you have router (you should have, or living with firewall disabled is bad idea) - you can set up vpn from router - that works 100% transparent to your system.

**Comment by kiwyna90** [comment]
Hey @Gl0 thank you so much for your help! I had to disable my firewall on my router 💃
