### ISSUE TITLE
Discord Connector Guildname

### ISSUE THREAD

**Issue by DarknessMico** [neowutran/ShinraMeter#209]
Hello,
I tried to use the discord connector to post the daily quests but i ran into a problem while editing the window file. According to the example I have to add the server and the guild name, but how do i add a guild name with a whitespace. The problem was that after i saved the document with the whitespace in the guild name the file was resetted. According to the example it seems like the capitalisation is ignored for the server and the guild name. How should the following code look like if the guild name would be something like "Red Rum". Thanks a lot and have a nice day.

        <killian_redrum>
            <guild_infos_channel>228900710643793920</guild_infos_channel>
            <guild_quests_channel>228900710643793920</guild_quests_channel>
            <server>214778491776794624</server>
        </killian_redrum>

**Comment by neowutran** [comment]
Just remove any space from the guildname. 
If your guildname is "Red rum", you can just write "redrum". Same with server name
