### ISSUE TITLE
I want to use this meter on K TERA

### ISSUE THREAD

**Issue by s2021369** [neowutran/ShinraMeter#21]
Hello :) My name is Story who plays K TERA.
I heard you added TW server to your meter lately.
I want to know how to use it on K TERA.
Because our publisher was changed, maybe it can work.
I play velik server and velik new IP is 183.110.3.7
Thank you for your answer ^^

**Comment by neowutran** [comment]
Hello =), thanks for the info.
In order to make it work on KTera, I need some data (opcodes + database)
sb032835 is looking for that too: https://github.com/neowutran/ShinraMeter/issues/19

I'm downloading KTera, I will probably need some days till the end of the download. 
IF the KTera version is not too much different from the EU/NA/RU/TW version, that should be working in few days.

**Comment by neowutran** [comment]
Hi, I have some problem to make KTera running. I get a "AttachAuth error 20000" when I try to run the launcher (with and without using a korean VPN). Do you have an idea / do you have a tutorial on how to properly create an account / install nexon ktera for someone who doesn't know a single word of korean? x)

**Comment by sb032835** [comment]
you can use Official Website to start game
http://tera.nexon.com/main/index.aspx

**Comment by neowutran** [comment]
hu, from the website I get "테라는 18세 이용가 게임물입니다.". 
Look like I somehow need to validate that I m over 18? Any way to do that?

**Comment by s2021369** [comment]
You need an adult account

**Comment by neowutran** [comment]
Okey, seems that I need a korean phone number / id to validate the account (=> google traduct). I don't have any, sooo.
In order to make this meter work, you will need to find someone who play on KTera & who is able to extract the opcode & database.

**Comment by s2021369** [comment]
Teach it to me. I will extract obcodes for you

**Comment by neowutran** [comment]
I highly recommand you to NOT do it yourself. KTera use Xigncode to protect the game (other region doesn't use that). You will have a hard time to manage to get opcodes and database. 

( some info I found about xigncode: 
- https://www.reddit.com/r/DFO/comments/30tcb6/xigncode_looks_at_all_files_youve_accessed_in_the/
- http://www.unknowncheats.me/forum/anti-cheat-bypass/125231-dll-injection-xigncode.html
)

The basic tutorial for the opcodes are here: https://github.com/GoneUp/Tera_PacketViewer/tree/master/Opcode%20DLL

The basic tutorial for the database are here: https://github.com/neowutran/TeraDpsMeterData/blob/master/copypaste-tuto/Gothos-databasekey.txt

I haven't be able to check how xigncode work on this game (doesn't have activated account).
But there are high probability that xigncode will detect cheatengine and block it.
Xigncode is also know for sending report over the network. I don't know how their are using these data, but there is a chance that if you get detected injecting DLL into the program, you can get ban if they choose to.  

Maybe @sb032835 can try to do it or maybe he have more information, as that was him who tell me about xigncode. Or if there are a way that I can get an activated account that I can fuck up, I can try it myself. 
But anyway, getting opcode & database from KTera will probably be a lot trickier than any other region.

With that, you have all the information that I have.

**Comment by neowutran** [comment]
Use cheat engine with ktera => need to modify something + window tile, then recompile cheat engine. That should be enouth to not be detected by Xigncode. 

The dll should not contains MessageBox. And you probably need to activate some option with the injector like remove PE header & hide module

Still, can't check that without an activated account

**Comment by tamanegion** [comment]
Hello. I'm really interesting about this topic.
In Japan, TERA is protected by XIGNCODE too. And, no one got opcode until today.
Could you try it? If you need, I can provide JTera accounts.
Regards,

**Comment by neowutran** [comment]
IF you are ok with this warning: 
https://github.com/neowutran/ShinraMeter/issues/21#issuecomment-177876511

then I can try. as far as I know, I need a Japan cellphone number to make an account for JTera? 
And everyone outside japan are IP-Block?

If so, then I will need you to give me an account
( neowutran@gmail.com )

I can't garant you that I will success, but at least I will try ^^

**Comment by sb032835** [comment]
I think T-tera and J-tera the opcode maybe the same
you can try it

**Comment by tamanegion** [comment]
Thank you for kind information.
I tried with Shinrameter v0.66, couldn't get any result .
Maybe, JTERA' opcode differs from TW (or my procedure was wrong).

my settings:
resouces\config\window.txt:
<language>TW</language>

resouces\data\servers.txt:  //203.141.240.215 & 216 is JTERA server IP
203.141.240.215 TW [TW] Yulien
203.141.240.216 TW [TW] Elinu

**Comment by tamanegion** [comment]
oops,my way was wrong.
J-TERA's opcode is same as TW-TERA.
Perfectly working :)
http://i.imgur.com/EUxrgAq.jpg

**Comment by s2021369** [comment]
@tamanegion How did you use the dps meter on J TERA? K TERA use Xigncode3 too.
But it doesn't work. I changed Server IP and used TW opcode.
Tell me the exact infos.

**Comment by s2021369** [comment]
Our server IP is 183.110.3.7
I modified server.txt
183.110.3.7 TW
Should I do other things?

**Comment by tamanegion** [comment]
I just edit: 
resouces\config\window.txt
resouces\data\servers.txt
as u know.
And, it was important for me that launch DPS meter before launching TERA.

If impossible, same ver. may possibly have same opcode. 
TERA  ver.Ninja (only KR) has opcode _ A_. 
ver.Brawler (ex. US, TW, JP,...)has opcode _B_.
This is  a hypothesis.

**Comment by s2021369** [comment]
@tamanegion Thank you for your answer ^^

**Comment by neowutran** [comment]
Found a way to get the database even with xigncode.
Looking for opcode now

**Comment by neowutran** [comment]
Good, I succeded to get opcode + database with the JTera client (xigncode3) 
When you launch the game, xigncode3 need some time. 
Do want you want in the memory, inject what you want in the game BEFORE xigncode3 finish to initialize and no problem, you get everything

**Comment by neowutran** [comment]
(JP DB: https://github.com/neowutran/TeraDpsMeterData/commit/5333db260179f1d77099bb39748efae2a23d640b)

**Comment by s2021369** [comment]
o__O J TERA client also have xigncode3? K TERA too.
But it doesn't work on K TERA.
Can I know how to use your dps meter on J TERA?
Or it works well without anything?

**Comment by neowutran** [comment]
That should work without anything for JTera (V0.68)

How can you get the opcode + database? 

I don't know what step is really mandatory, but here is how I did it: 

(METHOD 1)
- Slow down your computer. I used that: https://github.com/neowutran/Freezer/blob/master/ConsoleApplication1/ConsoleApplication1.cpp
- Click the Start game button  (In JTera, when you click on Start game, a small  window popup with "xigncode3 tera" and a loading bar)
- Rush into CheatEngine and follow the tutorial
 * When xigncode3 is initialized, it will detect cheatengine, and crash the game

Another way to have the timed needed to use cheatengine: 
(METHOD 2)
- Launch the game
- Once you are in the character selection screen: launch cheat engine
- Xigncode detect cheat engine and make the game crash (on my computer I saw a popup with something like "BlaBlaBla memory read error BlablaBla Tera crashed")
- DON'T CLOSE THIS WINDOW
- At this point,  cheat engine is not active anymore (the game as crashed). But everything is still in the RAM. So, launch cheat engine, and do what you need to do.


I used the second method to get the database.
And the first method for everything else. 
I did that 4 time. 
The first time I get the database
The second time I run the search string for "I_TELEPORT" and get the offset
The 3 time, I get the function start offset for opcode
-> write dll & compile
The 4 time => Inject the dll and tada! opcode available

That a stupid way to do it. But that work & not really hard =p

**Comment by sb032835** [comment]
I try method 2
game crash when I open cheat engine,and I can not get datebase

**Comment by neowutran** [comment]
Yes, the game crash. 
On my computer when I do the method 2, a small window popup to tell me "memory read error, crash" 
Then I launch cheat engine & get everything

**Comment by neowutran** [comment]
if this window doesn't show up, use method 1, that won't be a problem

**Comment by sb032835** [comment]
yes i have a small window to tell me 
"Run-time error occurs the game has nothing to do with the program
The game has nothing to do with the termination of the program and then start the game"
http://imgur.com/2YBamHE

**Comment by neowutran** [comment]
IE & xigncode windows 
So the tera window who tell something like "memory read error,  crash" doesn't show up for you. 
just do the method 1 then ^^

**Comment by sb032835** [comment]
how can i send u account for kTERA

**Comment by neowutran** [comment]
I read this sometime: neowutran@gmail.com

But someone from Ktera must succeed to get opcode + database. 
You can check those step with JTera as I know it work for JTera

**Comment by sb032835** [comment]
Date: Tue, 23 Feb 2016 01:45:14 -0800

**Comment by neowutran** [comment]
ok ^^ I will try to get ktera opcode + database

(be carefull, you just send your credential to everyone who follow this project)

**Comment by sb032835** [comment]
wow

**Comment by s2021369** [comment]
@neowutran Thanks~

**Comment by neowutran** [comment]
Done! =D (using only method 1 this time)
opcode + database + servers ip 
everything is here: https://github.com/neowutran/TeraDpsMeterData

I will make a new release today or tomorrow


But I will really need some ppl to maintain different region. 
I won't be able to maintain EU, NA, TW, JP and KR all by myself

**Comment by neowutran** [comment]
KR support with V0.69
download link in the wiki

**Comment by sb032835** [comment]
http://imgur.com/0WRyHj5
ShinraMeter work on KTera
Skill name displayed as numbers
maybe I am Lv54

**Comment by neowutran** [comment]
hum, nop, I forgot to extract some skills from the database x) will fix that later

**Comment by s2021369** [comment]
Thank you very much!!

**Comment by neowutran** [comment]
np =) Can you check if you have issue to display the dps meter on twitch? 
like here #45  ?

**Comment by s2021369** [comment]
@neowutran me?

**Comment by s2021369** [comment]
@neowutran Q_Q...When I attack any mosnter, I see this error
"Fatal error"
http://i.imgur.com/5iXf2l7.jpg
What should I do?

**Comment by neowutran** [comment]
You didn't change the default language. Open "resources/config/windows.xml" and change the language to "KR"

**Comment by neowutran** [comment]
(no other language have a support for the ninja class)

**Comment by neowutran** [comment]
https://github.com/neowutran/ShinraMeter/wiki#configuring-language

**Comment by s2021369** [comment]
oh I will try it!!

**Comment by sb032835** [comment]
run meter second time,windows.xml will appear

**Comment by s2021369** [comment]
It works well!!
I want to know last one.
How can I reset and restart the dps record?

**Comment by neowutran** [comment]
Yay! =) 
default hotkeys are here: https://github.com/neowutran/ShinraMeter/wiki#configuring-hotkeys

**Comment by s2021369** [comment]
What is "Suppr" key..?
I can't find it

**Comment by sb032835** [comment]
@s2021369 
we want to choose Brawler or Lancer in ninja version,who's DPS is BETTER
we need watch your twitch to see DPS Meter,GOGOGO twitch ONLINE!

**Comment by neowutran** [comment]
Del / Delete keys (humm, I think "suppr" is the french name x) )

**Comment by s2021369** [comment]
@sb032835 We aren't allowed to use the dps meter :)
But I can notice the result to you later

**Comment by neowutran** [comment]
The "clock" button is to switch between: 
- Encounter based detection (only the boss entity itself)
- Encounter timer based detection (the boss entity + every other entity you have fought during the boss fight)

Try it, that would be better than these explainations

**Comment by sb032835** [comment]
@s2021369 
thank you
but our version have not 특성 , maybe wil different
You can state your opinion please

**Comment by s2021369** [comment]
@neowutran Thank you very much!!!

**Comment by neowutran** [comment]
@s2021369 
np =) 

That kind of tool is not officially allowed on KTera? :/
In EU, we asked gameforge about this kind of tools years ago, and they post an announcement to officially allow us to use this kind of tools ^^ (that was 2 or 3 years ago)

**Comment by s2021369** [comment]
This tool isn't officially allowed on K TERA :(

**Comment by s2021369** [comment]
@neowutran Can I request you that you stop distributing k tera ver?
(At least please add to the key or password)
I already know your effort and thank you for your kindness.
Though I know this is a rude request, I should tell you it.
But our publisher (Nexon) is fussy and they will blcok your dps meter fastly.
(They noticed we don't allow the dps meter)
To be honest, our community is very aggressive and they will fight each other with the dps meter.
K TERA will be destroyed coz we couldn't use the dps meter so far.
I'm sure that it should happen.
K TERA ppl are different from NA, EU, RU.
They will blame other players and bicker with them.
I don't want it....

I want to study class dps, rotation, glyphs, talents etc for now.

Thank you for reading. Come to my stream later.
I will notice you!! I think you already know me. 
(http://www.twitch.tv/s2021369)

**Comment by s2021369** [comment]
Btw I love you <3

**Comment by kuko0411** [comment]
@s2021369 password would be pretty useless. Almost everyone with basic coding and googling skills would be able to bypass that - since the code is open-source.

On the other hand - are you absolutely sure people would fight each other with it ? There were countless threads on NA/EU forums how that would happen if dps meter came out, a lot of people were worried about this.

And it's just not really happening in my experience.

**Comment by s2021369** [comment]
It already happened on k tera forum without the dps meter.
They use the dps meter to judge other players.
The most important thing is that Nexon will block this meter.

**Comment by Gl0** [comment]
The only way to completely block dps meters is to change traffic encryption.

**Comment by kuko0411** [comment]
I dunno about that - can't they get the protection software (that xigncode3) to scan for the known meters ? That would get pretty hard/annoying to get around.

**Comment by Gl0** [comment]
We run dpsmeter on the same machine that we play tera only for our comfort. No protection can forbid us running it on router/proxy.

**Comment by kuko0411** [comment]
ah yes, that would work. But that would be not what some random user would be able to setup, would it ?

**Comment by neowutran** [comment]
I think the ways they have to "block" the dps meter are: 
- to change the traffic encryption
- to found a way to somehow fully load xigncode3 before putting anything usefull in the RAM (so I won't be able to get opcode +  database as easily as now)
- add a window name detection or something like that for xigncode3, but that won't be really a problem

@s2021369 
"(At least please add to the key or password)" 
everything is open source, that pointless

"Our publisher (Nexon) is very fussy and they will blcok your dps meter fastly."
I had fun to found a way to get opcode + database with xigncode3 for KTera/JTera. If they found a way to block the dps meter, I will have fun with that. Maybe I will be able to bypass their block, maybe not, but that will be fun, and i will probably learn many things ^_^ 

"To be honest, our community is very aggressive and they will fight each other with the dps meter.
K TERA will be destroyed coz we couldn't use the dps meter so far.
I'm sure that it should happen.
K TERA ppl are different from NA, EU, RU.
They will blame other players and bicker with them.
I don't want it...."

"It already happened on k tera forum without the dps meter.
(No one can't use the dps meter on k tera so far)
They say they will use the dps meter to judge other players."

I don't know  about the KTera community. But whatever the region, you can use the dps meter to test your crit rate with differents gear, trying to improve your dps etc... 
or, you can bash other player about their dps ^_^ that just a tool, won't change ppl mind, if they want to bash other player, they will, with or without this tool

So, if someone from KTera want to maintain the dps meter, with or without my help, all the needed informations / software / tools to get the opcodes + databases are available.
I won't try to stop that, and any way, even if I wanted to, I can't 


And no problem, I often go to your stream =p

**Comment by s2021369** [comment]
ok ~ Thank you for answer

**Comment by s2021369** [comment]
I shared your dps meter on inven

**Comment by neowutran** [comment]
okay ^_^

**Comment by s2021369** [comment]
Hellong @neowutran ~
How are you?
I want to talk with you.
Can I contact you? your email or discord
(Everyone can see this conservation)

**Comment by neowutran** [comment]
Hi ^_^
Fine and you?
You can contact me here:
neowutran@gmail.com
