### ISSUE TITLE
v1.50 not working with VPN

### ISSUE THREAD

**Issue by Skxpath** [neowutran/ShinraMeter#216]
Hi,

I'm using v1.50 and my VPN is not working. I am using ReduceTheLag.

I added the firewall exception, disabled winpcap (for raw sockets), and added the IP on the server list.

ShinraMeter will detect the VPN on connect, but it won't change to my native server after log in. It stays as "VPN". Of course, when I hit a boss the VPN will not detect any damage.

It will work if I do not use a VPN.

I play on Tera NA,

Thanks in advance!

**Comment by Gl0** [comment]
Was it working before 1.49?
Can't check what wrong with RTL myself, don't have NA or EU client. Other regions are not supported by RTL.

**Comment by Skxpath** [comment]
It hasn't worked on any version for me. I've been trying to make RTL work with it.

**Comment by Gl0** [comment]
Not sure it can, RTL injects his own dll into game process and if it use any traffic encryption - it would not be capturable even in raw sockets mode.

**Comment by Skxpath** [comment]
Hmm.. okay, thanks!

**Comment by Gl0** [comment]
but you can try 1.48 or bit earlier version to check. There was some optimizations in raw sockets mode in 1.49+, that may cause proxy connection to be discarded if it has too big overhead.

**Comment by Skxpath** [comment]
1.48 seems to work successfully. That might be the problem.

**Comment by Gl0** [comment]
Ok, I'll increase accepted overhead in next version

**Comment by Gl0** [comment]
check with 1.51

**Comment by Skxpath** [comment]
1.51 seems to work as intended, no problems as far as initial testing goes.

**Comment by Gl0** [comment]
Hm.. strange, don't see debug with overhead lengh. You have debug option disabled in config? Or may be you've done something wrong while configuring 1.50 for your proxy.

**Comment by Skxpath** [comment]
Debug is set to true. I did the same things with 1.50 and 1.48. In 1.51 theres the new server-overrides file. I moved my vpn ip to that file from 1.50 to 1.51. In both, my vpn was detected by the meter, but in 1.50 it would not change to the server i was on, but in 1.48 and 1.51 it would.

**Comment by Skxpath** [comment]
http://puu.sh/rECys/5dc92effdf.png - Patched via autoupdate from 1.50 to 1.51.

**Comment by Gl0** [comment]
I've missed another one place where overhead may be exceeded - will add debug in 1.52 to know how much it can be and minimize it.

**Comment by Gl0** [comment]
Got overhead values, it's 500-600 bytes, while 1.50 had limit at 256. Probably will limit it at 1Kb in future versions.

**Comment by Gl0** [comment]
Maximum is about 1.3kB, set 2Kb limit.

**Comment by vinc321** [comment]
hey may i ask i am totally fresh to programming.....do i just type the vpn server in override text without the # for example 108.41.244.241 NA Some Random Test Server
and how to i disable npcap to use raw sockets thanks for your time!

**Comment by Gl0** [comment]
https://github.com/neowutran/ShinraMeter/wiki#network
