### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by AriandelOni** [neowutran/ShinraMeter#219]
My dps meter crashing every time .-. in 1-2nd dungeon after launch
already tried to reinstall but it's not helped
[error.log.txt](https://github.com/neowutran/ShinraMeter/files/523443/error.log.txt)

(sry for bad eng, I'm from ru.)

**Comment by Gl0** [comment]
Да, видел такую ошибку в логах, не очень понятно в какой именно ситуации она возникает.
