### ISSUE TITLE
Incorrect location for Open World BAM

### ISSUE THREAD

**Issue by TChan626** [neowutran/ShinraMeter#22]
As you can see, the Meter says that the Naga Battlemaster (and the Moaloths) are in Arx Umbra, but they're actually in Ex Prima.

![bc812f12e4 1](https://cloud.githubusercontent.com/assets/6600476/12687786/004c5632-c6a0-11e5-8f0e-f74b4decc061.png)

**Comment by neowutran** [comment]
Thanks for the info, will look for that

**Comment by Gl0** [comment]
When we trying to get continent name for 7031, where huntingzone 181 is located - there are 4 different names. I can't distinguish what name is correct, and take the first one. Seems I need to add some exceptions or heuristics.

**Comment by Gl0** [comment]
Updated extractor, add some heuristics, check with other locales

**Comment by neowutran** [comment]
Fixed thanks to GI0, the fix will be added with the next release
