### ISSUE TITLE
[SUGGESTION] Adding notifications to debuffs.

### ISSUE THREAD

**Issue by Bertillee** [neowutran/ShinraMeter#225]
Hello,

Just as a notification for crystalbind has been implemented, it would be great if a notification for endurance debuffs were added. For example, a notification when hurricane procs (sometimes the UI bugs and I can't see if it procs or not, or maybe mistaking it with lancer debilitate) or when generally endurance debuffs run out of time.

Thanks for taking your time to read this.

**Comment by Gl0** [comment]
Not sure, how to filter it out. Spamming on all endurance debuffs seems bad idea. Notify on specific debuffs that may proc or not - may be usefull, but may also be annoying.
If debuff is not shown in UI, it will be probably missed by meter.
For debuffs running out - there probably will be another floating window with increased-size icons of debuffs, applied by meter user class, with stack and timer, not sure whether sound needed, or may be just change border color when 1-2 sec left.

**Comment by Bertillee** [comment]
Perhaps giving a notification just when hurricane and contagion are on. Damage dealers usually sync their brooches and burn skills when contagion and hurricane are on, but you may miss it because you're not focused to the debuff bar (usually happens to me as DD, even though I main mystic and I'm not the kind of guy that does 2m dps). Honestly, I believe that if it's doable, it would improve the QoL for DDs, tanks (lancer buffs) and for mystics (regarding the hurricane proc).

**Comment by neowutran** [comment]
Ok for hurricane. 

If we add contagion, it s better to add enrage notification too.
