### ISSUE TITLE
no server

### ISSUE THREAD

**Issue by Sirachasauce** [neowutran/ShinraMeter#227]
After updating to the newest patch, my meter keeps saying no server, ive tried re-installing it, but nothing works.

**Comment by neowutran** [comment]
reinstall npcap & restart your computer 
https://github.com/neowutran/ShinraMeter/wiki/FAQ#i-m-on-w10-meter-was-working-but-doesnt-work-anymore

**Comment by Gl0** [comment]
My fault with raw sockets, will be fixed in 1.57
