### ISSUE TITLE
Paste Dps issue

### ISSUE THREAD

**Issue by aeriazip** [neowutran/ShinraMeter#229]
Whenever i paste the dps it is all spaced out 
Example:

[Sorcerer]  ________________ Aeria.So: 32% ( 193M) | Crit: 34% |  487k/s

Any way to fix that?
There is a bunch of spaces, i used underscores because it won't show all the spaces.

**Comment by Gl0** [comment]
That's not a bug, each field in the table is aligned to max length of its column from all rows, so that whole table looks like table. See #207 
Can be disabled in config/menu.

**Comment by aeriazip** [comment]
i looked at the page but it didn't show me what to look for or what to change/disable sorry for not understanding :/

**Comment by Gl0** [comment]
uncheck "Format paste string" in menu

**Comment by aeriazip** [comment]
thakns
