### ISSUE TITLE
inconsistent hotkeys data after update

### ISSUE THREAD

**Issue by Gl0** [neowutran/ShinraMeter#23]
reset_current section is not appearing in hotkeys.xml if this file exists, but the default values are still applied and cause some users to not understand, why them can not set control-end as reset hotkey.
Also they asked to add availability to use alt modifier not only with reset hotkey, but with other too.

**Comment by neowutran** [comment]
"Also they asked to add availability to use alt modifier not only with reset hotkey, but with other too."
Using alt modifier for anything other than reset will cause problem. 
When you paste the DPS, I simulate the key "Enter" to make multiple line. 
Sooo, If I allow the alt modifier, the game will receive a hotkeys "alt + enter", in tera, this hotkeys cannot be disabled and will switch screen mode (between fullscreen, windowed fullscreen & windowed). 
So unless you know a way to disable the "alt + enter" hotkeys in tera, I won't add that. 

"reset_current section is not appearing in hotkeys.xml if this file exists, but the default values are still applied and cause some users to not understand, why them can not set control-end as reset hotkey."
Ok, I will see for that

**Comment by Gl0** [comment]
fixed in 0.59
