### ISSUE TITLE
Notification Sound

### ISSUE THREAD

**Issue by michaelcarno** [neowutran/ShinraMeter#231]
When i trying to set custom notification sound it doesnt work. But if you set checkbox "Switch to another sound system" it use default sound and works fine for every notification.
Step to reproduce for me: 
1) Set custom sound
2) Test sound with button "Test sound" (you should hear sound )
3) Open Tera, enter in any dungeon, use enrage/contagination/Hurri(if proc)
4) See notification box, but no sound.

**Comment by snwFlake** [comment]
Same problem here with 1.58.

First few enrage beeps come through, then it suddelny stops beeping.

**Comment by neowutran** [comment]
reopen if you still have issue with 1.60

**Comment by snwFlake** [comment]
"reopen"

**Comment by snwFlake** [comment]
fixed with 1.63

close request
