### ISSUE TITLE
[REQUEST] Advanced export options

### ISSUE THREAD

**Issue by snwFlake** [neowutran/ShinraMeter#233]
Hey there,
first of all: thanks for creating/maintaining this project, good job!

As for my suggestion: I would like to be able to choose the pattern, the directories for auto export are created.
The current hierarchy follows ../{Dungeon}/{Boss-Date-Char}... 
I play zerk aswell as brawler and myst. So my wish would be a hierarchy like ../{Char}/{Dungeon}/{Boss}.
Or even better, a fully configurable method.

I already digged through ExcelExport.cs, but I'm not comfortable with javascript nor c#.
Have a good day

**Comment by Gl0** [comment]
There is one potential issue - we don't know player name when exporting saved encounter. Now we just omit it in that case, but if it will be folder name - it should be named somehow.
+ there may be crashes if users messed something in config.

**Comment by snwFlake** [comment]
Fully agree with the potential of crashes due to improper user input. First thought was checking the return value of the dir-create operation. If it fails there could be a default/fallback.

The character name should fly over cable as you log in. A tmp-store in some manner should do the trick. 
I must admit, that I have no clue how you parse the traffic and if thats even possible though.

**Comment by Gl0** [comment]
We store current player name, but you can relog to other character and then push save on old encounter.

**Comment by snwFlake** [comment]
My bad, forgot about the old states beeing still present...

**Comment by snwFlake** [comment]
fixed it for now, by creating a .bat which is called after the files are created. batch itself just strips the filename and creates/moves stuff in the pattern i like.
