### ISSUE TITLE
Meter not showing

### ISSUE THREAD

**Issue by Menowar** [neowutran/ShinraMeter#234]
Hi

So I was playing 1 day and all of a sudent my meter disapeared, from showing when my tera wasa open. I set it to always show but when i lunch/open tera it doesnt show in game, when i alt tab tho it shows. I can still hear the notifications for ccb and enrage, when we are done i can paste the meter in chat. Every thing works but its just not showing up in my game. I tryed restarting the whole PC and reinstaling the meter but it stil doesnt show in the game.

**Comment by Gl0** [comment]
switch game from fullscreen mode
