### ISSUE TITLE
No server detected

### ISSUE THREAD

**Issue by bouncyharu** [neowutran/ShinraMeter#237]
Hi,

Sometimes it works sometimes it won't. TW server. May I know how to solve this issue ？ thanks!

**Comment by neowutran** [comment]
try reinstalling npcap. But without anymore data, can't help much more

**Comment by hsluoyz** [comment]
Please try latest installer at: https://github.com/nmap/npcap/releases

**Comment by Mitsunee** [comment]
I have both the firewall exception and npcap installed, yet it never detects Yurian. I tried booting up Tera from my HDD, as I had just moved it to my SSD, no change either.

**Comment by Gl0** [comment]
Firewall exception is needed only if you are using raw sockets, not *pcap. To get it working - exception should point to exact meter .exe that you are launching, without any macro in the path, + winpcap mode should be disabled in window.xml.
If you want to make it work via npcap - npcap should be installed in winpcap compatible mode, if you are using proxy or vpn - you should also install npcap loopback adaptor. If it still not working - we need details about your internet connection type, may be we missed something and it should be parsed in some other way.

**Comment by Mitsunee** [comment]
I reinstalled npcap again, which didn't help, but when I moved the folder back to my desktop, it worked again, so I guess it's using raw socket mode, even though I don't want it to. I'ma dig into this settings file a bit, there's a maintenance today anyways

**Comment by Gl0** [comment]
If you can send logs to @hsluoyz - that may help him to make npcap working in your setup.

**Comment by hsluoyz** [comment]
Please provide me the DiagReport and other install logs based on: https://github.com/nmap/npcap#diagnostic-report

**Comment by b104050409** [comment]
I try latest Npcap installer，but it still no server detected
I installer 「npcap-0.78-r5」

**Comment by Gl0** [comment]
which type of internet connection you are using?

**Comment by b104050409** [comment]
Dial-up lnternet connections
