### ISSUE TITLE
Spamming notifications

### ISSUE THREAD

**Issue by Qarinna** [neowutran/ShinraMeter#239]
Hello
New shinra is spamming useless notifications during fight "blessing of shakan" and other things non stop during fight, which have no real use. 
TN and other debuffs are nice, but the sound spam is too much, especially coming from blessing. 
Should be improved or just given option to turn off some notifications

**Comment by Gl0** [comment]
All notifications are configurable. And yes, we missed 805102 (Blessing of Shakan III) in config. Just add
```
			<abnormality>805102</abnormality>
```
after 
```
			<abnormality>805101</abnormality>
```
in ./resources/config/events-priest.xml

**Comment by Qarinna** [comment]
How can I remove debuff notifications? 
I know when to cast what, its rly annoying. 
I feel what i need is what we had in the previous version - contagion, enrage and hurricane

**Comment by Gl0** [comment]
https://github.com/neowutran/ShinraMeter/wiki/Events

**Comment by careful7j** [comment]
Thats definitely not a solution. Please add some checkboxes for every "beep" to application settings.

**Comment by Qarinna** [comment]
Yes I also think we should have UI for this, it requires too much work. 
Or at least by default most of them should be turned off.
