### ISSUE TITLE
Poison Blade DOT not counted with Poison Blade skill

### ISSUE THREAD

**Issue by NullableZK** [neowutran/ShinraMeter#24]
![pbdot](https://cloud.githubusercontent.com/assets/17015060/12734187/fccf9cc0-c90c-11e5-8213-152895d02eb4.png)

As you can see in the screenshot, poison blade's DOT isn't counted along with the actual poison blade skill. It treats them as separate skills.

**Comment by neowutran** [comment]
thanks for the info

**Comment by Gl0** [comment]
Half of hots/dots doesn't contain info about skill level in it's name, or even have name of the glyph in client files. You can strip skill lvl before combining skill strings, but it would help only partial.
As for me, separation dot from skill is not critical at all.

**Comment by neowutran** [comment]
yup, If I found an fast & efficient way to fix that, I will fix that. But not top priority

**Comment by Gl0** [comment]
Tried to export skillids into hotdot.tsv - there are abnormalities, that used by different skills and skills, that have multiply abnormalities at one time. And that's only for direct skill abnormalities, without abnormality chains, which should give another bunch of strings. Not sure how to use such data, but you can load only skillid's from strings with duplicate abnormality id to have list of skills that can cause this abnormality. Or may be leave it as is now and don't bother.=)

**Comment by Gl0** [comment]
Have you seen my last update to extractor? (not sure, whether mention in commit comment generates notification)
And do you need skillid's in hotdot.tsv, or I should revert it back to unique strings without skillid's?

**Comment by neowutran** [comment]
Yup ^^ ( that work, I received a notif )
And the current structure of the file is good, I have all I need ^^ 
(I will need time before being able to add consumable / buff detection in the code)
