### ISSUE TITLE
Unable to mute sound

### ISSUE THREAD

**Issue by noothernameisfree** [neowutran/ShinraMeter#245]
After new update, option for changing sound volume/remove sound notification was removed, any way to remove all sound manually without config?

**Comment by Gl0** [comment]
For now you can adjust system volume or edit events config, probably we'll add mute option later

**Comment by noothernameisfree** [comment]
I am okay without any "mute" option, the problem is I can't see sound volume settings in config in newest version 1.59, maybe I just can't find it, but here is screen from 1.58 meter, which in config got "sound volume" settings, but this option is somehow missing in 1.59

http://imgur.com/ZuBybQ4

**Comment by Gl0** [comment]
Sound volume is now configurable per event. And only if you alter event to use mp3 instead of beeps, cause beeps are system sounds and  their volume can't be adjusted other way than changing system sound volume in windows sound mixer.
