### ISSUE TITLE
Spam Buffs "bip"

### ISSUE THREAD

**Issue by Inesrrgg** [neowutran/ShinraMeter#247]
When I'm playing with the priest, every time "bip" because someone has buffs, not only at the beginning of the fight, too while I'm fighting.

Can I remove this? I only want the notification of enraged.

**Comment by Gl0** [comment]
Read [patch notes](https://github.com/neowutran/ShinraMeter/wiki/Patch-note), they are shown each update not for fun, but to inform users on new features, bug fixes and useful tips.
