### ISSUE TITLE
[Bug] damage received are not counter

### ISSUE THREAD

**Issue by neowutran** [neowutran/ShinraMeter#25]
bug here: 
https://github.com/neowutran/ShinraMeter/blob/master/DamageMeter.Core/DamageTracker.cs#L359
will fix that tonight

**Comment by Gl0** [comment]
Before this fix received damage was counted to the first appeared mob with same name, after that I see a bunch of the same boss entities in encounter combobox, counting only one incoming hit from the boss (to one or more targets in party).

**Comment by neowutran** [comment]
Not able to reproduce that, you tried on a specific boss?

**Comment by Gl0** [comment]
Kelivan in kdnm

**Comment by Gl0** [comment]
Still seeing this issue. Today's  IM group in kdnm has such low dps, that at the end of the fight I've seen more than 20 kelivan entities in the list, and no one of them was with damage dealt (usualy it was at the top of the list)

**Comment by neowutran** [comment]
Verified, working on it

**Comment by neowutran** [comment]
In the current version, a boss entity is ID + Name
I will look what happens if I just say, boss entity = name only

**Comment by Gl0** [comment]
It would be the same as it was before [fix](https://github.com/neowutran/ShinraMeter/commit/274926f7c7faa01dd2b6b618bb417c3af5ee1ca3) - if there are multiply boss entities with the same name all received damage would be count to the first (from the bottom) one.

**Comment by Gl0** [comment]
May be it is simpler to change this string to something like
`var t in EntitiesStats.Where(t => t.Key.Name == entitySource.Name).OrderBy(t=>-t.Value.FirstHit)) `

**Comment by neowutran** [comment]
For some reason, when you fight some boss, many different entity are linked to the boss. No idea why. 
With the current version I just delete encounter when I received damage data about an encounter who already received a "DESPAWN_NPC" packet

**Comment by Gl0** [comment]
These entities seems to be used for aoe attacks that cover the whole battlefield and not linked to boss position on it.

**Comment by neowutran** [comment]
humm ok ^^ but then, I have a problem. How can I count the damage taken from these AOE?
Those AOE are counted as a boss NPC by the dps meter.
Probably need to look for the SpawnNpcServerMessage packet to find some usefull bits.

**Comment by Gl0** [comment]
> I will look what happens if I just say, boss entity = name only
Seems this is a bad idea, when fighting multiple BAMs (or multiple runs to the same dungeon without meter reset) - abnormalities are registered to the first one with this name, and on despawnnpc they applied on actual entityid, causing exception.
Using in some related parts of code entityid and the whole entity, while entities synchronized only by their name may cause very hard to find errors.

**Comment by neowutran** [comment]
hum, yup. I will probably revert back as it was before (id + name).
But we will need to find how to see a difference between AOE and NPC.
If not, we will still have that pb "ve seen more than 20 kelivan entities in the list"

It s maybe something here: 
https://github.com/neowutran/ShinraMeter/blob/master/Tera/Game/Messages/Server/SpawnNpcServerMessage.cs#L11

or here: 
https://github.com/neowutran/ShinraMeter/blob/master/Tera/Game/Messages/Server/SpawnNpcServerMessage.cs#L16

or here:
https://github.com/neowutran/ShinraMeter/blob/master/Tera/Game/Messages/Server/SpawnNpcServerMessage.cs#L20

Don't know, I will try to see that next week

**Comment by Gl0** [comment]
to fix "20 kelivan entities" [one line is enough](https://github.com/neowutran/ShinraMeter/issues/25#issuecomment-184379473).

**Comment by Gl0** [comment]
Seems even with this fix, main entity of kelivan sometimes disappear at the end of the fight like after boss reset. May be when dot continue it's damage after mob's death. Today after fight i saw one entity with 2 ticks of incoming damage, 10k per tick.

**Comment by neowutran** [comment]
That would means the server send us a "SCreatureChangeHp" after the "SDespawnNpc"
weird

**Comment by Gl0** [comment]
Hp is actually changing, so this packet is normal.

**Comment by Gl0** [comment]
> I just delete encounter when I received damage data about an encounter who already received a "DESPAWN_NPC" packet

This causing main boss entity to disappear from encounter if there is active dot on someone after boss death.

**Comment by Gl0** [comment]
When dot was applied entity was alive. This not only kelivan issue. You can get dot right before boss death in many dungeons.

**Comment by neowutran** [comment]
Ok, you get a dot on you, the boss die, and then you get damage from the dot?

**Comment by Gl0** [comment]
Yes, of course. =)

**Comment by neowutran** [comment]
ok, then removing this block should be enought 
https://github.com/neowutran/ShinraMeter/blob/master/DamageMeter.Core/DamageTracker.cs#L428

**Comment by Gl0** [comment]
If you remove this block - the whole _hasReset seems to be useless, since you shouldn't receive packets with damage done to dead entity.

**Comment by neowutran** [comment]
still have this informations here: 
https://github.com/neowutran/ShinraMeter/blob/master/DamageMeter.Core/DamageTracker.cs#L358
(damage dealt vs damage received)
so that should still work

**Comment by Gl0** [comment]
Thats what I say, it useless, since you shouldn't receive packets with damage dealt to dead entity.

**Comment by Gl0** [comment]
Added debug output to S_SPAWN_NPC & S_DESPAWN_NPC filtered by IsBoss, don;t see any entities like https://github.com/neowutran/ShinraMeter/issues/25#issuecomment-185830901

Found bug, causing these ghost entities:
https://github.com/neowutran/ShinraMeter/blob/5797cb1a692ad60e53f28adcdbf1e4f23dc3e394/DamageMeter.Core/DamageTracker.cs#L294 should be source2.Id
after fixing that you may change
`var t in EntitiesStats.Where(t => t.Key.Name == entitySource.Name).OrderBy(t=>-t.Value.FirstHit))`
to
`var t in EntitiesStats.Where(t => t.Key.Name == entitySource.Name && t.Key.Id==entitySource.Id))`

**Comment by neowutran** [comment]
^_^' thanks you

**Comment by neowutran** [comment]
I think everything is fine now, except the _hasReset, but that should usefull in EKHM/SCHM when you leave the group & retry the boss

**Comment by Gl0** [comment]
That case should not appear in _hasReset, you don't receive despawn packets when teleporting somewhere.
