### ISSUE TITLE
TERA freezes when window not focused and IM succeeds

### ISSUE THREAD

**Issue by Noheadman** [neowutran/ShinraMeter#250]
As mentioned in title, my game freezes when IM succeeds and game window isn't focused (browsing web while waiting for IM to proc). I'm playing in fullscreen(windowed) if it helps anything. Server EU - Killian.

**Comment by Gl0** [comment]
We do nothing that can affect game. That's probably not meter issue, but game bug.

**Comment by Noheadman** [comment]
It doesn't freeze if meter is not running.

**Comment by Gl0** [comment]
Totally freezes or just stop responding for some time?

**Comment by Noheadman** [comment]
Totally freezes. Have to kill it through task manager.

**Comment by Gl0** [comment]
Try to disable text popup for afk event - delete following string from events-common.xml:
```					<balloon title_text="{afk_title}" body_text="{afk_body}" display_time="3000" />
```
and recheck.
