### ISSUE TITLE
[Request] Minimize (Hide) button

### ISSUE THREAD

**Issue by careful7j** [neowutran/ShinraMeter#251]
Current state is the following:
With option "show Shinra always" I can make screenshots with Shinra, but everytime I close the game I also close Shinra and... forget to launch it again when I launch the game. 
If I don't use "show Shinra always" then it doesn't appear on screenshots. It could be good if Shinra had "minimize (hide)" button.

As I see in game - many people keep restarting game since they fogrot to launch Shinra, for that only reason. Please if it is possible make such an option or mayby hook somehow Shinra with game .exe file?

**Comment by Gl0** [comment]
You can use ShinraLauncher to autostart meter with tera.
You can disable "stay topmost" - in that case meter window can be placed behind other windows and is shown in taskbar as regular window.

**Comment by careful7j** [comment]
Yea, Shinra launcher look like a good solution. Thank you, looks like replacing feature for the one I asked for is already implemented.
