### ISSUE TITLE
[Request] Countdown

### ISSUE THREAD

**Issue by tachiras** [neowutran/ShinraMeter#252]
Hi, sorry maybe I am using this section the wrong way, not sure if it works like forum. May I ask if it is possible to make a countdown using hotkeys XML document and editing this part:
```
<copy>
      <ctrl>True</ctrl>
      <shift>False</shift>
      <window>False</window>
      <key>NumPad0</key>
      <string>
        <header></header>
        <content></content>
        <footer></footer>
        <order_by></order_by>
        <order></order>
      </string>
</copy>
```

**Comment by Gl0** [comment]
How countdown relates to encounter stats chat copy?
