### ISSUE TITLE
OMG IT BEEPS ALL THE TIME MAKE IT STOP!!!

### ISSUE THREAD

**Issue by Owyn** [neowutran/ShinraMeter#253]
/title

really, I had to disable dozens of events to make it stop, it's not user-friendly to install & configure

**Comment by Gl0** [comment]
Latest defaults have very few number of events active: afk events, CCB & Nostrum checks, enrage/hurricane/contagion debuff on boss.

**Comment by Owyn** [comment]
As someone mentioned already here - a text-to-speech would be much more friendly to say what is actually wrong instead of beeping

**Comment by Gl0** [comment]
Text to speech have a big bunch of issues with regional settings. User may have only english voice installed, that doesn't support reading of local characters. English words, pronounced by local voice sounds awful and not understandable (especially for users that don't know english debuff names) - so using english notation is bad too. Some languages even don't have local voice. Don't see the way of making universal tts template, that will satisfy everyone.

**Comment by Owyn** [comment]
Well, just making a local config file with all text to read would do the trick I suppose, else english is fine, many programs use english T-T-S like teamspeak or other voice chats

**Comment by Gl0** [comment]
You can do that trick yourself, TTS is supported with latest version.

**Comment by Owyn** [comment]
So... how do I setup TTS myself? looked at wiki - nothing about it there

**Comment by Gl0** [comment]
https://github.com/neowutran/ShinraMeter/wiki/Events#text-to-speech

**Comment by Owyn** [comment]
> text to speech have a big bunch of issues with regional settings. User may have only english voice installed, that doesn't support reading of local characters. 

pretty much every local version of windows comes with according TTS like:
russian windows - with russian TTS
german windows - with german TTS
etc
even if not - users can just change text themselves

> so you can share your TTS defaults for all RU players.
sure
[events-common.xml.txt](https://github.com/neowutran/ShinraMeter/files/628327/events-common.xml.txt)

[events-mystic.xml.txt](https://github.com/neowutran/ShinraMeter/files/628332/events-mystic.xml.txt)
