### ISSUE TITLE
new common event pls: lancer buff

### ISSUE THREAD

**Issue by Owyn** [neowutran/ShinraMeter#255]
I've seen you added hurricane and contagion buffs to mostly everyone, but you missed lancer buff which is at least not less usefull than those, for damagers, for tanks and for healers, so you should probably add it to standart events too.

**Comment by neowutran** [comment]
Adrenaline rush?

**Comment by Owyn** [comment]
> Adrenaline rush?

Yes, must be it, that thing which gives bonus attack speed for party
