### ISSUE TITLE
events: false trigger for party everfull nostrum and crystalbinds

### ISSUE THREAD

**Issue by Owyn** [neowutran/ShinraMeter#258]
It triggers saying that someone from party is missing everyfull nostrum (triggers twice) and someone is missing crystalbind, I checked manually by expanding their hidden lists of buffs - everyboy had everything, and it triggered the same way for all three bosses

**Comment by Gl0** [comment]
Do you see these buffs inside meter detailed stats? Which id they have?

**Comment by Owyn** [comment]
How do I see the ID?

**Comment by Gl0** [comment]
it's shown in tooltip when hovering % uptime

**Comment by Owyn** [comment]
4030 for nostrum
and 4610 for crystalbinds,
maybe there were different IDs for that party, I'll turn events on again and see for sure

also, should It just trigger multiple times for multiple party-members? can't you do a one big trigger for multiple party members missing things?

or better if there was a number of party-members passed so we could use it like:
```
<text_to_speech text="%n people missing crystalbinds" />
```

**Comment by Gl0** [comment]
Need to know what was there when it was false triggered.
Now it triggers when some action is done by party member to ensure that he is fully loaded.

**Comment by Owyn** [comment]
I just went to Kelivan easy, on the start of first boss it beeped (TTS'ed) two times that party nostrum is missing, and one time that party crystalbind is missing, I checked manually that they had everything, same thing happened on 2nd boss fight start, and on the last boss, that's it.

**Comment by Gl0** [comment]
may be they had some cheaper nostrum, or meter haven't detected their bind/nostrum at all

**Comment by Qarinna** [comment]
This has to be fixed. People die all the time in 30 men raid at least for now and the meter can't stop beeping.
This is literally useless. Either disable it for 30 men or remove useless beeps please

**Comment by Gl0** [comment]
in 30-raid you should probably disable party notifications via checkbox.

**Comment by Owyn** [comment]
You'r right, lesser nostrums trigger this, it's fine I guess
