### ISSUE TITLE
low_dps_content does not working

### ISSUE THREAD

**Issue by rkay8496** [neowutran/ShinraMeter#259]
DPS shows not buff/debuff list of healor.

My "hotkey.xml" is almost same with "https://github.com/neowutran/ShinraMeter/wiki#configuring-hotkeys"

**Comment by Gl0** [comment]
show your hotkeys.xml and paste result.

**Comment by rkay8496** [comment]
My "hotkey.xml"
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<hotkeys>
  <topmost>
    <ctrl>False</ctrl>
    <shift>False</shift>
    <window>False</window>
    <alt>False</alt>
    <key>None</key>
  </topmost>
  <paste>
    <ctrl>False</ctrl>
    <shift>False</shift>
    <window>False</window>
    <key>Home</key>
  </paste>
  <reset>
    <ctrl>False</ctrl>
    <shift>False</shift>
    <window>False</window>
    <alt>False</alt>
    <key>Delete</key>
  </reset>
  <reset_current>
    <ctrl>True</ctrl>
    <shift>False</shift>
    <window>False</window>
    <alt>False</alt>
    <key>Delete</key>
  </reset_current>
  <excel_save>
    <ctrl>True</ctrl>
    <shift>False</shift>
    <window>False</window>
    <alt>False</alt>
    <key>Next</key>
  </excel_save>
  <click_throu>
    <ctrl>True</ctrl>
    <shift>False</shift>
    <window>False</window>
    <alt>False</alt>
    <key>PageUp</key>
  </click_throu>
  <copys>
    <copy>
      <ctrl>True</ctrl>
      <shift>False</shift>
      <window>False</window>
      <key>End</key>
      <string>
        <header>Damage Taken @ {encounter} {timer}:\</header>
        <content>[{class}] {name}: Hits: {hits_received} = {damage_received}; Death {deaths} = {death_duration} Aggro {aggro} = {aggro_duration}\</content>
        <low_dps_content>[{class}] {name}: Hits: {hits_received} = {damage_received}; Death {deaths} = {death_duration} Aggro {aggro} = {aggro_duration}\</low_dps_content>
        <low_dps_threshold>4</low_dps_threshold>
        <footer></footer>
        <order_by>hits_received</order_by>
        <order>descending</order>
      </string>
    </copy>
    <copy>
      <ctrl>False</ctrl>
      <shift>True</shift>
      <window>False</window>
      <key>End</key>
      <string>
        <header>Damage Done @ {encounter} {timer} {partyDps} {enrage}:\</header>
        <content>[{class}] {name}: {damage_percentage} ({damage_dealt}) | Crit: {crit_rate} | {global_dps}\</content>
        <low_dps_content>[{class}] {name}: {debuff_list}\</low_dps_content>
        <low_dps_threshold>4</low_dps_threshold>
        <footer></footer>
        <order_by>damage_percentage</order_by>
        <order>descending</order>
      </string>
    </copy>
  </copys>
</hotkeys>

-------------------------------------------


I am logging out. so I have no result.
Result that i saw is like an example is "Section Configuring Hotkeys"

**Comment by rkay8496** [comment]
My "hotkey.xml"
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<hotkeys>
  <topmost>
    <ctrl>False</ctrl>
    <shift>False</shift>
    <window>False</window>
    <alt>False</alt>
    <key>None</key>
  </topmost>
  <paste>
    <ctrl>False</ctrl>
    <shift>False</shift>
    <window>False</window>
    <key>Home</key>
  </paste>
  <reset>
    <ctrl>False</ctrl>
    <shift>False</shift>
    <window>False</window>
    <alt>False</alt>
    <key>Delete</key>
  </reset>
  <reset_current>
    <ctrl>True</ctrl>
    <shift>False</shift>
    <window>False</window>
    <alt>False</alt>
    <key>Delete</key>
  </reset_current>
  <excel_save>
    <ctrl>True</ctrl>
    <shift>False</shift>
    <window>False</window>
    <alt>False</alt>
    <key>Next</key>
  </excel_save>
  <click_throu>
    <ctrl>True</ctrl>
    <shift>False</shift>
    <window>False</window>
    <alt>False</alt>
    <key>PageUp</key>
  </click_throu>
  <copys>
    <copy>
      <ctrl>True</ctrl>
      <shift>False</shift>
      <window>False</window>
      <key>End</key>
      <string>
        <header>Damage Taken @ {encounter} {timer}:\</header>
        <content>[{class}] {name}: Hits: {hits_received} = {damage_received}; Death {deaths} = {death_duration} Aggro {aggro} = {aggro_duration}\</content>
        <low_dps_content>[{class}] {name}: Hits: {hits_received} = {damage_received}; Death {deaths} = {death_duration} Aggro {aggro} = {aggro_duration}\</low_dps_content>
        <low_dps_threshold>4</low_dps_threshold>
        <footer></footer>
        <order_by>hits_received</order_by>
        <order>descending</order>
      </string>
    </copy>
    <copy>
      <ctrl>False</ctrl>
      <shift>True</shift>
      <window>False</window>
      <key>End</key>
      <string>
        <header>Damage Done @ {encounter} {timer} {partyDps} {enrage}:\</header>
        <content>[{class}] {name}: {damage_percentage} ({damage_dealt}) | Crit: {crit_rate} | {global_dps}\</content>
        <low_dps_content>[{class}] {name}: {debuff_list}\</low_dps_content>
        <low_dps_threshold>4</low_dps_threshold>
        <footer></footer>
        <order_by>damage_percentage</order_by>
        <order>descending</order>
      </string>
    </copy>
  </copys>
</hotkeys>

-------------------------------------------


I am logging out. so I have no result.
Result that i saw is like an example is "Section Configuring Hotkeys"

**Comment by rkay8496** [comment]
[hotkeys.txt](https://github.com/neowutran/ShinraMeter/files/624313/hotkeys.txt)

**Comment by rkay8496** [comment]
i'm logging out, so i have no result.
but the result is like an example in Section "Configuring Hotkeys"
