### ISSUE TITLE
Tera Focus

### ISSUE THREAD

**Issue by Casanova** [neowutran/ShinraMeter#26]
Hi,

Thanks a lot for this amazing work, you DPS Meter is the best by far.
I use Two screens, and when I click on ShinraMeter while I'm on Tera, Tera loses focus and gets minimized.
I've seen on other DPS Meters that it's possible to click on it and see skills details without losing focus. For example you can still roll on loot using PageUp/PageDown.
Can it be implemented on ShinraMeter?
Please let me know if you need more details.

Kind regards,

Casanova

**Comment by neowutran** [comment]
Hi ^^ and thanks
"I click on ShinraMeter while I'm on Tera, Tera loses focus" => ok
"and gets minimized" => hu ? You try to use it in fullscreen mode? 

"click on it and see skills details without losing focus" => I will try but don't really know how to do that

**Comment by Casanova** [comment]
Hi,

Thank you for your answer.
I play Tera in full screen mode in order to have less FPS issues. I can see ShinraMeter at the same time, on the other screen.
The actions that require clicking on the DPS meter are checking skills details or endurance debuffs.

If it's to any help, [this](https://github.com/lunyx/CasualMeter) DPS meter has the requested behavior: Start the DPS meter, record some DPS, then click on it. You'll see that you can still see Tera and open its menus with keyboard shortcuts.
 
Thanks again from my whole guild, we really are fond of your work!

**Comment by Gl0** [comment]
the part of casualmeter, that make it windows click-through is in closed-source dll. 
Google give 2 technics of doing it.
Also this behavior seems to be linked to absence of the meter windows in taskbar and problems with making it forefront when it loose topmost status for some reason.

**Comment by neowutran** [comment]
Thanks for the data, I will try to see/fix that after the week end
( topmost cannot be trusted, I already have issues with that in the current version of the shinra meter )

**Comment by Gl0** [comment]
in casualmeter it is done via http://stackoverflow.com/a/12628353

**Comment by neowutran** [comment]
ok, thanks, testing it

**Comment by neowutran** [comment]
good, and thanks. 
Will be added for the next release

**Comment by Casanova** [comment]
\o/ Thanks !

**Comment by neowutran** [comment]
fixed, (V0.67)

**Comment by Gl0** [comment]
Seems there is too much topmost switching, It's hard to select something in encounter combobox. Until the focus is switched to main dpsmeter window via taskbar, this window is refreshed every second and  goes behind dropped down list.
