### ISSUE TITLE
shinrameter.exe cpu usage very high 

### ISSUE THREAD

**Issue by kterameter** [neowutran/ShinraMeter#260]
if Utorrent download speed is over 10M/s, shinrameter.exe cpu usage rate is over 20 ~ 35%.
download speed 2M/s , shinrameter.exe cpu usage rate 2.5%
4Ms , 6% 
It gets higher and higher.

shinrameter ver 1.64
windows 10 x64  1607 (14393.447)

**Comment by Gl0** [comment]
That's expected if you are using raw sockets. This method require all traffic parsing in user mode. Try latest npcap.

**Comment by kterameter** [comment]
Problem solved thank you !!

**Comment by hsluoyz** [comment]
Please download the latest Npcap here: https://github.com/nmap/npcap/releases

**Comment by Gl0** [comment]
btw, one of our users was forced to use raw sockets cause after installing npcap he got BSOD on each PPPoE connection attempt. Don't think he would collect any debug logs, but seems this happened due to some windows services disabled (at least not working firewall, may be some other, haven't look deeply into it, but seems system was installed not original from microsoft ISO, but from some tweaked windows 7 ISO "for gamers").

**Comment by hsluoyz** [comment]
> btw, one of our users was forced to use raw sockets cause after installing npcap he got BSOD on each PPPoE connection attempt. Don't think he would collect any debug logs

If he can provide the BSoD dump file and the DiagReport, Theyt are very easy to retrieve. it will be very helpful for me to troubleshoot the cause. Why can't he collect them?

> but seems this happened due to some windows services disabled (at least not working firewall, may be some other, haven't look deeply into it

My developer machine just has the firewall disabled all the time. And I didn't have this issue. So I'm afraid it's not the cause.

> but seems system was installed not original from microsoft ISO, but from some tweaked windows 7 ISO "for gamers").

A reproduce step would also be helpful. Like providing the ISO and the connection software.

**Comment by Gl0** [comment]
I've just connected there once with teamviewer to help with meter configuration, and don't have any contact for this user. There was no connection software, just built-in windows PPPoE over onboard ethernet card.

**Comment by Gl0** [comment]
Another one user with the same problem, asked him for logs.

**Comment by hsluoyz** [comment]
OK.
