### ISSUE TITLE
request: tray icon context menu

### ISSUE THREAD

**Issue by Owyn** [neowutran/ShinraMeter#264]
a context menu via right mouse button on tray icon with reset\exit choices would be much more convenient instead of bringing up the whole programs UI (the same way as clicking the left mouse button on the tray icon does)

**Comment by snwFlake** [comment]
+1

**Comment by Owyn** [comment]
btw, adding "view chat" button there and in actions would be nice cuz if you have no DPS data and that window hidden - you can't click the button "view chat" which is for some reason in that DPS window...

**Comment by Gl0** [comment]
With chatbox button - problem is not underlying window, but transparency of button in places where it have no text. So just click more accurately on icon or text.

**Comment by Owyn** [comment]
>  So just click more accurately on icon or text.

There is nowhere to click.

I checked "hide dps window when there is no data" - so no button at all after I reset DPS
