### ISSUE TITLE
shinra w npcap = game crashes every 15 minutes in fight

### ISSUE THREAD

**Issue by Owyn** [neowutran/ShinraMeter#266]
without npcap - no crashes

**Comment by Gl0** [comment]
Seems npcap have some issues with ppp connectons. Probably you should send logs to @hsluoyz (see https://github.com/neowutran/ShinraMeter/issues/237#issuecomment-265116376 )

**Comment by Owyn** [comment]
sent him that log via email, hope it'd help

**Comment by hsluoyz** [comment]
Well, from your log, it seems OK, except that you have installed Npcap into S:\. I can't tell what's wrong there with current information.

Does the game or meter have any crash logs? Why is it related to PPP connections? Do you use a VPN too? But I didn't see another network filter in your report.

I don't play the Teranext game.. So I didn't know how to reproduce this issue. Can you describe me about the steps?

**Comment by Gl0** [comment]
Meter have crash logs, but it wasn't crashed, cause we decode much less packets than game itself.
I think that it's related to PPP because AFAIK @Owyn is using PPPoE or l2tp and there were another 2 users with PPPoE that have BSOD even on PPPoE connection attempt (not sure, whether any of them sent you dumps).

**Comment by Owyn** [comment]
@hsluoyz 
S: is the system drive, so I couldn't install it anywhere else...

I use L2TP connection to internet, ISP cable provides just access to local network unless you activate the official VPN connection to have internet

> I don't play the Teranext game.. So I didn't know how to reproduce this issue. Can you describe me about the steps?

1. Play game for 15 minutes
2. Have game crash

That's it, I just started the meter with newly installed and turned on npcap thinking that it'd correctly gather data about 3rd phase of 30man raid dungeon, it worked for few times, few other times it bugged - counted just 1 mage dealing 57m\s in 0 sec boss fight from all 30 ppl, then I think it counted just 3 minutes out of 8 min fight, then it crashed the game somehow, then I just relaunched the game, played for 15 minutes and had my game crashed again, then I just relaunched the game, played for 15 minutes and had my game crashed again, I just relaunched the game, played for 15 minutes and had my game crashed again... then I turned off the meter and BOOM - no more crashes

with meter I have pretty much two options now:
1. use rawsockets without npcacp - and make meter stop working at some point for unknown reason https://github.com/neowutran/ShinraMeter/issues/261
OR
2. use npcap - and make GAME stop working at some point for unknown reason... (well meter stops working too cuz there is no game active and nowhere to pick data from)

**Comment by Gl0** [comment]
>That's it, I just started the meter with newly installed and turned on npcap thinking that it'd correctly gather data about 3rd phase of 30man raid dungeon, it worked for few times, few other times it bugged - counted just 1 mage dealing 57m\s in 0 sec boss fight from all 30 ppl

Anything in error.log after that?

**Comment by Owyn** [comment]
> Anything in error.log after that?

Nope, that error.log is empty as always, pretty useless logfile...

**Comment by Gl0** [comment]
btw, have you looked at this mage's skill details window when it happened?

**Comment by Gl0** [comment]
The only reason I see for both issues - is packet corruption in memory. When it happens in npcap's code before it passed to the game - game crashes, when it happens in meter callback (either in npcap mode or raw sockets) - meter stops working or show strange things.
Have you checked your memory/cpu for stability? Isn't it overclocked?

**Comment by Owyn** [comment]
> btw, have you looked at this mage's skill details window when it happened?

No, sorry.

> Have you checked your memory/cpu for stability? Isn't it overclocked?

It's not overclocked and works perfectly in everything else
