### ISSUE TITLE
format for chat problem

### ISSUE THREAD

**Issue by Owyn** [neowutran/ShinraMeter#267]
![tera_screenshot_20161208_234208](https://cloud.githubusercontent.com/assets/1309656/21060315/c0d1cefa-be57-11e6-88da-7ae8e944e2b4.png)
![tera_screenshot_20161208_234119](https://cloud.githubusercontent.com/assets/1309656/21060314/c0ce4640-be57-11e6-9ed1-ecfc4369208e.png)

```
<header>Damage Done @ {encounter} {timer} {partyDps} {enrage}:\</header>
<content>{class} - {name}: {global_dps} ({damage_percentage}) {debuff_list}\</content>
        <low_dps_content>{class} - {name}: {global_dps} ({damage_percentage}) {debuff_list}\</low_dps_content>
```

These are same results from my format and old default format

Could you fix it so parameters in  {} would all be under each other like in old default version without debuff_list?

(if that is not possible - Can I use {debuff_list} in the `<header>` to be displayed once and not individually? - would that make chat formatting work OK again?)

**Comment by Gl0** [comment]
Are you using default chat font?

**Comment by Owyn** [comment]
Verdana, but look at 1st screen - it formats perfectly with old default formatting

**Comment by Gl0** [comment]
![tera_screenshot_20161210_002841](https://cloud.githubusercontent.com/assets/15658733/21065161/d34e3470-be6f-11e6-8b94-4934d09c7e8e.png)
Fresh screenshot with default settings and font

**Comment by Owyn** [comment]
But can you fix it for not default settings?

**Comment by Gl0** [comment]
With your settings looks fine too.
Don't see 
![untitled](https://cloud.githubusercontent.com/assets/15658733/21065983/2bded460-be74-11e6-9fd6-73d809d75ecd.png)
this issue (look at first space).
And can't see, how it can appear with current code.

**Comment by Gl0** [comment]
Found out, where's the case - your chat is too stretched, and when some strings wraps to the next line and some don't - game reformat string to be justified.

**Comment by Gl0** [comment]
Ok for adding {debuff_list} to header.

**Comment by Owyn** [comment]
> Ok for adding {debuff_list} to header.

thx, btw, I just noticed in config file there is a `<footer>` also.. can I add it there?

**Comment by Gl0** [comment]
only in next release =)

**Comment by Owyn** [comment]
> In header {debuff_list} include enrage, so you can replace {enrage} with {debuff_list}.

why does it include enrage btw? In footer it would be bad to just duplicate enrage from header, and in header users could just use {enrage} {debuff_list} instead of just {debuff_list} to get the same result, why not?

**Comment by Gl0** [comment]
Cause it's impossible to make template, where {enrage} will be separated visually only if {debuff_list} is not empty. Enrage is the same debuff as others, showing it the same way looks reasonable.

**Comment by Owyn** [comment]
> Enrage is the same debuff as others

That's weird, I thought it's just a state of boss, not a buff or debuff

But even so - can you just make an exception to cut it out of debuff_list template manually?

**Comment by Gl0** [comment]
We store it as debuff. Exception can be done, of cause (it's already cut in personal {debuff_list})
Are you sure that it wouldn't be good in current way if we implement short names for debuffs? + (may be) sort it so that enrage goes first?

**Comment by Owyn** [comment]
It's better in my opinion to display enrage time separately after boss total fight time,

I'm planning on using {debuff_list} in the `<footer>` so it would be a duplicate

but anyway, even if it would be used in `<header>` by anyone - `{enrage} {debuff_list}` would display the pretty same result, no? - but it would give more flexibility, which is nice

**Comment by Gl0** [comment]
{enrage} is only %, without name and separator = not the same result

**Comment by Owyn** [comment]
> {enrage} is only %, without name and separator = not the same result

Well, if in debuff_list it is something like "enrage %n" user can always add text "enrage" before {enrage} to get the 100% same result

**Comment by Gl0** [comment]
but he can't set separator =)

**Comment by Owyn** [comment]
> but he can't set separator

he also can't do that when adding debuff_list per player, or anywhere else... it's not necessary that everyone would want debuff_list to be exactly after enrage timer

writing a separator before debuff_list would be a good alternative (if there were other {params} before it as a solution

**Comment by Owyn** [comment]
btw, on the topick, 
![tera_screenshot_20161222_185345](https://cloud.githubusercontent.com/assets/1309656/21469094/14086b08-ca4a-11e6-8b2d-eed89e94acfb.png)

the lining up in the end of the screen seems pretty weird, can you fix (remove) it?
I mean those spaces after `%` sign `(0% )` instead of `(0%)`

**Comment by Gl0** [comment]
I remove only whitespaces at the end of the string. I can't determine, what user wanted to get, a stripped space in `(0% )` or some sort of table like `|0% |`.
There are some problems with stripping spaces only from last placeholder, since it can be different for normal and low_dps templates.
Or there can be empty or not {debuff_list} at the end.
So I suggest just change `(value)` to simple `|value` , that would be looking quite good

**Comment by Owyn** [comment]
Well, I had to remove `[]` brackets from class list because this algorithm placed spaces into those, eg `[Archer    ]`,  why not just make it `[Archer]    ` - place spaces after brackets only? You probably could whitelist brackets so no spaces would be put inside them

**Comment by Gl0** [comment]
Because all out of {} is plain string, that can be anything. If I force remove all spaces between brackets - it will ruin formatting of templates where brackets are surrounding not last placeholder.

**Comment by Gl0** [comment]
I'll move all spaces that are before `)` or `]` to be after them. It can brake some wide templates with spaces between brackets, but seems it wouldn't be harmful, since such templates are very uncommon.
