### ISSUE TITLE
 I can not use ShinraMeter with VPN (NoPing)

### ISSUE THREAD

**Issue by safc1** [neowutran/ShinraMeter#268]
Hello, I can not use ShinraMeter with NoPing, it appears "No Server", could anyone help me? Program: https://nptunnel.com/ is VPN Tunnel.

**Comment by Gl0** [comment]
Have you read th following and tried both ways?
https://github.com/neowutran/ShinraMeter/wiki#vpnproxy

**Comment by safc1** [comment]
Yes, it does not work, Because it leaves as localhost and keeps changing the exit door.

**Comment by Gl0** [comment]
localhost traffic is intercepted by meter either via npcap loopback adapter or via raw sockets mode. no need to know exit door.
