### ISSUE TITLE
[Request] Cut chat debuff information output

### ISSUE THREAD

**Issue by careful7j** [neowutran/ShinraMeter#270]
Please add a file where we can override Debuff names and output format of {debuff_list}. It's too much of text (especially on Russian localization) like:

Ослабляющее тройное возмездие VI 66.5% (00:40) | Милосердие кузнеца 33.3% (00:20) | e.t.c.

1. Some skill names are Loooooooong ('Ослабляющее тройное возмездие' - just OMG) can I somewhere in Shinra modify this skill names?
2. Time (00:40) is also consuming space in chat (I Believe percentage (66.5%) could be just enough)
3. Skilll level in chat "VI" <- something I defenetely don't need.

Perfect output would look like:
Возмездие 66.5% | Милосердие 33.3% | e.t.c.

Please save my chat from garbage :D Thank you for the job already done, Shinra the best :)

**Comment by Owyn** [comment]
+1

**Comment by Gl0** [comment]
Don't see the way to create short name automatically, but I can add short name to meter, if someone send me override file (something like hotdot-short-RU.tsv) in format

```<id>	<short name>```

Not sure, where to add it, to DB (so that it will autoupdate with meter) or to user config, so that user changes to this file will be persistent.

**Comment by Owyn** [comment]
Alternatively - could you do a priority for displaying debuffs? like "Милосердие кузнеца" and Velika's Mark of Archer is pretty worthless to know, but on the other hand debuffs of healers and then tanks are very important to know:
see, useless stuff now comes first and important one gets cut
![tera_screenshot_20161213_213422_proc](https://cloud.githubusercontent.com/assets/1309656/21154834/eb1f2e2e-c180-11e6-9ef1-825c8499ff94.jpg)

**Comment by Gl0** [comment]
Again, don't see the way to prioritize it automatically. Now it's shown in order of appearing on boss.
override file is probably the best way, cause there is not so many debuffs available on boss and it can be written manually.

**Comment by careful7j** [comment]
And what about modifying the output schema - "debuff name" + "debuff level" + "percentage" + "time" - is there any xml file where can I find it and fix the way I Like?

**Comment by Gl0** [comment]
I'll strip time in next release, "debuff name"+"debuff level" is actually debuff name, will be substituted with short name, if we implement overrides

**Comment by Owyn** [comment]
> I'll strip time in next release

but time is needed T_T

not only percents, by time we can see how much procs there was like if it's 0:20 - hurricane proced just once, both percentage and time are needed to be shown

**Comment by Gl0** [comment]
The only way I see - add something like {debuff_list_p} for only % output

**Comment by Owyn** [comment]
> The only way I see - add something like {debuff_list_p} for only % output

How would people know to what debuff the % belongs then?...

**Comment by Gl0** [comment]
I've mean without time version

**Comment by Owyn** [comment]
I wonder if people would use that {debuff_list_p} ...

**Comment by Gl0** [comment]
You see one as issue starter.=)

**Comment by Gl0** [comment]
Still need someone to supply desired short names for debuffs, that will be understandable for the majority of meter users in the region.

**Comment by Owyn** [comment]
@Gl0
Can you dump a file with full names so people would just edit those to desired? That'd be the easiest way

**Comment by Gl0** [comment]
All full names and id's are in ./resources/data/hotdot/[hotdot-RU.tsv](https://github.com/neowutran/TeraDpsMeterData/blob/master/hotdot/hotdot-RU.tsv)
I don't know which debuffs that can be placed on boss, you should know it better, cause you see them every day in dungeons.

**Comment by Owyn** [comment]
So you do have skill descriptions.. but when I hover buffs in shinra window they don't show any description up...

**Comment by Gl0** [comment]
Description is shown when hovering over debuff name.

**Comment by careful7j** [comment]
I'll try to collect long debuff names today and publish it here in the end of the day.

**Comment by Owyn** [comment]
> are there any more debuffs except Hurricane that are important to have time?

can't recall any

**Comment by Owyn** [comment]
@Gl0 

> Again, don't see the way to prioritize it automatically. Now it's shown in order of appearing on boss.

Some sort of sorting would be nice:

to always have priest debuffs come first, then mystic, then tank etc, 

else people would be always confused searching for debuff names in unknown places when trying to know the uptime, - it's like if DPS was always shown in different place every fight (or for every player lol) (at the start, or in the middle, or at the end)

**Comment by Gl0** [comment]
I can sort it by player class, but ingame order of classes is far from what you want. Also can sort it by uptime % (same as on moongourd)

**Comment by Owyn** [comment]
Well, sorting by uptime is better than how it is currently, so yes please.

**Comment by careful7j** [comment]
Yesterday collected this (after -> suggested short version):
Ослабляющий град проклятий  -> Град проклятий
Ослабляющее тройное возмездие -> Тройное
Броня: ураган -> Ураган
Милосердие кузнеца -> ВМ8
Прорезающий выпад -> Прорезающий
Серия взрывных ударов -> Серия
Do you need it's Ids in File or names are enough?

**Comment by Owyn** [comment]
Ослабляющий град проклятий -> Град
Ослабляющее тройное возмездие -> Возмездие
Прорезающий выпад -> Выпад

better this way :-)

**Comment by careful7j** [comment]
Ослабляющий град проклятий -> Град
Ослабляющее тройное возмездие -> Тройное
Броня: ураган -> Ураган
Милосердие кузнеца -> ВМ8
Прорезающий выпад -> Выпад
Серия взрывных ударов -> Серия
Клеймо велики -> Клеймо
Карающий удар -> Карающий
Okay, updated

**Comment by Owyn** [comment]
> Ослабляющее тройное возмездие -> Тройное

Ослабляющее тройное возмездие -> Возмездие

> Милосердие кузнеца -> ВМ8

Милосердие кузнеца -> Милосердие 

(not much longer)

**Comment by careful7j** [comment]
> Возмездие <- may look confusing, but if you don't think so - I don't care. Isn't 'ВМ8' shorter? However don't care again.

**Comment by Owyn** [comment]
> May look confusing

It's pretty unique word related to priest, no?

> Тройное

Much more confusing in my opinion, could mean anything by "triple"

Thank you for gathering short names btw.

**Comment by careful7j** [comment]
Ослабляющий град проклятий -> Град
Ослабляющее тройное возмездие -> Возмездие
Броня: ураган -> Ураган
Милосердие кузнеца -> ВМ8
Прорезающий выпад -> Выпад
Серия взрывных ударов -> Серия
Клеймо велики -> Клеймо
Карающий удар -> Карающий

Finally :)
