### ISSUE TITLE
[question] main window relocatable?

### ISSUE THREAD

**Issue by LeviathanX** [neowutran/ShinraMeter#274]
Hi,

I just grabbed the latest release from the server and it works as intended; good tool. 
However, since you don't do in-game overlay, is there any way to relocate the window position by mouse or something?
Dunno, but the window is not dragable (stays fixed top left corner on the main screen), and the wiki entry (?) about a window location attribute in the settings xml leaves me puzzled. That is, because the mentioned files are just completely empty (so  I am left with file structure unknown to me). 
The goal is to move the window to one of my other screens so that I can see the DPS while playing Tera on the main screen... Curently I ALT+TAB to go to the desktop to see the stats..  That however might cause crashes at random points... (I don't want to paste the stats in the chat; at some point I'd like to see them live)

So, is it possible to relocate the window in any way (how so?) or would you accept a feature request to make it moveable with the mouse?

Thanks!

Kind regards,

**Comment by Gl0** [comment]
It's dragable, but not by all UI elements. Try dragging by any numbers.

**Comment by LeviathanX** [comment]
Thanks for your kind reply.
But funny, I could swear I clicked everywhere... Dragging on the left most bar icon element and on the damage number indeed works...  (Though, the site export seems pops back to the main screen.. )

Feeling a bit stupid now -.-
