### ISSUE TITLE
[POPUP NOTIFICATION] Phase out NotifyIcon - Notifications appear on rightmost monitor instead of same screen.

### ISSUE THREAD

**Issue by Glyd** [neowutran/ShinraMeter#275]
Tested with dual monitors, can't speak for more. If I have TERA on the left monitor, the popups (enrage, contagion etc) will appear on my second monitor instead of the same. Makes the feature pretty pointless if you use two monitors, would really appreciate it being fixed :)

**Comment by Gl0** [comment]
popups appear at tray icon position, since they are the part of it.
Probably we'll made separate window for this later.

**Comment by piotrhalaczkiewicz** [comment]
I second this request. The reason I have my tray icons on a different monitor than the game is so that I can see it at all times (for IMs etc).
Would be also great to be able to reposition notifications.

OS: Win7

**Comment by neowutran** [comment]
#335 #283 #328

**Comment by neowutran** [comment]
a fix will be released in 1.97

**Comment by neowutran** [comment]
1.97 released, should be fixed
