### ISSUE TITLE
Reset Window Position?

### ISSUE THREAD

**Issue by hailshy** [neowutran/ShinraMeter#276]
This is less of an error and more of an issue with me being a total idiot.
I somehow managed to get the meter dragged all the way to the bottom of my screen and can't see anything but the very top of it (can choose bosses/total and see the "X" in the top right corner). Because of this, I can't move it, see any numbers, or click on any information. Is there any way to reset the position of the window? When I close and restart it, it just opens in the last location, which is usually great, but right now it means I effectively haven't been able to use Shinra properly for a day or two.

This is what I have:

![screenshot 341](https://cloud.githubusercontent.com/assets/24639300/21296065/5c5037f2-c517-11e6-9edd-63cef53a77cc.png)

Again this was just me being dumb and not thinking and there's probably a way to easily fix it, but... I'm stuck.

**Comment by Gl0** [comment]
Edit location in window.xml

**Comment by hailshy** [comment]
Ah, thank you! Sorry about that.
