### ISSUE TITLE
request: debuff uptime - stacks

### ISSUE THREAD

**Issue by Owyn** [neowutran/ShinraMeter#277]
There are newbly lancers who only debuff boss once and keep at most 1 or 2 stacks of their maximum 3 stacks of debuff,

could you perhaps only count debuff uptime when it's fully stacked? else in debuff_list these newbly players are counted as best players by debuffing means (when it's not true)

**Comment by Gl0** [comment]
We can't determine max available stack value.
The only thing I can suggest is to show uptime of max stack used by player + number of stacks if it's higher then 1. Something like `Debiate(2) 20% (00:20)`

**Comment by Owyn** [comment]
> We can't determine max available stack value.

We can pretty much hardcode those cuz we know it already, no need to determine it.

**Comment by Gl0** [comment]
I've mean show only max stacks uptime, with info about how much it was

**Comment by Owyn** [comment]
> I've mean show only max stacks uptime, with info about how much it was

yea, that's what I'm asking in this ticket :-) 
(but without writing number of stacks)

**Comment by Gl0** [comment]
max = max used, not max available, so needed to list it.

**Comment by Owyn** [comment]
well, no need to show or count their debuff if they didn't reach max available :-)

**Comment by Gl0** [comment]
we count it anyway =)
