### ISSUE TITLE
bug: incorrect data in GUI

### ISSUE THREAD

**Issue by Owyn** [neowutran/ShinraMeter#278]
![default](https://cloud.githubusercontent.com/assets/1309656/21432512/feefdd10-c87c-11e6-9307-dde0d7d530ae.png)

If I switch to another boss data and back to this one - fight time and total dps are update to actual right data

**Comment by Gl0** [comment]
Hm... very strange, don't see the way, how window's header can receive bad fight time while player containers use correct one for counting global dps.

**Comment by Owyn** [comment]
I think it's just not being updated properly, it's not "bad data", it was actual data at some point

**Comment by Gl0** [comment]
Total damage done in header is more then in chat / player containers. And even more than boss max HP.

**Comment by Owyn** [comment]
Or that problematic header can turn invisible ...
![46 _proc](https://cloud.githubusercontent.com/assets/1309656/21531991/2a56c024-cd5d-11e6-8268-946c1b68c2f3.jpg)
![47 _proc](https://cloud.githubusercontent.com/assets/1309656/21531989/2a5683ca-cd5d-11e6-8731-cb80b008d4bd.jpg)
![48 _proc](https://cloud.githubusercontent.com/assets/1309656/21531990/2a56a2ec-cd5d-11e6-8b40-c17905987701.jpg)
