### ISSUE TITLE
UI not being redrawn when game is in fullscreen mode

### ISSUE THREAD

**Issue by Owyn** [neowutran/ShinraMeter#279]
so you can't show it while streaming :-(

Please take a look at possible fixes: https://www.google.ru/search?num=20&safe=off&q=WPF+window+keep+refreshing&oq=WPF+window+keep+refreshing

like InvalidateVisual method or OnRender method or  .Refresh() method

**Comment by Gl0** [comment]
Problem is not with invalidate or onrender. Problem is hardware acceleration. When you switch game to fullscreen mode meter loose rendering device and stop updating UI. Workaround - use software rendering.

**Comment by Owyn** [comment]
omg, if this gonna work - thank you so much <3

**Comment by Gl0** [comment]
At least it working in my setup.
