### ISSUE TITLE
ShinraMeter won't start working

### ISSUE THREAD

**Issue by dovah4056** [neowutran/ShinraMeter#28]
ShinraMeter won't start working at TWTERA
Due to the latest update the meter won't work
(Forsaken Island Hard mode/Dreadspire V2/Revamped Island of  #Dawn)

**Comment by neowutran** [comment]
I won't do it myself as I don't have the TW version on my computer

Instructions here: https://github.com/neowutran/TeraDpsMeterData

Additionnal information here: 
https://github.com/neowutran/ShinraMeter/issues/19

Someone need to send me the new opcode & the new database

**Comment by Dswimxp** [comment]
TW version Added new battlefield.
But I don't know how to extract.
How to run TeraDataExtractor to get the database?
The Extreme Injector v3, I Don't know how to inject.
Add the OpcodeDLL_3009.dll?
Injected.
Finished.
Injection has completed successfully!
But Tera then shut down.
How to get new opcode?
Do you have a step tutorial? XD
Thank you for your answer.

**Comment by neowutran** [comment]
follow that, step by step: 
https://github.com/GoneUp/Tera_PacketViewer/tree/master/Opcode%20DLL

You can't just inject the OpcodeDLL_3009.dll, you need to build your own DLL with the new TW data, then inject it 

And for the database, before extracting it, you need to decipher the database first.
Step by step instruction: https://github.com/neowutran/TeraDpsMeterData/blob/master/copypaste-tuto/Gothos-databasekey.txt
Or automated tool to to it:
https://github.com/gothos-folly/TeraDataTools

I need the opcode + decrypted database

**Comment by Dswimxp** [comment]
Do I need more tools?
I can only be running Windows basic executable file.
I've downloaded the automation tool.
Where to put it?

**Comment by neowutran** [comment]
To use the automated tool to get the database, you need to compile it and run it with Visual Studio

**Comment by Dswimxp** [comment]
Studio visual 2013 can run it?
Import Tera.suo?
I must install Studio visual now
Thank you ^^

**Comment by dovah4056** [comment]
I had found the adress for the opencodedll
but the problem is, I might need to bypass nprotect or I can't inject my dll into TERA

**Comment by neowutran** [comment]
Ok, have fun ^_^

**Comment by dovah4056** [comment]
nah,I even tried JTERA(which is same version as TW server)
cant by pass that nprotect and xigncode3
the only thing we can do is wait for other server update to get opcode

**Comment by neowutran** [comment]
hum ^^ anyone can create a TW account? no need to use a cellphone, social security number or another bullshit?

**Comment by dovah4056** [comment]
yeah, TW account just need an email

**Comment by neowutran** [comment]
ok thanks ^^ I will try to find a way to get opcode + database then

**Comment by neowutran** [comment]
opcode + database available
https://github.com/neowutran/TeraDpsMeterData/commit/b7bdb54368df475f5dc4ce7a6d3dc957b81d5a2b

I will make a new official release today or tomorow
But you just have to copy the new opcode & database file in the current release of shinra meter, and everything will work well ^^

**Comment by MikeWGS** [comment]
hello,  can u show me where to get the latest version(TW Tera)? thank u for the sharing.

**Comment by neowutran** [comment]
new release (0.62). Work with TW

**Comment by MikeWGS** [comment]
when i open 0.62, no UI show up.  should i copy new opcode and database?

**Comment by neowutran** [comment]
Fully invisible (only a system tray to check if the dps meter is able to connect to the server). Go dps something and the UI will show up

**Comment by MikeWGS** [comment]
the dps meter shows : no server...

**Comment by neowutran** [comment]
Then you probably have some network issues. 

You can check here: https://github.com/neowutran/ShinraMeter/wiki#network

(and of course, you must run the dps meter before launching the game)

If even with that, that doesn't work, tell me what kind of network device you use 
(ethernet, wifi, 3g, usb or other)

**Comment by MikeWGS** [comment]
Before this latest version of TW Tera, DPS meter 0.57 works well . 
maybe i can rule out the possibilities of network issues.
i use ethernet, btw.

**Comment by neowutran** [comment]
window.xml to switch

<winpcap>false</winpcap> or <winpcap>True</winpcap>

That the issues. (=> the windows firewall is blocking the shinra meter when you are not using winpcap. I m writing a tuto for that)

**Comment by neowutran** [comment]
(working now? or you still have some issues? )

**Comment by MikeWGS** [comment]
actually....i dont know how to >>>window.xml to switch

<winpcap>false</winpcap> => <winpcap>True</winpcap>

**Comment by neowutran** [comment]
Write
`<?xml version="1.0" encoding="utf-8"?>
<window>
  <location>
    <x>0</x>
    <y>0</y>
  </location>
  <language>TW</language>
  <opacity>
    <mainWindow>50</mainWindow>
    <skillWindow>70</skillWindow>
  </opacity>
  <autoupdate>true</autoupdate>
  <remember_position>true</remember_position>
  <winpcap>true</winpcap>
</window>`

In /resources/config/window.xml

**Comment by MikeWGS** [comment]
it is empty in  /resources/config/

**Comment by neowutran** [comment]
then create the file

**Comment by neowutran** [comment]
that won't be a problem

**Comment by MikeWGS** [comment]
window.xml  is created, but it's not working.
is there another one called "hotkeys" ?
cause i can't find it in here as well.

**Comment by MikeWGS** [comment]
the same problems , NO UI shows up, No server.

**Comment by neowutran** [comment]
recheck that: https://github.com/neowutran/ShinraMeter/wiki#network
If that doesn't work, then no idea
