### ISSUE TITLE
bug: buff events false triggering on dungeon exit during combat

### ISSUE THREAD

**Issue by Owyn** [neowutran/ShinraMeter#280]
if you teleport out of the dungeon during boss fight (via "release" command at least) all events for missing buffs and consumables are triggered at once and user is spammed by those

**Comment by Gl0** [comment]
We stop triggering events on user spawn, so it can be false triggered while map loading or if meter missed s_spawn_me packet (check error.log for debug messages).

**Comment by Owyn** [comment]
error.log has nothing from that day as usual
https://www.twitch.tv/owyntyler/v/109784616 
02:52:47 shows it

**Comment by Gl0** [comment]
Will dig into packets to workaround this issue.
