### ISSUE TITLE
does shinra meter work with 4G mobile broadband modem?

### ISSUE THREAD

**Issue by probatya** [neowutran/ShinraMeter#281]

**Comment by Gl0** [comment]
Should work. If your modem connection is not detected via latest npcap - you can always switch to raw sockets.

**Comment by probatya** [comment]
I have tried raw socket and server override, It gaves nothing. :(

**Comment by Gl0** [comment]
Server overrides have nothing common with direct game connection.
All you need is properly switch to raw sockets mode, with changing config and adding **correct** firewall exception for meter.

**Comment by probatya** [comment]
With 4g modem I have ethernet connection also. Via ethernet DPS meter working well, but 4g modem doesn't. I had tried raw sockets mode, it didn't work.

**Comment by Gl0** [comment]
In raw sockets mode it should work despite of connection type.
