### ISSUE TITLE
[Request] Enrage Indicator or Timer

### ISSUE THREAD

**Issue by careful7j** [neowutran/ShinraMeter#282]
Would like to have some kind of idicator of Enrage in Shinra window. I know there are notifications "Enrage started" and "Enrage is over", but it could be nice to be able to somehow check if boss is enraged in case I have missed "Enrage started" message. Also it could be great if not only indicator but a timer appear like:
0:30, 0:29.... 0:00 - so I can always decide to use boosts or not :) Thank you!

Btw thank you for short debuff output, I see people are now using it on RU servers. 
p.s. Is there any way how can I donate a few $ to your project? :D

**Comment by neowutran** [comment]
Will start working on that soon ^^ 

& atm, didn't setup any donation system

**Comment by careful7j** [comment]
Wuuu thank you! Waiting to see it in game :) Good job!

**Comment by neowutran** [comment]
added with TCC UI integration

**Comment by careful7j** [comment]
Yes, the best implementation ever, thank you! :)
