### ISSUE TITLE
[POPUP NOTIFICATION] Phase out NotifyIcon

### ISSUE THREAD

**Issue by careful7j** [neowutran/ShinraMeter#283]
Right now notifications are appearing at right-bottom part of the screen (Enrage, missing crystalbind e.t.c.). But some of my friend find it not very comfortable, is there a way how we can change it - so it appear on top-centre or some other corner of the screen? If there are no such option it could be nice to have it :)

**Comment by Gl0** [comment]
That require implementing notification window from scratch, now it just a tray icon popup. We have plans to do it, but not sure, when.

**Comment by careful7j** [comment]
Thank you for you responce! I have moved windows control panel with tray and it followed it. A kind of solution anyway :) thank you!

**Comment by neowutran** [comment]
#335 #328 #275

**Comment by neowutran** [comment]
a fix will be released in 1.97

**Comment by neowutran** [comment]
1.97 released, should be fixed
