### ISSUE TITLE
bug: no reset for fight

### ISSUE THREAD

**Issue by Owyn** [neowutran/ShinraMeter#284]
https://www.twitch.tv/owyntyler/v/111136480 
01:11:45 - new boss fight just continued from old try and combined stats (fight time etc)

btw, I checked "count only bosses" in settings but it still counts some random mob fights in world (see data for Poporia: Fimbirlisk before boss start)

**Comment by Gl0** [comment]
It wasn't reset due to fimbrilisk was current encounter.
Just check "Detect bosses by HP bar (ignore DB)" to force openworld bosses to be regular mobs.

**Comment by Gl0** [comment]
and / or "Count only party"

**Comment by Owyn** [comment]
> It wasn't reset due to fimbrilisk was current encounter.

you sure?

I thought it was cuz I teleported from boss during battle...

**Comment by Gl0** [comment]
It anyway reset on boss spawn after teleport back, but only if boss is current

**Comment by Owyn** [comment]
> and / or "Count only party"

does it include only party or whole raid too? I want reid to be counted too...

**Comment by Gl0** [comment]
raid too, but ignore unknown damage, btw probably need exception for it

**Comment by Owyn** [comment]
>Just check "Detect bosses by HP bar (ignore DB)" to force openworld bosses to be regular mobs.

so what "count only bosses" setting does then? what is it for?

**Comment by Gl0** [comment]
Both should be checked.
