### ISSUE TITLE
Shinra Meter not showing any information

### ISSUE THREAD

**Issue by cobra0798** [neowutran/ShinraMeter#287]
upon startup of Shinra meter and TERA, I get this error message:

![error message](https://cloud.githubusercontent.com/assets/19150422/21752779/8ac8bfb4-d5ac-11e6-91ac-e010fedea6d1.png)
The error log: (I renamed it to error.txt since this site doesn't support uploading .log files.
[error.txt](https://github.com/neowutran/ShinraMeter/files/692383/error.txt)

When I log in to a server, it does register that I am logged in.
![connected](https://cloud.githubusercontent.com/assets/19150422/21752780/8ac94c90-d5ac-11e6-853f-a41ff3139e5a.png)

When I am in a dungeon, however, no stats show while fighting a boss.
![not working](https://cloud.githubusercontent.com/assets/19150422/21752778/8ac839fe-d5ac-11e6-97e5-6c0c46496ba7.png)
I play the game through steam and do not use WTFast. 
I did install the .NET 4.6.1, WinPCap 4.1.3, and ran the add firewall exception.bat included in the download file.

**Comment by Gl0** [comment]
Download latest version manually

**Comment by cobra0798** [comment]
ah, didn't realize I had downloaded the oldest version available instead of the most recent.
