### ISSUE TITLE
Conflict with utorrent v2.2.1

### ISSUE THREAD

**Issue by jstnobody** [neowutran/ShinraMeter#290]
It seems that shinra meter has some conflict with utorrent.
In-game the meter does not register any dps from any class while the tray icon showing it is connected to the server. Also it gives random and uncontrolled warnings about the CCB, Battle Solution, for mystic class also sends notices about auras and for ninja about the focus skill, ik these warning can be turned off but that is not the point.

**Comment by neowutran** [comment]
check what server is detected by the meter (mouse over the icon in system tray). 

Meter have issue with bitcoin blockchain resync, & will probably have issue with every network-heavy software

**Comment by jstnobody** [comment]
tray icon detected Celestial Hills but to honest with you was acting like a police siren

**Comment by Gl0** [comment]
That's strange. I see the only way of such things happening while showing "VPN" there, if you have no servers entries added manually.

**Comment by jstnobody** [comment]
ok i fixed the problems with utorrent (simply changed the port that uT was using, strange but it works...)
but now there is a conflict with discord client, the meter acts same as it did with uT
