### ISSUE TITLE
Problem with adding an event for skill cooldown

### ISSUE THREAD

**Issue by Trex1337** [neowutran/ShinraMeter#291]
this is the code i go in slayer's event file and its not showing any event when incoldblood resets. i have tried  in cold blood II but didnt work so i added all and still doesnt work. also has quatrfoil brooch cooldown.Im using shinra v1.71 and got skill ids from skills-EU-EN file.
can someone tell me where is the problem.

**Comment by Trex1337** [comment]
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<events>
<cooldown ingame="true" active="true" skill_id="200100">
        <actions>
            <notify>
                <balloon title_text="{skill_name} reset" body_text="{skill_name}" display_time="3000" />
                <beeps>
                    <beep frequency="185" duration="500"/>
                </beeps>
            </notify>
        </actions>
    </cooldown>
<cooldown ingame="true" active="true" skill_id="200200">
        <actions>
            <notify>
                <balloon title_text="{skill_name} reset" body_text="{skill_name}" display_time="3000" />
                <beeps>
                    <beep frequency="185" duration="500"/>
                </beeps>
            </notify>
        </actions>
    </cooldown>
<cooldown ingame="true" active="true" skill_id="200300">
        <actions>
            <notify>
                <balloon title_text="{skill_name} reset" body_text="{skill_name}" display_time="3000" />
                <beeps>
                    <beep frequency="185" duration="500"/>
                </beeps>
            </notify>
        </actions>
    </cooldown>
<cooldown ingame="true" active="true" skill_id="200400">
        <actions>
            <notify>
                <balloon title_text="{skill_name} reset" body_text="{skill_name}" display_time="3000" />
                <beeps>
                    <beep frequency="185" duration="500"/>
                </beeps>
            </notify>
        </actions>
    </cooldown>
<cooldown ingame="true" active="true" skill_id="65000510">
        <actions>
            <notify>
                <balloon title_text="{skill_name} reset" body_text="{skill_name}" display_time="3000" />
                <beeps>
                    <beep frequency="185" duration="500"/>
                </beeps>
            </notify>
        </actions>
    </cooldown>
</events>

**Comment by Trex1337** [comment]
apparently, i can't past the code here. so maybe someone could help and tell me how to add an event for skill cooldown resets and where to find skill IDs.

**Comment by Gl0** [comment]
AFAIK ICB cooldown can't be reset?

**Comment by Trex1337** [comment]
by reset i mean the cooldown is finished or skill is ready to be used again. my bad

**Comment by Gl0** [comment]
cooldown reset event tracks only reset, not normal end.

**Comment by Trex1337** [comment]
so there is no event for tracking cooldown of icb or broach for example ?

**Comment by Gl0** [comment]
No, there is no timers for now

**Comment by Trex1337** [comment]
ty !

**Comment by Gl0** [comment]
btw you can set up beep on icb / brooch abnormality added that have some seconds of silence at the beginning so that it beeps at the end of cooldown (without showing anything on screen).
