### ISSUE TITLE
Tera Priest Notifactions

### ISSUE THREAD

**Issue by RapturesAngel** [neowutran/ShinraMeter#293]
The Blessing of Shakan constantly beeps and the only way to turn it off is to turn off all notifications but I don't want to do that. It beeps even if it's applied.

**Comment by Gl0** [comment]
https://github.com/neowutran/ShinraMeter/wiki/Events

> Latest defaults have only basic events active, so if you hear too much annoying beeps from 1.59 default configs - just delete old events-*.xml.
