### ISSUE TITLE
Missing buffs in buff-list

### ISSUE THREAD

**Issue by Owyn** [neowutran/ShinraMeter#294]
Mana-buffs to be specific: ones from new tiaras, and old ones from back-crit mana crystals

wanted to check uptime and mana given, but those were missing both from buff-list and from "mana" tab

![tera_screenshot_20170125_234240](https://cloud.githubusercontent.com/assets/1309656/22309176/3671847a-e35b-11e6-9385-755a1ced399a.png)
![tera_screenshot_20170125_234220](https://cloud.githubusercontent.com/assets/1309656/22309175/36713e98-e35b-11e6-97c5-9a43868eb594.png)

**Comment by Gl0** [comment]
They are just ticking as mp regen without showing as buffs. But their ticks can be seen only for meter user.

**Comment by Gl0** [comment]
We can add mpchange abnormals to buff list, but that may cause a bunch of mp regening trash to show there, since most of things that change mp do it via buffs/debuffs, even if it is just a single tick

**Comment by Owyn** [comment]
Well, not mana tab is just practically empty with single priest skill for MP, so enabling those would be totally OK

**Comment by Gl0** [comment]
Let look at it in next release

**Comment by Gl0** [comment]
You've seen all you need?

**Comment by Owyn** [comment]
Sorry, can't test it, rarely playing currently
