### ISSUE TITLE
Sniper's eye

### ISSUE THREAD

**Issue by Adid1** [neowutran/ShinraMeter#298]
Hello, is there an option to make a warning when sniper's eye skill isn't on during fight same as ninja's Focus? if there is, how to make it warn me, and if there isn't it would be amazing if you could add that kind of feature!
have a great day!

**Comment by Gl0** [comment]
You can configure it in the same way as any other missing abnormality event.
https://github.com/neowutran/ShinraMeter/wiki/Events
