### ISSUE TITLE
Shinra meter not showing server nor working

### ISSUE THREAD

**Issue by zaphrevan** [neowutran/ShinraMeter#300]
okay I have both Wincap and Ncap installed, still starting TERA relogging and shit, and the meter does not work, does not detect the server

**Comment by neowutran** [comment]
uninstall winpcap,
reinstall npcap with "support winpcap api" checked
restart 

if it doesn't work, switch to raw socket 
https://github.com/neowutran/ShinraMeter/wiki#network

**Comment by zaphrevan** [comment]
thank you that solved that problem, also there is a small detail, back then, the meter used to overlay ingame in fullscreen, its not doing that anymore, Any setting I should modify for the overlay?

**Comment by neowutran** [comment]
Overlay work only in windowed and windowed (fullscreen) mode.
The real fullscreen mode is not supported, too much work needed

**Comment by zaphrevan** [comment]
ohh makes sense, thank you tho, I appreciate your help.
