### ISSUE TITLE
Fullscreen support

### ISSUE THREAD

**Issue by Herz3h** [neowutran/ShinraMeter#302]
Hello, 

I was just wondering why doesn't this support fullscreen mode?

**Comment by Gl0** [comment]
True fullscreen overlay require a lot of low level coding. We don't have so much free time to implement it.

**Comment by NickGrease** [comment]
Just out of curiosity, and because I don't know enough, Discord seems to have figured out the fullscreen thing, anyway you could piggyback off that code?

**Comment by Gl0** [comment]
Discord is not open source - we can't get any code from it. And they have much more ppl working on it as their primary work while we are improving meter in our free time.
