### ISSUE TITLE
Dispose a TrayNotifyIcon

### ISSUE THREAD

**Issue by iHimiko** [neowutran/ShinraMeter#303]
I see icon tray when exit from app, and can i help to fix it.
Just add new field in App.xaml.cs
` public static TaskbarIcon TrayTaskbarIcon;`
and write data to this from NotifyIcon.xaml.cs.
To remove icon from TaskBar just need relese it from event
`protected override void OnExit(ExitEventArgs e)
{
    TrayTaskbarIcon?.Dispose();
    _unique.ReleaseMutex();
    base.OnExit(e);
}`
And dont forget remove it from App.xaml and from App.xaml.cs
`private void App_OnExit(object sender, ExitEventArgs e)
{
    _unique.ReleaseMutex();
}`

**Comment by neowutran** [comment]
thanks =)
