### ISSUE TITLE
DPS not posting in game?

### ISSUE THREAD

**Issue by Alexotic** [neowutran/ShinraMeter#305]
I have tried to get the DPS to post itself in game but it apparently gets stuck while trying to do so. Does the command not work by default? If this is the case, then I do not have the capabilities to edit the hotkey file myself. It copies it to my clipboard, and I see it try to enter it into chat, but nothing goes through into the actual chat.

**Comment by Gl0** [comment]
Game chat should be ready for text input when you are pressing hotkey.
