### ISSUE TITLE
Overriding the list of area IDs for private dps servers

### ISSUE THREAD

**Issue by Malalicious** [neowutran/ShinraMeter#308]
Currently the list of dungeons where data gets sent to a private dps server is restricted. Perhaps it would be an idea to allow users to override this list.

**Comment by neowutran** [comment]
https://github.com/neowutran/ShinraMeter/issues/348
https://github.com/neowutran/ShinraMeter/tree/dps-servers-refactoring

Extended support for dps server config will be added with next release

**Comment by neowutran** [comment]
2.01
https://github.com/neowutran/ShinraMeter/wiki/Private-DPS-server
