### ISSUE TITLE
Meter resets on its own

### ISSUE THREAD

**Issue by Emezzel** [neowutran/ShinraMeter#309]
It's totally random , it might reset in 2-3 bosses in a row or once in 3-5 bosses, at random times.
I've checked if I use some reset keybind as a skill in-game but it appears I don't. 

P.S I'm using Tera on fullscreen and I can't see the meter even if i check show always, so i don't know when exactly it resets because I can't see it unless I post it. 

Thanks

**Comment by Gl0** [comment]
You mean full reset, or reset all but latest boss? Second thing may happen if your PC is too slow and meter's packet queue is overloaded.

**Comment by Emezzel** [comment]
I mean full reset. There is no history of any boss left after it resets

**Comment by Gl0** [comment]
Try to change reset hotkeys. or even disable them (use "None" as key) temporary. You will still be able to reset via tray icon actions menu.

**Comment by Emezzel** [comment]
But how do I change them XD?

**Comment by Gl0** [comment]
https://github.com/neowutran/ShinraMeter/wiki#configuring-hotkeys

**Comment by Emezzel** [comment]
I know this file exists and I've opened it before but I don't know what I need to change/delete from all that mass x_x 
I'm sorry if I'm being tiring

**Comment by Emezzel** [comment]
Do I just have to type None between the <key> <key> under the reset and reset current ?

**Comment by Gl0** [comment]
Yes

**Comment by Emezzel** [comment]
Alright, thanks for your help 👍  I'll try it again and see if it resets!

**Comment by Emezzel** [comment]
Seems to be working with no resets the past 2 days! Must be fixed :D Thanks for your help again
