### ISSUE TITLE
TODO: add firewall exception

### ISSUE THREAD

**Issue by neowutran** [neowutran/ShinraMeter#31]

**Comment by Gl0** [comment]
Automatic adding of firewall exception may cause aggro of antivirus software.

**Comment by neowutran** [comment]
Oh, I didn't know, thanks for that info =)
I will probably try to do it on my version & submit it to virustotal
if I get alert, I won't publish that functionnality

**Comment by Gl0** [comment]
AFAIK virustotal have only signature detection, without paranoid proactive defence.

**Comment by neowutran** [comment]
ok, then, closed

**Comment by Gl0** [comment]
It's ok to do it in some kind of installer, showing user request to approve this behavior.
