### ISSUE TITLE
topmost issue

### ISSUE THREAD

**Issue by topmost-tera** [neowutran/ShinraMeter#313]
Hi, 
First of all, I want to specify that I use google translate, so I apologize for my English.
Since a few days, my shinrameter no longer appears in foreground, in front of Tera.
Tera is well in full screen (windowed) and shinrameter settings are correct.
deactivating and reactivating "always show" & "stay topmost" it works again sometimes for a few moments, until I alt-tab to go online.
When launching tera, the dps is displayed correctly (if I uncheck invisible when no stats) but disappears after the choice of the characters.

I downloaded PinMe but this time the dpsmeter is removed when it collects data (combat) and an alt-tab makes it reappear when the combat is finished.

I reformatted my pc but it changed nothing. The dpsmeter settings were not changed between the time it was working properly and now.

I found someone with the same problem but no solution was found : https://github.com/neowutran/ShinraMeter/issues/161

**Comment by Gl0** [comment]
We haven't touched anything that can affect topmost at least for a month.
Have you installed/updated something (windows/gpu drivers/other software)?

**Comment by topmost-tera** [comment]
No, I have not installed or updated anything. Now I have reformatted my pc and the problem is still the same.
I tried again this morning (I uncheck when no stats) :
- The dpsmeter appears correctly before running Tera.
- Disappears during BHS & GF videos.
- Reappears during / after character selection.
- Disappears during a tp to a quest (and is no longer visible even by alt-tab on a web page)

**Comment by Gl0** [comment]
With "Show always" and "Stay topmost" options active and "Invisible when no stats" inactive meter visibility doesn't depend on anything game related. Probably you have some other software/system setting that hides all topmost windows when see fullscreen video playback or something like this. Topmost status should be refreshed by meter when you alt-tab into tera.

**Comment by Gl0** [comment]
Do you have Avast installed? Seems it got "game mode" as an update, and that mode is causing this issue.

**Comment by topmost-tera** [comment]
Yes I have avast. I will try as soon as I can ! Thank you very much
