### ISSUE TITLE
computer is too low to use shinra blablabla

### ISSUE THREAD

**Issue by NEON714** [neowutran/ShinraMeter#316]
is it my computer has really low spec, or shinra doesnt support low spec pc?
have to restart client and close shinra to make it work again. and yeah always have same issue (computer is to low ....)

**Comment by Gl0** [comment]
This error is shown when meter have 3000 unprocessed game messages in queue.
You can disable chat and notification services in settings + reset stats after each fight for faster message processing.
Also you can try to boost meter priority via `<low_priority>false</low_priority>` in window.xml (default value is true). In that case meter should eat more CPU from game.
If all that things won't help - your computer is really too slow for shinra and you should use something more primitive, like https://github.com/Gl0/TeraDamageMeter/releases

**Comment by NEON714** [comment]
sorry but i dont see low priority option in my windows.xml
