### ISSUE TITLE
[Request] Boss %hp and hurricane cd notification

### ISSUE THREAD

**Issue by Qarinna** [neowutran/ShinraMeter#317]
Hello
I think it would be appreciated to put boss %hp in the shinrameter window, especially for dungeons with multiple bosses, which will prevent screaming in ts/discord such as "what's the white dragon hp" and so on.

Secondly, in order to keep track of hurricane cd, it would be nice to add notification which spams or at least reminds you couple of times that your hurricane is off cd and ready to cast again.

**Comment by neowutran** [comment]
%hp for boss are now displayed with the TCC boss gage integration

& now hurricane doesn't exist anymore
