### ISSUE TITLE
Not opening windows 10

### ISSUE THREAD

**Issue by xAlienation** [neowutran/ShinraMeter#32]
Hey there,

I've loved the ShinraMeter so far! It was the only free dps meter that worked on my windows 10. 
Since the last update today however, when I open the .exe, nothing shows up at all and I can no longer use ShinraMeter. Is it possible that the last update caused some issue with windows 10? I didn't receive an error, so I don't know if there's any extra information I can give you. 

Kind regars,
Alienation

**Comment by neowutran** [comment]
hey

activate winpcap
or
create a firewall rule
see wiki
https://github.com/neowutran/ShinraMeter/wiki#network

**Comment by neowutran** [comment]
(and UI doesn't work the same way: 
https://github.com/neowutran/ShinraMeter/wiki#ui
)

**Comment by Gl0** [comment]
May be you change UI behavior back to show full UI at startup. Many users don't understand, whether it started correctly or not. =)

**Comment by xAlienation** [comment]
For me, the issue has been resolved by adding Shinra to my windows firewall rules as you advised. Thanks for the help, should have read the wiki better.
