### ISSUE TITLE
Issue with shinra launcher (Win 7)

### ISSUE THREAD

**Issue by Orange-Ass** [neowutran/ShinraMeter#322]
While playing tera using shinra launcher my mouse is appearing on my screen (so it's not locked ingame anymore) so the next keyboard spells aren't captured by the game and it starts capturing again after the next mouse spell.
While it happens the windows process Werfault.exe  appears on task manager for like 0.5s.
I fixed it closing shinra launcher process.
Tera settings: Borderless

**Comment by neowutran** [comment]
shinra launcher will be delete with next update ^^
