### ISSUE TITLE
[POPUP NOTIFICATION] Click throu needed

### ISSUE THREAD

**Issue by ryanrjk** [neowutran/ShinraMeter#328]
Everytime the notifcation comes up displaying enrage, adreniline rush etc, my mouse skills stop working. I cant use left click, right click, or mouse buttons. Is there a solution for this?

**Comment by neowutran** [comment]
that means you mouse is over the area where the notification popup. No solution atm for that

**Comment by neowutran** [comment]
#335 #283 #275

**Comment by neowutran** [comment]
a fix will be released in 1.97

**Comment by neowutran** [comment]
1.97 release, should be fixed
