### ISSUE TITLE
Skill off cooldown in X seconds event

### ISSUE THREAD

**Issue by MuffinName** [neowutran/ShinraMeter#329]
Hi, I've been trying to get a notification for when there are only X seconds left on a certain skill's cooldown, but I'm not quite sure how to do that. The cooldown reset sample code in the wiki is 

`<cooldown ingame="true" active="true" skill_id="111100">`.

but that only works if the skill actually reset. I wanted to get a beep for when the skill's cooldown has run out first, as adding the X seconds before that should just require adding a 

`remaining_seconds_before_trigger=`

as far as I'm aware. The thing is, I don't really understand how `<cooldown>` works, how to add some kind of `trigger=ending` there and so on. 

If someone could explain to me what `ingame="true" active="true"` means in the context of `<cooldown>` or how to reference the cooldown running out I'd be very grateful!

**Comment by neowutran** [comment]
the cooldown event work only for reset. 
Not working for normal cooldown

& 
`ingame="true"` means to display the notification only if Tera is the focused window
`active="true"`  means to disable this event or not
