### ISSUE TITLE
bug with zerker

### ISSUE THREAD

**Issue by dovev1** [neowutran/ShinraMeter#331]
canceling animations with block sometimes makes block stuck. happens only when using shinra meter and to some people. but to those who have it happen, happens quite often.(on a side note, it started happening recently, after some update, not sure if its related.)

**Comment by neowutran** [comment]
the only case where meter can cause this kind of behavior is if you click on the shinra meter while playing. You can activate click throu to avoid this behavior (by default: ctrl + page up )

**Comment by dovev1** [comment]
will try that, but wierd thing was i could rotate camera with mouse while left or right click wouldnt work( tried switching block to left click, still same), and its not mouse issue since ive tested multiple mouses.

**Comment by dovev1** [comment]
little update, still happens, even with click throu option turned on

**Comment by neowutran** [comment]
then impossible to be related to meter, meter don't modify the game
