### ISSUE TITLE
Boss gagebar

### ISSUE THREAD

**Issue by boymin2ne1** [neowutran/ShinraMeter#334]
How do u remove the ingame boss gagebar if im using the TCC embedded ones? I download the file given by K but where do i put it or what do i do with it?

**Comment by Gl0** [comment]
`TERA\S1Game\CookedPC\Art_Data\Packages\_S1UI`

**Comment by boymin2ne1** [comment]
So do i remove anything there or replace the file in it?

**Comment by neowutran** [comment]
same thing as other tera UI mod. **You don't remove anything.** 
you create this folder if it doesn't exist 
`TERA\S1Game\CookedPC\Art_Data\Packages\_S1UI`
& put the GageBoss.hgpk file inside
https://github.com/neowutran/ShinraMeter/wiki#boss-gage-replacement
