### ISSUE TITLE
Boss Bar events

### ISSUE THREAD

**Issue by Owyn** [neowutran/ShinraMeter#337]
Can we please have events for bass bar? so a TTX would say when is next rage gonna be after current one ends like:

"Next enrage on 76% HP"

Because bossbar isn't shown when playing fullscreen obviously, and I don't want to play windowed

**Comment by Gl0** [comment]
Moment when you receive that notification will be the same as enrage end notification. So you should remember this number all the time. With the same efficiency you can just set notification on enrageend and look at boss bar after it.

**Comment by Owyn** [comment]
>you can just set notification on enrageend and look at boss bar after it.

but what text can I put there in enrageend? I'd like a "Next enrage on \n % HP"
