### ISSUE TITLE
sorcerer DPS ERROR

### ISSUE THREAD

**Issue by sb032835** [neowutran/ShinraMeter#34]
sorcerer DPS is wrong 
total damage percentage, crit rate, number of hit received, damage received work well
but dps abnormal

**Comment by neowutran** [comment]
what do you means by anormal? 
do you still have the values?

**Comment by sb032835** [comment]
unusual ?
sorcerer DAMAGE PER SECOND More than the original

**Comment by Gl0** [comment]
more than original or more than counted via damage/time ?

**Comment by sb032835** [comment]
http://i.imgur.com/ro3mpcG.png

**Comment by sb032835** [comment]
I think fighting time record is not correct

**Comment by neowutran** [comment]
indeed, weird timer. 
If you found a way to reproduce that issue, I will be able to fix that.

**Comment by neowutran** [comment]
It s like the sorcerer only did one dps burst, then stopped to do anything

**Comment by sb032835** [comment]
ok, I will try to look for that 
thank you

**Comment by Gl0** [comment]
It's very unlikable, that sorc can burst 8M/s on a single target for 9 sec and than do nothing for 3min

**Comment by kuko0411** [comment]
Doesn't seem to be unique to sorcerers - same thing happened to one gunner in my party. 3M/s dps because his time gone to to like 5 seconds.

**Comment by Gl0** [comment]
Still see such bad timing on fresh screenshots posted on forums.

**Comment by neowutran** [comment]
Ok, will try to look for that. 
But for now, no real idea

**Comment by Gl0** [comment]
btw, can you give us ServerId's of TW servers? It can be either sniffed all together in http xml exchange between launcher and server, either seen one by one in tooltip of the player.

**Comment by neowutran** [comment]
I think I can close that, never seen that again
