### ISSUE TITLE
Popup event window position

### ISSUE THREAD

**Issue by FusenSho** [neowutran/ShinraMeter#341]
Hi I just wanted to report, that the popupwindow is not saving its position.
I am using 2 monitors and normally its in the right bottom corner above the windows clock but since it extends the longer messages to the wrong side, i changed the position to where my game is displayed.
After every restart of the meter it is located back in the bottom right corner above the windows clock.

**Comment by Gl0** [comment]
In 1.99 it will be snapable to screen edge, so you'll be able to put it back to the bottom right corner.
Meter saves config on correct close. If you kill it via task manager or it died due to some error - all your setting changes will be lost.

**Comment by FusenSho** [comment]
Okay, great :) 
And well I am closing it manually all the time but its not saving the lovcation of the popups :/
