### ISSUE TITLE
Shinra Meter v.065/0.64: No server

### ISSUE THREAD

**Issue by Ancyfer** [neowutran/ShinraMeter#35]
HI, have some problem to use new version shinra .
ver 0.61 and earlier work fine.
ver 0.62/0.63 fatal eror 
[https://drive.google.com/file/d/0B4AZvtHEzR8kbzRaXzFDbUg4WFU/view?usp=sharing](url)
ver 0.65 says (Shinra Meter v.065/0.64:No server) before run terra and after too.
Win7 x 64  
Winpcap 4.6 installed
Im use UK vpn for authorization (pptp).
I hope to help.

**Comment by Gl0** [comment]
read https://github.com/neowutran/ShinraMeter/wiki#network for instructions

**Comment by Ancyfer** [comment]
tnx for help, I`m add  incoming firewall rule - is no help .

**Comment by Gl0** [comment]
> If that doesn't work, you can switch back to winpcap

**Comment by Ancyfer** [comment]
tnx
