### ISSUE TITLE
Notifications Reset (Enrage. Adrenaline Rush, etc..)

### ISSUE THREAD

**Issue by ryanrjk** [neowutran/ShinraMeter#358]
The notification window appears on top left of my screen, but its hard to see it sometimes for the enrage and when lancers use buffs and such. So i tend to move it down towards the middle of my screen to really make it noticeable mid fight. Everytime I reopen the meter (like... the following day) the position resets back to the corner.. Is this intentional?

**Comment by neowutran** [comment]
Settings are saved when the meter is gracefully closed. If you shutdown your computer before closing the meter, settings won't be saved. 

In next version, settings should be saved on shutdown, in theory

**Comment by ryanrjk** [comment]
hmm strange, i do close normally. all the settings save, and UI positions are saved.. the only thing that isn't is just that one notification box.

**Comment by neowutran** [comment]
verify if you have the latest version of meter (2.01) & try again
