### ISSUE TITLE
ShinraMeter fails to start

### ISSUE THREAD

**Issue by UberUlow** [neowutran/ShinraMeter#36]
When I run the program icon appears in the system tray with an inscription: "Shinra Meter V0.65: No server". Any interaction with the icon of the program is closed.
[Screenshot](http://imgur.com/f9RfbUi)
I have installed Eset Smart Security 9. Therefore, it did not help: [link](https://github.com/neowutran/ShinraMeter/wiki/Window-firewall)

> If that doesn't work, you can switch back to winpcap:
> window.xml to switch
> <winpcap>false</winpcap> => <winpcap>true</winpcap>

[Result](http://imgur.com/Y5WrYPQ)

**Comment by UberUlow** [comment]
> Go dps something, and the UI will show up

The problem was solved, sorry to trouble you.

**Comment by UberUlow** [comment]
But it's not a very good solution (show window on damage). Previously, it was better, I could immediately remove the property - on top of all windows.

**Comment by Gl0** [comment]
This made configurable via config file in next version, with old behavior by default.

**Comment by neowutran** [comment]
Yep ^^ the UI is not really intuitive in this version. I'm working on it

**Comment by UberUlow** [comment]
Thank you very much for your response.
