### ISSUE TITLE
Tera.exe stopped working.

### ISSUE THREAD

**Issue by adem940** [neowutran/ShinraMeter#361]
so I wanted to give Shinra Meter a try but everytime I launch the game, it is crashing, if I don't use Shinra, it starts normal, also there is an ''add firewall exception'' bat file in folder, I am running it as admin but it still tells me to run it as admin -_-

**Comment by Gl0** [comment]
May be your network setup is incompatible with npcap - try switching to raw sockets (see wiki).
Or there are some issues with video drivers.

**Comment by adem940** [comment]
I was using winpcap before since I am using casual meter, I installed npcap, uninstalled winpcap, casual meter is working well with npcap too, but shira doesn't work for me... I don't know what it has to do anything with video drivers, it is updated to latest one, game is running well.

**Comment by Gl0** [comment]
Than idk what's going on, casual meter use 90% same code for packet processing (and it should not affect game since it's passive sniffing, but I heard about some issues with npcap causing tera crash when meter is active) and same technique for topmost windows (but latest shinra toggles it more frequently to workaround latest win10 issues with topmost windows). Most significant difference - shinra use dotnet 4.7 while casual use 4.5. Another option that can affect game - recently added fullscreen overlay, but it's disabled by default.

**Comment by adem940** [comment]
I even updated my windows to latest one just to get framework 4.7 so I could use Shinra but no luck, oh well.

**Comment by neowutran** [comment]
The game is crashing? you tried to use raw socket instead of npcap/winpcap? 
in what region do you play?

**Comment by adem940** [comment]
I play from Eastern Europe, how to enable raw socket? when I click play button, it instantly says ''tera.exe stopped working'' :s

**Comment by Gl0** [comment]
Then raw sockets would not help probably. Sounds like some virus/antivirus issue.

**Comment by adem940** [comment]
I don't have any antivirus running, Tera gives fatal client exception error..

**Comment by neowutran** [comment]
probably some issue on operating system level / virus / broken patch... Can't really do anything without any logs. 
You could try to install it on another computer & reinstall your OS 

Last time I got the issue you describe was when BHS tried to block meter in Korea. It should be unrelated to your problem. You can still try to run the "randomizer.exe" once & try to launch meter & check. But should not change anything.

**Comment by Gl0** [comment]
The only thing in meter that can cause such behavior - fullscreen overlay, recheck that it is disabled in settings and restart meter.
But you will be the first who report it - probably that's not the root of problem.

**Comment by adem940** [comment]
I realized overlay was enabled, I disabled it and it works now ^^

**Comment by iHimiko** [comment]
If you have a problem with Overlay, you need to install the MVC ++ packages 2005-2017
