### ISSUE TITLE
shinra fatal error on hotkey for deaths

### ISSUE THREAD

**Issue by Owyn** [neowutran/ShinraMeter#362]
````<copy>
      <ctrl>True</ctrl>
      <shift>False</shift>
      <window>False</window>
      <key>End</key>
      <string>
        <header>Damage Taken @ {encounter} {timer}:\</header>
        <content>{class} - {name}: Death {deaths} = {death_duration} Aggro {aggro} = {aggro_duration} Hits: {hits_received} = {damage_received}\</content>
        <low_dps_content>{class} - {name}: \</low_dps_content>
        <low_dps_threshold>0</low_dps_threshold>
        <limit_name_length>0</limit_name_length>
        <footer></footer>
        <order_by>death_duration</order_by>
        <order>descending</order>
      </string>
    </copy>
````

**Comment by Gl0** [comment]
`death_duration` is not valid option for `order_by`.
And you can see that statement in error.log after crash

**Comment by Owyn** [comment]
can you fix that?

**Comment by Gl0** [comment]
that require rework of the whole chat paste sorting

**Comment by Owyn** [comment]
ok, but can you at least make it not crash with fatal error?

**Comment by Gl0** [comment]
just configure it properly )

**Comment by Gl0** [comment]
supported for now
`damage_received`
`name`
`dps` = `damage_dealt` = `damage_percentage` (same result)
`crit_rate`
`hits_received`

**Comment by Owyn** [comment]
but it makes no sense to sort death chat linking by dps or damage_received ;s unlike deaths or death time

**Comment by Gl0** [comment]
death tracking appeared much later than that sorting code...

**Comment by neowutran** [comment]
finally added
