### ISSUE TITLE
How to remove the second overlay window

### ISSUE THREAD

**Issue by Foobar11a590** [neowutran/ShinraMeter#365]
Hello. Is there a way to get rid of the second overlay window? I couldn't find any setting or hotkey that would hide it.

It cannot be moved and just shows redundant information :) It disappears after reset but re-appears again in combat.

![image](https://user-images.githubusercontent.com/29923589/27870314-d8934c14-61a2-11e7-9b5a-5ca8e6671809.png)

**Comment by Gl0** [comment]
Uncheck "Enable overlay" in settings

**Comment by Foobar11a590** [comment]
Wow, thanks :+1:  now I feel dumb. I thought overlay would hide them both so I didn't even bother to try :)
