### ISSUE TITLE
Notifications: Crystalbind Missing, Enrage, Nostrum etc.

### ISSUE THREAD

**Issue by ashjnr** [neowutran/ShinraMeter#366]
Is there any way to close those notifications?
I guess they are under "Party Events" but "Disable Party Events" doesn't work.

**Comment by neowutran** [comment]
Every notification is configurable individually, (or globally if you want none)
check the wiki for details https://github.com/neowutran/ShinraMeter/wiki/Events 
Crystalbind/enrage/nostrum are in the file "event-common.xml"

**Comment by ashjnr** [comment]
Thank you so much

**Comment by neowutran** [comment]
np : )
