### ISSUE TITLE
Cant make the paste to work

### ISSUE THREAD

**Issue by Fengxiah** [neowutran/ShinraMeter#367]
Hi, 

I can't make the paste dps to work, 
When I use the hotkey shift+end, i can see the chat opening and closing many times, but it doesn't paste anything, 

Any idea what's wrong or what i'm doing wrong ?

PS : I didnt change anything, all is by default.

ty.

**Comment by neowutran** [comment]
Hi, you need to have the chat box already open before using the hotkey

**Comment by Fengxiah** [comment]
Lol I see ! Thx a lot for the fast answer !

**Comment by neowutran** [comment]
np ^^
