### ISSUE TITLE
https://cloud.neowutran.ovh/index.php/s/e7arRRxkHEIkzU1 not showing latest versions

### ISSUE THREAD

**Issue by Gl0** [neowutran/ShinraMeter#37]
It's browser related, scrolling is bugged in IE.
The only way to see end of the list is to zoom out and/or maximize height

**Comment by neowutran** [comment]
huehuehue x) right
Don't want to rewrite the CSS, so just removing the old version

**Comment by neowutran** [comment]
(scrolling is bugged too in FF )
