### ISSUE TITLE
notification can't work 

### ISSUE THREAD

**Issue by rkay8496** [neowutran/ShinraMeter#373]
beep sound and popup window can't work.
please help me.

setting information is like this:

[window.txt](https://github.com/neowutran/ShinraMeter/files/1230097/window.txt)

**Comment by neowutran** [comment]
Event system are not in this file. Check event file & wiki https://github.com/neowutran/ShinraMeter/wiki/Events

**Comment by rkay8496** [comment]
i didn't modify event files.

after updating 2.04v, this problem happened

**Comment by neowutran** [comment]
You have to give me more infos : 
- What was the exact previous behavior ? ( Beeps ? TTS ? MP3 file ? )
- What is the exact current behavior ?
- Events.xml config files
- Eventual modification you did

**Comment by rkay8496** [comment]
- What was the exact previous behavior ? ( Beeps ? TTS ? MP3 file ? )
Previously, the program informed me of rage or skill cooldown in pop-up windows and beeps.

- What is the exact current behavior ?
Now, when I enter combat, the program does not inform the pop-up window and beeps of rage or skill cooldown.

- Events.xml config files
[events-common.txt](https://github.com/neowutran/ShinraMeter/files/1233617/events-common.txt)
[events-ninja.txt](https://github.com/neowutran/ShinraMeter/files/1233619/events-ninja.txt)

As far as I know, I have not modified the file.

**Comment by neowutran** [comment]
- Check System sound volume 
- Check in the settings if you really have the "Chat and Notification" enabled

Meter is showing correctly?

**Comment by rkay8496** [comment]
The meter works well.

**Comment by rkay8496** [comment]
It seems to be good because I update it.

**Comment by rkay8496** [comment]
It seems to be good after the update.
