### ISSUE TITLE
KR Boss HP Bar

### ISSUE THREAD

**Issue by ayx1995** [neowutran/ShinraMeter#374]
The Boss HP bar isn't working the debuff icons and duration is showing but not the HP, Enrage, Enrage timings. 

Not sure if this issue is reported

**Comment by Gl0** [comment]
should be fixed in 2.05

**Comment by ayx1995** [comment]
Can I ask roughly when? Thanks :smile:

**Comment by Gl0** [comment]
working? Or they changed something else?

**Comment by ayx1995** [comment]
Yes, its working now! Thanks! yup the S_CAGE_INFO float -> int64
