### ISSUE TITLE
RU-crash 8/24

### ISSUE THREAD

**Issue by KeioSeko** [neowutran/ShinraMeter#375]
crash after unplanned maintenance

[error.txt](https://github.com/neowutran/ShinraMeter/files/1247644/error.txt)

**Comment by neowutran** [comment]
seems like they did an update at the same time

**Comment by KeioSeko** [comment]
> seems like they did an update at the same time

Yeah, ~50mb client update

**Comment by neowutran** [comment]
someone will get the opcode probably later in the day, will require a meter update after that

**Comment by KeioSeko** [comment]
we've got a big "hype" on RU about client update and a lot of angry comments about crashed ShinraMeter

Is it a big deal to fix or it even impossible? Any news?

**Comment by iHimiko** [comment]
I heard I closed access to the data packets. I think there will be serious recovery problems.

**Comment by PeerageMartin** [comment]
How about TW? Is there any plan to restore just some basic function?

**Comment by Gl0** [comment]
if someone from TW can discover needed packets and send us - we will publish it to users.
the minimal set for most basic dps count is
```
S_GET_USER_LIST
S_LOGIN
S_SPAWN_ME
S_SPAWN_USER
S_SPAWN_NPC
S_SPAWN_PROJECTILE
S_START_USER_PROJECTILE
S_EACH_SKILL_RESULT
```

**Comment by PeerageMartin** [comment]
I don’t know if it is too difficult to get these packets. So can you offer a tutorial on it?  Maybe I'll try.
