### ISSUE TITLE
Error Fatal / nvm

### ISSUE THREAD

**Issue by Fengxiah** [neowutran/ShinraMeter#376]
Hi, 
I can't seem to make the meter work ever since this afternoon, can u help me ? here's my log : 

Edit : i didnt know it was the same for everyone/

**Comment by clfarron4** [comment]
We know it doesn't work. Patches have been implemented so it doesn't work.

Possible duplicate of https://github.com/neowutran/ShinraMeter/issues/375

**Comment by Fengxiah** [comment]
Oh mb I didnt know
