### ISSUE TITLE
Wrong notification

### ISSUE THREAD

**Issue by Conor29134** [neowutran/ShinraMeter#379]
Latest ver prompt "party matching sucess" notification after selected character get loaded.
Client need to be minimalized to trigger notification.
http://i.imgur.com/yvBJbak.png

**Comment by neowutran** [comment]
Ya, due to the lastest BHS security update, we don't have gathered every opcode yet ^ ^ 
Will need some time until the new automated tools to retrieve opcode be ready to use

**Comment by neowutran** [comment]
should be fixed now
