### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by NickShaun** [neowutran/ShinraMeter#380]
Hi guys, since the last Update of Tera and the ShinraMeter it crashs for some reason.

Thats the error text, i hope someone can help me.
2017-09-05 13:24:35,571 [12] ERROR ShinraMeter [(null)] - ##### CRASH #####
Ein Aufrufziel hat einen Ausnahmefehler verursacht.
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Delegate.DynamicInvokeImpl(Object[] args)
   bei DamageMeter.PacketProcessingFactory.Process(ParsedMessage message)
   bei DamageMeter.NetworkController.PacketAnalysisLoop()
   bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.IO.FileNotFoundException: Die Datei "J:\ShinraMeter\ShinraMeterV2.10\resources\data\opcodes\320566.txt" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding)
   bei System.IO.File.ReadLines(String path)
   bei Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename)
   bei DamageMeter.Processing.C_CHECK_VERSION..ctor(C_CHECK_VERSION message)
   bei lambda_method(Closure , C_CHECK_VERSION )
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Delegate.DynamicInvokeImpl(Object[] args)
   bei DamageMeter.PacketProcessingFactory.Process(ParsedMessage message)
   bei DamageMeter.NetworkController.PacketAnalysisLoop()
   bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal
System.IO.FileNotFoundException: Die Datei "J:\ShinraMeter\ShinraMeterV2.10\resources\data\opcodes\320566.txt" konnte nicht gefunden werden.
Dateiname: "J:\ShinraMeter\ShinraMeterV2.10\resources\data\opcodes\320566.txt"
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding)
   bei System.IO.File.ReadLines(String path)
   bei Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename)
   bei DamageMeter.Processing.C_CHECK_VERSION..ctor(C_CHECK_VERSION message)
   bei lambda_method(Closure , C_CHECK_VERSION )
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
2017-09-05 13:31:45,680 [13] ERROR ShinraMeter [(null)] - ##### CRASH #####
Ein Aufrufziel hat einen Ausnahmefehler verursacht.
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Delegate.DynamicInvokeImpl(Object[] args)
   bei DamageMeter.PacketProcessingFactory.Process(ParsedMessage message)
   bei DamageMeter.NetworkController.PacketAnalysisLoop()
   bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.IO.FileNotFoundException: Die Datei "J:\ShinraMeter\ShinraMeterV2.10\resources\data\opcodes\320566.txt" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding)
   bei System.IO.File.ReadLines(String path)
   bei Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename)
   bei DamageMeter.Processing.C_CHECK_VERSION..ctor(C_CHECK_VERSION message)
   bei lambda_method(Closure , C_CHECK_VERSION )
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Delegate.DynamicInvokeImpl(Object[] args)
   bei DamageMeter.PacketProcessingFactory.Process(ParsedMessage message)
   bei DamageMeter.NetworkController.PacketAnalysisLoop()
   bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal
System.IO.FileNotFoundException: Die Datei "J:\ShinraMeter\ShinraMeterV2.10\resources\data\opcodes\320566.txt" konnte nicht gefunden werden.
Dateiname: "J:\ShinraMeter\ShinraMeterV2.10\resources\data\opcodes\320566.txt"
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding)
   bei System.IO.File.ReadLines(String path)
   bei Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename)
   bei DamageMeter.Processing.C_CHECK_VERSION..ctor(C_CHECK_VERSION message)
   bei lambda_method(Closure , C_CHECK_VERSION )
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
2017-09-05 13:39:15,100 [10] ERROR ShinraMeter [(null)] - ##### CRASH #####
Ein Aufrufziel hat einen Ausnahmefehler verursacht.
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Delegate.DynamicInvokeImpl(Object[] args)
   bei DamageMeter.PacketProcessingFactory.Process(ParsedMessage message)
   bei DamageMeter.NetworkController.PacketAnalysisLoop()
   bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.IO.FileNotFoundException: Die Datei "J:\ShinraMeter\ShinraMeterV2.10\resources\data\opcodes\320566.txt" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding)
   bei System.IO.File.ReadLines(String path)
   bei Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename)
   bei DamageMeter.Processing.C_CHECK_VERSION..ctor(C_CHECK_VERSION message)
   bei lambda_method(Closure , C_CHECK_VERSION )
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Delegate.DynamicInvokeImpl(Object[] args)
   bei DamageMeter.PacketProcessingFactory.Process(ParsedMessage message)
   bei DamageMeter.NetworkController.PacketAnalysisLoop()
   bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal
System.IO.FileNotFoundException: Die Datei "J:\ShinraMeter\ShinraMeterV2.10\resources\data\opcodes\320566.txt" konnte nicht gefunden werden.
Dateiname: "J:\ShinraMeter\ShinraMeterV2.10\resources\data\opcodes\320566.txt"
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding)
   bei System.IO.File.ReadLines(String path)
   bei Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename)
   bei DamageMeter.Processing.C_CHECK_VERSION..ctor(C_CHECK_VERSION message)
   bei lambda_method(Closure , C_CHECK_VERSION )
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

NickShaun

**Comment by SaltyMonkey** [comment]
EU region? EU got new patch. You can wait only

**Comment by Gl0** [comment]
Wait for shinra update. It's not going to be as quick as it was before "security" patch

**Comment by NickShaun** [comment]
ah ok, as i started shinra the first time today there was a "patch" and i thought it would be the right one, thanks for the fast answers =)
