### ISSUE TITLE
Potential bug in calculating damage of pets?

### ISSUE THREAD

**Issue by Seeohelaien** [neowutran/ShinraMeter#382]
![shinrabug](https://user-images.githubusercontent.com/14126356/30242067-e3925e22-958f-11e7-81d1-080b1df2a439.PNG)

Somehow this adds up to more than 100%

**Comment by Gl0** [comment]
should be fixed with https://github.com/neowutran/ShinraMeter/commit/3fe3de59c09afecb75b4665adb1bb87ec474c021
