### ISSUE TITLE
autoupdate error

### ISSUE THREAD

**Issue by Airey1** [neowutran/ShinraMeter#384]
hey I have a problem with updating shinrameter. I've been using shinra for long time and everything was fine but recently i had a 2 months break from tera and tried to update it but I couldnt so I reinstalled newest version and its showing me this error "The update system have been modified and is not compatible with your meter version. Download the new version directly from the website." which i did but its still not working

**Comment by Gl0** [comment]
You shouldn't run autoupdate.exe manually. This file is called internally by meter after downloading updates.

**Comment by Airey1** [comment]
well even if i dont run it manually, when i try to open tera error shows up saying its "unknown client version meter require update to continue working: 321154

**Comment by Gl0** [comment]
Meter require update, but update not yet exists.

**Comment by Gl0** [comment]
when it will be ready you will be prompted to get it on meter startup.

**Comment by Airey1** [comment]
oh thats the case xD I thought i was missing something.. I guess its cuz of recent maintenance

**Comment by Baconcodex** [comment]
By any chance there is estimated time when it will be ready?
