### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by sheldox** [neowutran/ShinraMeter#389]
Hey, my meter always crash with this error. How can i fix it?

> 2017-10-30 14:10:13,412 [14] ERROR ShinraMeter [(null)] - ##### CRASH #####
> UCEERR_RENDERTHREADFAILURE (A kivétel HRESULT-értéke: 0x88980406)
>    a következő helyen: System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
>    a következő helyen: System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
>    a következő helyen: System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
>    a következő helyen: System.Windows.Interop.HwndTarget.OnWindowPosChanging(IntPtr lParam)
>    a következő helyen: System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
>    a következő helyen: System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    a következő helyen: MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    a következő helyen: MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    a következő helyen: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    a következő helyen: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    a következő helyen: System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    a következő helyen: MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
> PresentationCore
> System.Runtime.InteropServices.COMException (0x88980406): UCEERR_RENDERTHREADFAILURE (A kivétel HRESULT-értéke: 0x88980406)
>    a következő helyen: System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
>    a következő helyen: System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
>    a következő helyen: System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
>    a következő helyen: System.Windows.Interop.HwndTarget.OnWindowPosChanging(IntPtr lParam)
>    a következő helyen: System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
>    a következő helyen: System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    a következő helyen: MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    a következő helyen: MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    a következő helyen: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    a következő helyen: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    a következő helyen: System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    a következő helyen: MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
> System.Collections.ListDictionaryInternal
> 
> Void SyncFlush()
> 2017-10-30 14:10:13,418 [15] ERROR ShinraMeter [(null)] - ##### CRASH #####
> UCEERR_RENDERTHREADFAILURE (A kivétel HRESULT-értéke: 0x88980406)
>    a következő helyen: System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
>    a következő helyen: System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
>    a következő helyen: System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
>    a következő helyen: System.Windows.Interop.HwndTarget.OnWindowPosChanging(IntPtr lParam)
>    a következő helyen: System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
>    a következő helyen: System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    a következő helyen: MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    a következő helyen: MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    a következő helyen: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    a következő helyen: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    a következő helyen: System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    a következő helyen: MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
> PresentationCore
> System.Runtime.InteropServices.COMException (0x88980406): UCEERR_RENDERTHREADFAILURE (A kivétel HRESULT-értéke: 0x88980406)
>    a következő helyen: System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
>    a következő helyen: System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
>    a következő helyen: System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
>    a következő helyen: System.Windows.Interop.HwndTarget.OnWindowPosChanging(IntPtr lParam)
>    a következő helyen: System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
>    a következő helyen: System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    a következő helyen: MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    a következő helyen: MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    a következő helyen: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    a következő helyen: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    a következő helyen: System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    a következő helyen: MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
> System.Collections.ListDictionaryInternal
> 
> Void SyncFlush()

**Comment by Gl0** [comment]
Try updating your GPU drivers.

**Comment by sheldox** [comment]
It's updated but same error.

**Comment by neowutran** [comment]
try disabling transparency https://github.com/neowutran/ShinraMeter/wiki#streaming 

( the error won't be fixed, not related to meter. OS / GPU drivers failure )
