### ISSUE TITLE
[Bug] Randomly stops recording

### ISSUE THREAD

**Issue by kuko0411** [neowutran/ShinraMeter#39]
I see no pattern in this, it simply randomly stops reading packets sometimes. Happened several times already, mostly in middle of fight. 

Is there any log or something I can provide with info the next time this happens ?

**Comment by neowutran** [comment]
you are using raw socket or winpcap?

**Comment by Gl0** [comment]
Happend to me several times before [fix buffer size](https://github.com/neowutran/ShinraMeter/commit/5449dc32ccb5677547e40ca5145b19cca6b95222) in KD when killing all mobs before keilvan at one time. May be it was enough for me, but not for all?

**Comment by neowutran** [comment]
idk, 8mo buffer seem pretty huge to me

**Comment by kuko0411** [comment]
Happened using raw socket. 
Probably not buffer issue - last time it stopped in middle of fighting Darkan .

**Comment by Gl0** [comment]
Actually in raw sockets mode buffersize is left as it was, 65536 bytes, it's [overrides later](https://github.com/neowutran/ShinraMeter/blob/4985abb745bc11d0ab0aa9e4ff2f38cf6506deef/NetworkSniffer/IpSnifferRawSocketSingleInterface.cs#L44) and when parsing received packet - program buffer is 131072 bytes

**Comment by neowutran** [comment]
That should be fixed now. Maybe
Tell me if you see this bug again

**Comment by Kagashini** [comment]
I see this bug again. I think, need to reset the counter after 2-5 dungeons and save previous dungeons. I changed my 1 character to 2 character and meter stopped.

**Comment by neowutran** [comment]
Since I m not able to see this bug on my computer, I will add one messagebox for the next release. If that messagebox show up and the dps meter stop recording, that would mean I found out at what line the problem is. But that will take me more time to understand how to fix it ^^

**Comment by neowutran** [comment]
messagebox added with 0.71. Tell me if when the dps stop recording you see a messagebox. This information will help me to debug

**Comment by neowutran** [comment]
I think I can close that, never seen that problem again
