### ISSUE TITLE
Boss mechanics events?

### ISSUE THREAD

**Issue by FalcorPIX** [neowutran/ShinraMeter#391]
is it possible to do an event when a certain boss mechanic happens, for example:

On LK when pyrepelt targets a player and they have to run away to put the puddle as far as possible. Is it possible to create an event when the boss targets me with that mechanic and there is a sound or text to speech for me to run away.

when im DPSing i never notice those notifications so a sound would be nice

**Comment by SaltyMonkey** [comment]
Mechanics in dungeons - main part of game (and big part of game). Your dps and dungeon time can show not only your ingame items, but also the general skill and knowledge of the mechanic. Next step - full dungeon guide from Shinra? Or automatic bot?

**Comment by FalcorPIX** [comment]
i understanding what you saying, but it producing a sound for a mechanic in addition to its text its not a big deal, its not like it is telling me something i had no other way of knowing

**Comment by neowutran** [comment]
Technically possible ofc, but that is a bit "crossing the line" IMO
So, won't do that ^^ & if it s related to a buff/debuff/any abnormality, you can already do it with the existing event system
