### ISSUE TITLE
increase volume

### ISSUE THREAD

**Issue by aPsyXeran** [neowutran/ShinraMeter#393]
and although there is a possibility to make the voice louder z.b. If you are being tempted, it would be great who you could help me with

**Comment by SaltyMonkey** [comment]
https://github.com/neowutran/ShinraMeter/wiki/Events

**Comment by aPsyXeran** [comment]
thx

**Comment by aPsyXeran** [comment]
have now set but still totally silent here times the config

[http://textuploader.com/dljzs](url)

**Comment by Gl0** [comment]
Increase volume of "totally silent"  = "totally silent".
Probably you have no appropriate voice pack installed in your windows.
You should either install it or change config to point to exact voice that is already installed, including all parameters (for example: `voice_gender="Female" voice_age="Adult" culture="en-US" voice_position="0" volume="100" rate="0""`)
