### ISSUE TITLE
Fight timer

### ISSUE THREAD

**Issue by Lancerleague** [neowutran/ShinraMeter#395]
"V2.17.9da854b:

Fix some issue with packets logs
Start fight timer on aggro OR on first hit"

Actually the fight timer starts counting right after someone pulled agro from the boss. On this patch note it says: **"Start fight timer on aggro OR on first hit"** Well but i cant find any option where i can change this setting. I´d really love to change it on counting on first hit, because otherwise, its really hard to keep track with the lancers in the top-rankings, that were stacking their buff before the timer started counting. Its a huge difference, starting the boss with 10 or 0 block-stacks as a lancer, what kinda makes the ranking unfair. Therefore i´d love to have a button to change that setting or to get the "start counting fight timer on first hit" back again as a basic setting. Thank you in advance!

**Comment by Gl0** [comment]
We will, probably, add such option, but moongourd will refuse logs collected with that setting active.

**Comment by Lancerleague** [comment]
But what about the runs that are already posted on Moongourd from Lancers, that already did their fights with stacking before the time started counting? Its barely impossible to do that starting with 0 stacks.

**Comment by acsi2** [comment]
Exactly, what about the runs that are already posted? How are people supposed to outrank anyone that got their score starting the boss with 10 stacks? The top scores will remain top forever, since the difference is huge. Its extremely unfair. Either reset the ranks in moongourd or make reverse the change on meter.

**Comment by neowutran** [comment]
The option have been added to switch between aggro & first hit for the UI only
For the existing logs, check with Teri
& If you want to have a website with the run based on first it: build it, meter can export both logs
