### ISSUE TITLE
advanced autoinspect with moongourd data

### ISSUE THREAD

**Issue by dzonygate** [neowutran/ShinraMeter#398]
One of best features of Shinra meter is autoinspect (puting /inspect player.name to clipboard). I made a little tool to parse info from moongourd based on this clipboard entry. It would be nice if something similar was implemented to shinra meter. This is how mine looks like : https://i.imgur.com/w6FUEJ3.png It simply creates windows tooltip showing info from RK9 normal and hard.

**Comment by neowutran** [comment]
Interesting idea ^^
Idk if I will implement that, but interesting idea

**Comment by neowutran** [comment]
Something similar have been implemented in TCC
