### ISSUE TITLE
Volume request

### ISSUE THREAD

**Issue by Caerninchen** [neowutran/ShinraMeter#399]
hay, can you guys may add an volume option for the enrange voice-noticifation? I like it but sometimes it's to low, so that i miss to hear it at time. And my Windows Soundmixer didn't show Shinrameter Volume to set it.

 Would be great <3

**Comment by Gl0** [comment]
https://github.com/neowutran/ShinraMeter/wiki/Events#text-to-speech

**Comment by Caerninchen** [comment]
can i set it for enrage the same? or ist this sample for borh - begining and ending?
