### ISSUE TITLE
[Request] Bosses history

### ISSUE THREAD

**Issue by Casanova** [neowutran/ShinraMeter#40]
Hi,

I see that the DPS meter allows to see the history of the previous fights, may that be Vs a boss or not. And the DPS meter already knows the difference between a boss and non-boss fight.

Is it possible to add a parameter in the configuration file, to tell the DPS meter to only saves boss fights?

Thanks in advance for the answer.

Kind regards,

Casanova

**Comment by neowutran** [comment]
ok for that

**Comment by neowutran** [comment]
v0.92
