### ISSUE TITLE
Shinra crashes and I get a black screen

### ISSUE THREAD

**Issue by Syphiria** [neowutran/ShinraMeter#401]
Hello,
I downloaded the latest version of Shinra Meter and Npcap. It works in the game, but it always crashes and I get a black screen for a few seconds and then I see the Desktop, so I have to Alt+Tab to get back into the game. I added Shinra to the exceptions of the firewall and the "error" file is empty.
Should I try changing the resolution? I'm actually playing in Windowed (full screen), maybe that's the problem?

**Comment by Gl0** [comment]
Sounds like video card/drivers issue.

**Comment by Syphiria** [comment]
I am actually using an AMD Radeon R7 370 Series. I have the latest version drivers (17.11.2).
What should I do?

**Comment by neowutran** [comment]
Update to the latest windows version, check gpu driver update. You can try to disable transparency support in the settings 
https://github.com/neowutran/ShinraMeter/wiki#streaming
