### ISSUE TITLE
Enrage status "damage" crits and skews crit rate

### ISSUE THREAD

**Issue by Seeohelaien** [neowutran/ShinraMeter#402]
Using shinra meter V2.23 (.e218f4f)
I noticed that it is possible to get over 100% crit rate on really short fights such as vs bloodbound teraliths (sub ilvl 439 island of dawn BAMs).

Having done 5 hits (all crits) the meter was somehow showing me 120% crit rate.
Looking into the skills window it would appear that the teraliths enrage did 1 damage?
Which I inflicted?
Which also crited?

Not sure if this is a Shinra meter thing or if that enrage status is supposed to do 0 damage but instead did 1 damage because it critted which it may not be supposed to...?
But it wasn't being counted as a used skill but did count towards the crit tottal... i guess?

![shinrameterbug](https://user-images.githubusercontent.com/14126356/33292790-c0dc80dc-d3ca-11e7-8b52-157e72473981.PNG)

**Comment by Gl0** [comment]
already [fixed](https://github.com/neowutran/ShinraMeter/commit/fe09b9ddf2c492c68432738c6bf929550b614723)
