### ISSUE TITLE
can't install shinra cause of .net4.7

### ISSUE THREAD

**Issue by tortellos** [neowutran/ShinraMeter#405]
hi guys there is a way to install shinrameter without .net 4.7, i've windows10 but my update are blocked so i can't install the meter...ty in advance

**Comment by neowutran** [comment]
Hi 
not possible. You can use casual meter instead or some alternative to shinrameter ^^

**Comment by tortellos** [comment]
is casual meter a good meter or should i use something other?

**Comment by neowutran** [comment]
Ya, it's a good meter, try it

**Comment by Gl0** [comment]
note that it has outdated tera.core.dll now, that need to be replaced by the one from latest shinra

**Comment by tortellos** [comment]
oh well but where can i found the last tera.core.dll of shinra?

**Comment by Gl0** [comment]
https://neowutran.ovh/updates/ShinraMeterV/Tera.Core.dll.zip
That url may be changed later if we change file layout for shinra

**Comment by tortellos** [comment]
ok i installed casual meter but now where should i put this file? (sry for the question but i'm a noob)

**Comment by Gl0** [comment]
`%localappdata%/CasualMeter/<version>`

**Comment by tortellos** [comment]
ok did everything and it work ty for your help, really appreciate it
