### ISSUE TITLE
Disable enrage popups

### ISSUE THREAD

**Issue by FusenSho** [neowutran/ShinraMeter#406]
Hey its not an issue but could you tell me a way to disable the popups only for enrage and disenrage please?

**Comment by neowutran** [comment]
File SHINRA_FOLDER/resources/config/events/events-common.xml 

Remove the popup for enrage & disenrage : 
Remove this line https://github.com/neowutran/ShinraMeter/blob/master/Lang/Resources/en/events-common.xml#L21 
And this line https://github.com/neowutran/ShinraMeter/blob/master/Lang/Resources/en/events-common.xml#L47

**Comment by FusenSho** [comment]
Would:

	
	<abnormality **active="false"** ingame="true" trigger="Added" target="Boss">
		<abnormalities>
			<abnormality>8888888</abnormality>
		</abnormalities>
		<actions>
			<notify>
				<balloon title_text="{abnormality_name} : on" body_text="{abnormality_name}" display_time="3000" />
				<beeps>
					<beep frequency="185" duration="500"/>
				</beeps>
			</notify>
		</actions>
	</abnormality>

Solve the problem aswel?

**Comment by neowutran** [comment]
putting "active" to false would also disable the beeps

**Comment by FusenSho** [comment]
great :D I mutet shinra anyways :)
