### ISSUE TITLE
Glyph Build Not Uploading

### ISSUE THREAD

**Issue by chachabsc** [neowutran/ShinraMeter#408]
I have the game open and the meter up, but when I press upload glyph build on the shinra configurations, nothing happens. I check moongourd and I still can't register my character, nothing comes up. I have the Shinra v2.28.96 Please help ;(

**Comment by neowutran** [comment]
You configured the meter with your moongourd token?

**Comment by ve3k** [comment]
I've noticed same issue yesterday, but didn't give it much thought.
I will refresh the moongourd config and retry today.

**Comment by Gl0** [comment]
config can be wiped only if it is corrupted. I'm that case not only moongourd settings are gone, but all window.xml is recreated with defaults. And it should have nothing to do with updates.
