### ISSUE TITLE
[Request] Data Export

### ISSUE THREAD

**Issue by Casanova** [neowutran/ShinraMeter#41]
Hi,

An other request (Again :p)

As said in the title, I'd like to be able to export the DPS meter data to Excel, so CSV file should be enough.

The purpose is to allow a better data collection, for statistical purposes.

The export could trigger multiple CSV files creation, one containing the first screen data, meaning 8 columns: 
{class};{name};{damage_percentage};{crit_rate};{Crit};{dps};{hits_received};{damage_received}.
The other extracts could come later and they would contain a file per each dps meter screen.

Kind regards,

Casanova

**Comment by neowutran** [comment]
Hi again =) 
Data export is already planned, but I intend to export everything in JSON. anyway json <--> CSV is not really a problem.
The final goal will be to be able to generate web chart like this: https://jsfiddle.net/api/post/library/pure/ .
I don't intend to release data export before few weeks

**Comment by Casanova** [comment]
Hi,

The charts idea seems very interesting! :+1: 
It's also useful to have the raw data to be able to compile many fights for statistics :) 
As for the format JSON or CSV, it doesn't matter, as long as it could be put in a table in order to calculate averages ^_^

**Comment by Casanova** [comment]
**Subject:** Functional Specifications
**Warning:** TEXT WALL :p

Hi,

Here is my attempt to clarify the idea I have in mind :)

• The new functionality extract the data that is already accessible via UI.
• The new functionality will be triggered via a button in the UI,
• This button will have a built-in cool down of 1 sec
• The button turns to a different color once clicked, for a fight. When there is an other fight (new or history), the button color reset.
• The extracted files can be used in spreadsheet program.
• The data extracts will be sent to a folder, the path of this folder can be set in a configuration file (_optional_).
• Every extract will create many files of the following format: DataType_YYYYMMDDHHMMSS (that's why there is a 1 second CD on the button),
• The types are:
  + Fight_Summary: The main screen (damage dealt, damage taken...etc),
  + Fight_Debuffs: The debuff screen,
  + Fight_....: Any other general fight data,
  + [Player_x]_Damage: The detailed skills page, where [Player_x] is the actual name of the player,
  + [Player_x]_Heals: Same for heals,
  + [Player_x]_Mana: Same,
  + [Player_x]_buffs: Same,
  + ... etc: in case I missed any other screen.

I hope it will be clear when you'll have time for it.

Many thanks,

Casanova

**Comment by neowutran** [comment]
Export to Json object have been done (sending data to teradps.io). 
Export to file is trivial now, will be added soon

**Comment by Casanova** [comment]
AMAZING! :+1:

Looking forward to it :)

**Comment by neowutran** [comment]
v0.92 => excel export

**Comment by Casanova** [comment]
How can we launch the export? and what are the new buttons? I can't find them on the wiki page.

**Comment by Gl0** [comment]
Edit window.xml `<excel>true</excel>`

**Comment by Gl0** [comment]
buttons are for chat and boss history

**Comment by neowutran** [comment]
(yup, haven't wrote the "tuto" on the wiki yet, do what Gl0 say & you will see the excel files in ./resources/logs/xxxxxxx)

**Comment by Gl0** [comment]
May be add it as context menu item switch?

**Comment by neowutran** [comment]
hum, yup ^^ will add that

**Comment by Gl0** [comment]
Added myself. =)

**Comment by Casanova** [comment]
Thanks for the explanation, it's working for me :+1:  :)
