### ISSUE TITLE
[Request] Bravery and Canephora warnings

### ISSUE THREAD

**Issue by Mkalo** [neowutran/ShinraMeter#410]
Much like the nostrum warning, send notification whenever bravery or canephora is ending (not if its missing unlike nostrum).

**Comment by neowutran** [comment]
You can configure it
https://github.com/neowutran/ShinraMeter/wiki/Events

**Comment by ve3k** [comment]
<abnormality ingame="true" remaining_seconds_before_trigger="10" rewarn_timeout_seconds="3" trigger="MissingDuringFight" target="Self" priority="2">
        <abnormalities>
            <abnormality>920</abnormality>
            <abnormality>921</abnormality>
            <abnormality>922</abnormality>
        </abnormalities>
        <actions>
            <notify>
                <balloon title_text="Noctenium missing" body_text="{player_name} {time_left}" display_time="3000" />
            </notify>
        </actions>
    </abnormality>

    
    <abnormality ingame="true" remaining_seconds_before_trigger="10" rewarn_timeout_seconds="3" trigger="MissingDuringFight" target="Self" priority="1">
        <abnormalities>
            <abnormality>4830</abnormality>
            <abnormality>4831</abnormality>
            <abnormality>4832</abnormality>
            <abnormality>4833</abnormality>
            <abnormality>4841</abnormality>
            <abnormality>4886</abnormality>
            <abnormality>4861</abnormality>
            <abnormality>4953</abnormality>
            <abnormality>4955</abnormality>
            <abnormality>2103</abnormality>
        </abnormalities>
        <actions>
            <notify>
                <balloon title_text="Bravery/Canephora" body_text="{player_name} {time_left}" display_time="3000" />
            </notify>
        </actions>
    </abnormality>

**Comment by f3ck4r** [comment]
why is not working?!


	<cooldown ingame="true" active="true" skill_id="700100">
		<actions>
                       <notify>
	                  <balloon title_text="{skill_name} reset" body_text="{skill_name}" display_time="3000 />
                       </notify>
		</actions>
     </cooldown>

**Comment by Gl0** [comment]
there is no skill with id 700100...

**Comment by f3ck4r** [comment]
vow of rebirth?

**Comment by Gl0** [comment]
You are messing skills with buffs.

**Comment by f3ck4r** [comment]
where can i look for skill id?
It seems those are glyph id

**Comment by Gl0** [comment]
that skill can't be reset - you can only track if you have that buff or not. (Or have it ending in x seconds, which would be most close to cooldown tracking)

**Comment by f3ck4r** [comment]
OK!
thank you!

**Comment by ve3k** [comment]
@f3ck4r 
here is my events file shared for fellow mystic :)
pick w/e you like from it
[events-mystic.txt](https://github.com/neowutran/ShinraMeter/files/1795791/events-mystic.txt)
