### ISSUE TITLE
Instantaneous DPS or DPS in a short time interval

### ISSUE THREAD

**Issue by aurelius88** [neowutran/ShinraMeter#411]
Hi there,
Shinra Meter is nice to find out a way to maximize your dps and analyze your skills. But there has been always something I was missing: An instantaneous dps. Shinra Meter is only showing you an average dps over the whole fight. So - also you wouldn't do this - if you have something like a brake while you are still in a fight (e.g. kiting the boss), you loose dps for doing nothing. But you can't tell afterwards if you was better or worse than another fight without a brake.

This is when instantaneous dps comes in play. It does not look for the whole fight, but for a short time period or to be exactly for a specific point in time. So you can still see if you are doing well or not. Of course there is a disadvantage comparing with the average dps. The average dps is just one value. Instantaneous dps would be several values over the whole fight. To be exactly, it is the derivation of the function that discribes the damage done for a specific time. Because I think you are just using simple calculation, it might be difficult to realize.

So to simplify it, you could just take the dps over a short time interval. The interval can be variable. E.g. starting from 2s to a maximum of 10s. Let's say the we set the value to 2s. The pseudo instantaneous dps would show the dps for the last 2s.
Instantaneous dps or the pseudo instantaneous dps would als help tanks to see, when they are about to loose aggro and react before it happens.
And you could also draw it in a graph to show when dps was well or worse. Helping to further optimize the class in terms of dps. But this could be a seperate request.

**Comment by Gl0** [comment]
You can set `Excel: calc moving average DPS for X seconds` to 2-10 (as you want), export to excel and look at the sheet after the fight to see that info.

**Comment by aurelius88** [comment]
Thanks for that, but still it would be better to have it in real time. Additionaly, I can't see afterwards which skill resulted into that dps peek, because there is no skill to time list in the exported sheet.
Only if I still got the data on shinra meter, I can compare the "SkillDealt" list with that graph from excel sheet. But already deleted data cannot be compared.

So this request is for a real time display of something like instantaneous dps.

**Comment by bigworld12** [comment]
@aurelius88 updating UI on packet received can be a huge overhead, imagine each player doing average 6 hits/second and you have 5 players = 30 UI updates per second, which will consume unnecessary cpu usage, rather than 1 UI update per second

**Comment by aurelius88** [comment]
@bigworld12 
> @aurelius88 updating UI on packet received can be a huge overhead [...]

That's absolutely right, but you must have missunderstood. I never said to update UI on each packet received. I just said to also calculate the "instantaneous dps" or the pseudo version of it and display it on the damage meter. The UI can still stay on 1 UI update per second or however it is configured to.

**Comment by neowutran** [comment]
done by @Foglio1024
