### ISSUE TITLE
Shinrameter crashing after start (2.17)

### ISSUE THREAD

**Issue by doesthatmatter** [neowutran/ShinraMeter#412]
Hi, I wanted to use this DPS meter but I have this problem :/
Error log:

2018-02-05 12:25:02,876 [1] WARN  NetworkSniffer.IpSnifferWinPcap [(null)] - Failed to open device rpcap://\Device\NPF_{78032B7E-4968-42D3-9F37-287EA86C0AAA}. Unable to open the adapter (rpcap://\Device\NPF_{78032B7E-4968-42D3-9F37-287EA86C0AAA}). rpcap://\Device\NPF_{78032B7E-4968-42D3-9F37-287EA86C0AAA}: failed to set hardware filter to non-promiscuous mode
2018-02-05 12:28:29,228 [24] ERROR ShinraMeter [(null)] - Unknown client version: 326439
2018-02-05 12:28:44,562 [7] ERROR ShinraMeter [(null)] - ##### CRASH #####
Se produjo una excepción en el destino de la invocación.
   en System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   en System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   en System.Delegate.DynamicInvokeImpl(Object[] args)
   en DamageMeter.PacketProcessingFactory.Process(ParsedMessage message)
   en DamageMeter.NetworkController.PacketAnalysisLoop()
   en System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   en System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.Reflection.TargetInvocationException: Se produjo una excepción en el destino de la invocación. ---> System.IO.FileNotFoundException: No se pudo encontrar el archivo 'C:\Program Files (x86)\ShinraMeterV2.17\resources\data\opcodes\326439.txt'.
   en System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   en System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   en System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   en System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   en System.IO.StreamReader..ctor(String path, Encoding encoding)
   en System.IO.File.ReadLines(String path)
   en Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename)
   en DamageMeter.Processing.C_CHECK_VERSION..ctor(C_CHECK_VERSION message)
   en lambda_method(Closure , C_CHECK_VERSION )
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   en System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   en System.Delegate.DynamicInvokeImpl(Object[] args)
   en DamageMeter.PacketProcessingFactory.Process(ParsedMessage message)
   en DamageMeter.NetworkController.PacketAnalysisLoop()
   en System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   en System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal
System.IO.FileNotFoundException: No se pudo encontrar el archivo 'C:\Program Files (x86)\ShinraMeterV2.17\resources\data\opcodes\326439.txt'.
Nombre de archivo: 'C:\Program Files (x86)\ShinraMeterV2.17\resources\data\opcodes\326439.txt'
   en System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   en System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   en System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   en System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   en System.IO.StreamReader..ctor(String path, Encoding encoding)
   en System.IO.File.ReadLines(String path)
   en Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename)
   en DamageMeter.Processing.C_CHECK_VERSION..ctor(C_CHECK_VERSION message)
   en lambda_method(Closure , C_CHECK_VERSION )
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

What do I have to do?
Thanks

**Comment by Gl0** [comment]
Update meter

**Comment by doesthatmatter** [comment]
What's the lastest version? I though that 2.17 was the lastest one :/

**Comment by Gl0** [comment]
2.30, just allow auto update

**Comment by doesthatmatter** [comment]
Oh, thank you! ^^
