### ISSUE TITLE
Archers Velik Mark debuff

### ISSUE THREAD

**Issue by oversharegit** [neowutran/ShinraMeter#415]
Hello, is there any way to implement a check on velik mark debuff from archers, like what happens in other classes debuffs?

Regards

**Comment by Gl0** [comment]
isn't it already implemented?

**Comment by oversharegit** [comment]
It doesn't work for me, doesn't also warn the snipers self-buff... is there a way to implement it?

**Comment by Gl0** [comment]
https://github.com/neowutran/ShinraMeter/wiki/Events
