### ISSUE TITLE
Fullscreen Overlay stops counting

### ISSUE THREAD

**Issue by Shrubbity** [neowutran/ShinraMeter#418]
The stats still work if I do Shift + End I think though they have been messed up before.

Sometimes when I reset the stats with delete it spams me with random voice clips, like 'enrage' over and over again.

I swear my Shinra doesn't work correctly :/ I don't know what to do though. I've downloaded all the prerequisites, reinstalled npcap etc. And tried high priority mode in window.xml

I'm on windows 7.

**Comment by Shrubbity** [comment]
`2018-04-06 16:04:34,342 [1] WARN  NetworkSniffer.IpSnifferWinPcap [(null)] - Failed to open device rpcap://\Device\NPF_{78032B7E-4968-42D3-9F37-287EA86C0AAA}. Unable to open the adapter (rpcap://\Device\NPF_{78032B7E-4968-42D3-9F37-287EA86C0AAA}). rpcap://\Device\NPF_{78032B7E-4968-42D3-9F37-287EA86C0AAA}: failed to set hardware filter to non-promiscuous mode
2018-04-08 13:07:15,263 [1] WARN  NetworkSniffer.IpSnifferWinPcap [(null)] - Failed to open device rpcap://\Device\NPF_{78032B7E-4968-42D3-9F37-287EA86C0AAA}. Unable to open the adapter (rpcap://\Device\NPF_{78032B7E-4968-42D3-9F37-287EA86C0AAA}). rpcap://\Device\NPF_{78032B7E-4968-42D3-9F37-287EA86C0AAA}: failed to set hardware filter to non-promiscuous mode`

There are only two entries however, and I do think it has been happening more frequently than those two entries suggest. Yes I am using TERA proxy. I did try and look for some info on using them together but couldn't find anything, maybe my bad.

**Comment by Gl0** [comment]
try setting allow_transparency = false in window.xml

**Comment by Shrubbity** [comment]
I even clean installed to Windows 10 from Windows 7 and it still occurs every now and then (on a side note the fullscreen UI works properly now, notifications don't glitch through like on W7 and it looks good, so great job!). I wonder if it's something to do with proxy though.

**Comment by Shrubbity** [comment]
One possibility is the fact that my CMOS battery is clearly on its way out, since it can't hold a time. I wonder if this might cause the issue. Ordered a new one.
