### ISSUE TITLE
Ruinous Manor S2 (Hard) - First boss is not uploaded

### ISSUE THREAD

**Issue by VenoMKO** [neowutran/ShinraMeter#419]
Shinra version: 2.39.723449d
Region: RU
The error log is spammed with:
```
2018-05-05 00:56:10,615 [6] ERROR ShinraMeter [(null)] - PacketExport: Start
2018-05-05 00:56:10,616 [6] ERROR ShinraMeter [(null)] - PacketExport: Boss not allowed, exiting
```
[Second boss upload](https://moongourd.com/ru/encounter?area=970&boss=2001&log=5aecc6aae93d5)
[Third boss upload](https://moongourd.com/ru/encounter?area=970&boss=3001&log=5aeccbced8b2f)

Whole party tried to upload the run but no success.

**Comment by Gl0** [comment]
packet export has nothing with moongourd export.
To see why your upload is rejected - open site export history window from cogweel button context menu and hover mouse over boss name.

**Comment by VenoMKO** [comment]
Server error or timeout. I don't thinks it's a problem with with network coz like i said i am not the only one with this problem

**Comment by Gl0** [comment]
"Server error or timeout" means that either server returned something unpredictable or there were http error while uploading. If you see that reason you can try to press manual upload button after a while and it should be uploaded fine.
