### ISSUE TITLE
How to turn it on.

### ISSUE THREAD

**Issue by shine223** [neowutran/ShinraMeter#42]
Hello, i downlaoded metter, WinPcap, and how do i turn metter on now?

**Comment by neowutran** [comment]
read that: https://github.com/neowutran/ShinraMeter/wiki#network

Launch the dps meter, then launch the game and that should work fine

**Comment by shine223** [comment]
Yes , thats the problem, how could i launch it? i launch ''Tera.DamageMeter*****'' and it says me to select program.

**Comment by neowutran** [comment]
run "ShinraMeter.exe"
https://github.com/neowutran/ShinraMeter/wiki#download

**Comment by shine223** [comment]
its not there, could it be that antivirus deleted it?

**Comment by neowutran** [comment]
possible

**Comment by shine223** [comment]
Fixed, works. It was antivirus. Ty.
