### ISSUE TITLE
Shinra crashes and Tera alt-tabs itself

### ISSUE THREAD

**Issue by Syphiria** [neowutran/ShinraMeter#420]
Hello. This issue is going on since i downloaded Shinra months ago and I always had this problem.
I activate it before logging on Tera, I play normally and when I'm in dungeon I get a black screen for one or two seconds, I find myself in another page (Internet, Spotify or whatever is going in background), and after 2-3 seconds it comes back on Tera. During this time I keep hearing Tera sounds but I can't move or alt-tab in Tera manually and I have to wait. I stay still in game for 5 or more seconds and Shinra crashes.
I tried with fullscreen (actually I play in fullscreen windowed) and my graphic card (AMD) is at its last version.
I try to close every other program not related to Tera when I play, except for Spotify/iTunes, so I'm sure that there are no problems between Shinra and something else.

**Comment by Gl0** [comment]
What's in error.log/ windows error log?
Looks like some GPU issue with driver restart.

**Comment by Syphiria** [comment]
There's nothing, it's empty.
Shinra is still active but doesn't respond and I have to close it with the task manager.

**Comment by Gl0** [comment]
Again, looks like GPU fault. Seems game can recover from that, mater - not...

**Comment by neowutran** [comment]
Cannot be fixed, closing
