### ISSUE TITLE
Fatal Error after launching Tera

### ISSUE THREAD

**Issue by jacek257** [neowutran/ShinraMeter#425]
After launching Tera, ShinraMeter terminates with fatal error. Error persists after fresh install of program.
[error.log](https://github.com/neowutran/ShinraMeter/files/2103576/error.log)

**Comment by Gl0** [comment]
should be fixed in 2.44

**Comment by jacek257** [comment]
thank you, about when will 2.44 come out?

**Comment by Gl0** [comment]
already out
