### ISSUE TITLE
Meter doesn't work

### ISSUE THREAD

**Issue by RWingel** [neowutran/ShinraMeter#428]
After Dreadspire patch the dps meter just stopped showing anything. Autoupdate doesn't work either I think. 

[error.log](https://github.com/neowutran/ShinraMeter/files/2190473/error.log)

**Comment by Gl0** [comment]
Reinstall npcap. Autoupdate is not working now (problems with update server), but meter should still work (without new skill/buff/monster names).

**Comment by RWingel** [comment]
Didn't work, still getting the same error. :<

**Comment by Gl0** [comment]
then try switching to raw sockets

**Comment by RWingel** [comment]
Not working, but without error this time. (yes, I used the firewall .bat)

**Comment by Gl0** [comment]
That's not really an error, that's just a warning that not all of your network adapters can be used to capture game traffic.
If meter was working earlier via npcap - try to uninstall it, reboot, install and reboot again. Sometimes it can help if something is going wrong with npcap after windows update.
Raw sockets require not only firewall rule, but change in window.xml too. (both should be done in correct copy of meter).

**Comment by RWingel** [comment]
Nice, that one reboot between un- and reinstalling made the difference. Meter is working fine now, ty :D
