### ISSUE TITLE
Ctr+Del bug

### ISSUE THREAD

**Issue by Kagashini** [neowutran/ShinraMeter#43]
Hello!
`2016-02-19 22:11:34,875 [1] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### CRASH (version=0.67): #####
Адресат вызова создал исключение.
   в System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   в System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   в System.Delegate.DynamicInvokeImpl(Object[] args)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.DispatcherOperation.InvokeImpl()
   в System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Windows.Threading.DispatcherOperation.Invoke()
   в System.Windows.Threading.Dispatcher.ProcessQueue()
   в System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   в System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   в System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   в System.Windows.Application.RunDispatcher(Object ignore)
   в System.Windows.Application.RunInternal(Window window)
   в System.Windows.Application.Run(Window window)
   в DamageMeter.UI.App.Main()
mscorlib
System.Reflection.TargetInvocationException: Адресат вызова создал исключение. ---> System.Collections.Generic.KeyNotFoundException: Данный ключ отсутствует в словаре.
   в System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   в DamageMeter.UI.EntityStats.EntityStatsMain.Update(Dictionary`2 stats)
   в DamageMeter.UI.MainWindow.<Update>b__24_0(Int64 firstHit, Int64 lastHit, Int64 totalDamage, Dictionary`2 entities, List`1 stats, Entity currentBoss)
   --- Конец трассировки внутреннего стека исключений ---
   в System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   в System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   в System.Delegate.DynamicInvokeImpl(Object[] args)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.DispatcherOperation.InvokeImpl()
   в System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Windows.Threading.DispatcherOperation.Invoke()
   в System.Windows.Threading.Dispatcher.ProcessQueue()
   в System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   в System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   в System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   в System.Windows.Application.RunDispatcher(Object ignore)
   в System.Windows.Application.RunInternal(Window window)
   в System.Windows.Application.Run(Window window)
   в DamageMeter.UI.App.Main()
System.Collections.ListDictionaryInternal
System.Collections.Generic.KeyNotFoundException: Данный ключ отсутствует в словаре.
   в System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   в DamageMeter.UI.EntityStats.EntityStatsMain.Update(Dictionary`2 stats)
   в DamageMeter.UI.MainWindow.<Update>b__24_0(Int64 firstHit, Int64 lastHit, Int64 totalDamage, Dictionary`2 entities, List`1 stats, Entity currentBoss)
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
`

**Comment by Gl0** [comment]
[This line](https://github.com/neowutran/ShinraMeter/blob/74df8857515923633123688af3bb8290143aff21/DamageMeter.UI/MainWindow.xaml.cs#L275)
should be moved after [this](https://github.com/neowutran/ShinraMeter/blob/74df8857515923633123688af3bb8290143aff21/DamageMeter.UI/MainWindow.xaml.cs#L324)
to fix this error.

**Comment by Gl0** [comment]
Or better to do the opposite - move [second one](https://github.com/neowutran/ShinraMeter/blob/74df8857515923633123688af3bb8290143aff21/DamageMeter.UI/MainWindow.xaml.cs#L324) before [first one](https://github.com/neowutran/ShinraMeter/blob/74df8857515923633123688af3bb8290143aff21/DamageMeter.UI/MainWindow.xaml.cs#L275) 
as it was before [0.67](https://github.com/neowutran/ShinraMeter/commit/30f58c0a2772a1c4f1f0bd092eaee09e40930884)

**Comment by neowutran** [comment]
will fix that tomorrow. I don't have any computer able to compile the project right now.

**Comment by neowutran** [comment]
should be fixed
