### ISSUE TITLE
Was working before: ERROR ShinraMeter [(null)] - ##### CRASH #####

### ISSUE THREAD

**Issue by DaXmAn** [neowutran/ShinraMeter#430]
2018-07-14 14:18:35,273 [1] WARN  NetworkSniffer.IpSnifferWinPcap [(null)] - Failed to open device rpcap://\Device\NPF_{78032B7E-4968-42D3-9F37-287EA86C0AAA}. Unable to open the adapter (rpcap://\Device\NPF_{78032B7E-4968-42D3-9F37-287EA86C0AAA}). rpcap://\Device\NPF_{78032B7E-4968-42D3-9F37-287EA86C0AAA}: failed to set hardware filter to non-promiscuous mode
2018-07-14 14:21:37,756 [16] ERROR ShinraMeter [(null)] - ##### CRASH #####
Obiekt docelowy wywołania zgłosił wyjątek.
   w System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   w System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   w System.Delegate.DynamicInvokeImpl(Object[] args)
   w Tera.Game.MessageFactory.Instantiate(UInt16 opCode, TeraMessageReader reader)
   w Tera.Game.MessageFactory.Create(Message message)
   w DamageMeter.PacketProcessor.PacketAnalysisLoop()
   w System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   w System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.Reflection.TargetInvocationException: Obiekt docelowy wywołania zgłosił wyjątek. ---> System.IO.EndOfStreamException: Nie można odczytać danych spoza końca strumienia.
   w System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   w System.IO.BinaryReader.ReadUInt32()
   w Tera.Game.Messages.SPartyMemberChangeHp..ctor(TeraMessageReader reader)
   w lambda_method(Closure , TeraMessageReader )
   --- Koniec śladu stosu wyjątków wewnętrznych ---
   w System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   w System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   w System.Delegate.DynamicInvokeImpl(Object[] args)
   w Tera.Game.MessageFactory.Instantiate(UInt16 opCode, TeraMessageReader reader)
   w Tera.Game.MessageFactory.Create(Message message)
   w DamageMeter.PacketProcessor.PacketAnalysisLoop()
   w System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   w System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal
System.IO.EndOfStreamException: Nie można odczytać danych spoza końca strumienia.
   w System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   w System.IO.BinaryReader.ReadUInt32()
   w Tera.Game.Messages.SPartyMemberChangeHp..ctor(TeraMessageReader reader)
   w lambda_method(Closure , TeraMessageReader )
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

**Comment by Gl0** [comment]
delete ./resources/data/opcodes/protocol.333783.map and restart meter

**Comment by DaXmAn** [comment]
worked, thanks!
