### ISSUE TITLE
Meter doesn't work

### ISSUE THREAD

**Issue by doesthatmatter** [neowutran/ShinraMeter#432]
I can open the meter properly and it has been working fine until now. For some reason, it doesn't see any boss near me even when I hit it or my party does. It doesn't count dps and the hp bar won't show. I tried to see if it needed any update but everything seems okay, what can I do?

**Comment by Gl0** [comment]
update server is dead now, if you play NA - delete `./resources/data/opcodes/protocol.333782.map` and restart meter

**Comment by neowutran** [comment]
Update server is online again, closing
