### ISSUE TITLE
Meter does not work

### ISSUE THREAD

**Issue by primuskilli** [neowutran/ShinraMeter#433]
Int32 EndRead(System.IAsyncResult)
2018-07-22 11:00:25,011 [6] ERROR ShinraMeter [(null)] - ##### CRASH #####
IAsyncResult nesnesi bu türdeki ilişkili zaman uyumsuz metottan gelmedi veya EndRead aynı IAsyncResult ile birden çok kez çağrıldı.
   konum: System.IO.Stream.EndRead(IAsyncResult asyncResult)
   konum: System.IO.Pipes.PipeStream.EndRead(IAsyncResult asyncResult)
   konum: DiscordRPC.IO.ManagedNamedPipeClient.EndRead(IAsyncResult callback)
   konum: System.IO.Pipes.PipeStream.AsyncPSCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOverlapped)
   konum: System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
mscorlib
System.ArgumentException: IAsyncResult nesnesi bu türdeki ilişkili zaman uyumsuz metottan gelmedi veya EndRead aynı IAsyncResult ile birden çok kez çağrıldı.
   konum: System.IO.Stream.EndRead(IAsyncResult asyncResult)
   konum: System.IO.Pipes.PipeStream.EndRead(IAsyncResult asyncResult)
   konum: DiscordRPC.IO.ManagedNamedPipeClient.EndRead(IAsyncResult callback)
   konum: System.IO.Pipes.PipeStream.AsyncPSCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOverlapped)
   konum: System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
System.Collections.ListDictionaryInternal

That's the error message that I got. Can someone help me about my meter? I tried to download the fresh one but still it has the same error.

**Comment by neowutran** [comment]
Seems like discord RPC plugin error. 
Try disabling the plugin:
In ./resources/config/window.xml 
replace
```xml
<rich_presence><enabled>true</enabled>
```
by
```xml
<rich_presence><enabled>false</enabled>
```
