### ISSUE TITLE
Cooldown events bugged?

### ISSUE THREAD

**Issue by Lunaversitay** [neowutran/ShinraMeter#436]
Heyo,

I tried using the 0 wildcard along with events I found on (https://github.com/neowutran/TeraDpsMeterData/blob/master/skills/skills-NA.tsv) and none seemed to work for the cooldown event. (The code is the same on the wiki page https://github.com/neowutran/ShinraMeter/wiki/Events#cooldown-reset-event I just changed the skill_id to 0)

Little things people usually forget like saving the file wasn't an issue either, I changed something else in the same file to make sure everything was saved fine n' what not.

Also would it be possible to have a different method of before trigger to possibly remaining_seconds_**after**_trigger?

**Comment by neowutran** [comment]
Yes. 

You cannot set an event on natural cooldown. 
For the adrenalin rush, you can use some hacks for abnormality events like: 
Event for drenalin rush buff start, in the action you put something like that:
```xml
<beeps>
            <beep frequency="0" duration="15000"/>
            <beep frequency="185" duration="500"/>
</beeps>
``` 
beep frequency=0 means no sound. 
So this beep config is: 
Wait 15s, then do a beep. 

You can configure those 15s to be your cooldown

**Comment by Lunaversitay** [comment]
I'll give that trick a go, how possible would it be to see `remaining_seconds_after_trigger` possibly added for better prediction on nature skill cooldowns?

**Comment by Gl0** [comment]
May be we will add own skills natural cooldown notifications, but there is no way of accurate predicting other players cooldowns (depends on their gear and glyph build, which we can't get).

**Comment by Lunaversitay** [comment]
Yeah, I saw that being a problem, I'd be great if there was a way to detect natural cooldowns but I was thinking more or less using the predictions for personal use or just reminding people you're using x glyph if shared.
