### ISSUE TITLE
Windows Firewall Exceptions

### ISSUE THREAD

**Issue by redcrimsonmoon** [neowutran/ShinraMeter#438]
Is adding/deleting an exception truly safe for your computer? I just want to make sure as I want this meter, yet I do not know if there are risks to this.

**Comment by Gl0** [comment]
meter doesn't open any ports to listen, so there is no way to attack it remotely via allowed incoming connections.
You can use npcap (or even winpcap), which doesn't require setting up firewall exception. And this is recommended setup as it use less system resources to parse traffic.

**Comment by redcrimsonmoon** [comment]
Thank you very much for the reply. I'm quite a newbie at this, so I'm sorry for the questions. Do I just need to download NPCAP and it would work, or must I launch the program?

**Comment by Gl0** [comment]
npcap is network packet capture framework, it need to be installed, not just downloaded. Look at wiki for details about meter network configuration.

**Comment by redcrimsonmoon** [comment]
Thank you. I have one last question. Where can I find "WinpCap Compatible Mode" as the Home page states?

**Comment by Gl0** [comment]
in npcap installer

**Comment by redcrimsonmoon** [comment]
Alright, thank you very much for bearing with me. Have a nice day!
