### ISSUE TITLE
 0.67 crashes often

### ISSUE THREAD

**Issue by hap0328** [neowutran/ShinraMeter#44]
2016-02-19 19:24:09,853 [1] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### CRASH (version=0.67): #####
引動過程的目標傳回例外狀況。
   於 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   於 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   於 System.Delegate.DynamicInvokeImpl(Object[] args)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   於 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Windows.Threading.DispatcherOperation.Invoke()
   於 System.Windows.Threading.Dispatcher.ProcessQueue()
   於 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   於 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   於 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   於 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   於 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   於 System.Windows.Application.RunDispatcher(Object ignore)
   於 System.Windows.Application.RunInternal(Window window)
   於 System.Windows.Application.Run(Window window)
   於 DamageMeter.UI.App.Main()
mscorlib
System.Reflection.TargetInvocationException: 引動過程的目標傳回例外狀況。 ---> System.Collections.Generic.KeyNotFoundException: 指定的索引鍵不在字典中。
   於 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   於 DamageMeter.UI.EntityStats.EntityStatsMain.Update(Dictionary`2 stats)
   於 DamageMeter.UI.MainWindow.<Update>b__24_0(Int64 firstHit, Int64 lastHit, Int64 totalDamage, Dictionary`2 entities, List`1 stats, Entity currentBoss)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   於 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   於 System.Delegate.DynamicInvokeImpl(Object[] args)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   於 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Windows.Threading.DispatcherOperation.Invoke()
   於 System.Windows.Threading.Dispatcher.ProcessQueue()
   於 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   於 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   於 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   於 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   於 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   於 System.Windows.Application.RunDispatcher(Object ignore)
   於 System.Windows.Application.RunInternal(Window window)
   於 System.Windows.Application.Run(Window window)
   於 DamageMeter.UI.App.Main()
System.Collections.ListDictionaryInternal
System.Collections.Generic.KeyNotFoundException: 指定的索引鍵不在字典中。
   於 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   於 DamageMeter.UI.EntityStats.EntityStatsMain.Update(Dictionary`2 stats)
   於 DamageMeter.UI.MainWindow.<Update>b__24_0(Int64 firstHit, Int64 lastHit, Int64 totalDamage, Dictionary`2 entities, List`1 stats, Entity currentBoss)
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

**Comment by Gl0** [comment]
Duplicate, look [here](https://github.com/neowutran/ShinraMeter/issues/43#issuecomment-186470819).

**Comment by a0922171656** [comment]
thank you for your help

2016-02-19 19:59:43,341 [1] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### CRASH (version=0.67): #####
引動過程的目標傳回例外狀況。
   於 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   於 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   於 System.Delegate.DynamicInvokeImpl(Object[] args)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   於 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Windows.Threading.DispatcherOperation.Invoke()
   於 System.Windows.Threading.Dispatcher.ProcessQueue()
   於 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   於 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   於 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   於 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   於 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   於 System.Windows.Application.RunDispatcher(Object ignore)
   於 System.Windows.Application.RunInternal(Window window)
   於 System.Windows.Application.Run(Window window)
   於 DamageMeter.UI.App.Main()
mscorlib
System.Reflection.TargetInvocationException: 引動過程的目標傳回例外狀況。 ---> System.Collections.Generic.KeyNotFoundException: 指定的索引鍵不在字典中。
   於 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   於 DamageMeter.UI.EntityStats.EntityStatsMain.Update(Dictionary`2 stats)
   於 DamageMeter.UI.MainWindow.<Update>b__24_0(Int64 firstHit, Int64 lastHit, Int64 totalDamage, Dictionary`2 entities, List`1 stats, Entity currentBoss)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   於 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   於 System.Delegate.DynamicInvokeImpl(Object[] args)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   於 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Windows.Threading.DispatcherOperation.Invoke()
   於 System.Windows.Threading.Dispatcher.ProcessQueue()
   於 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   於 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   於 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   於 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   於 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   於 System.Windows.Application.RunDispatcher(Object ignore)
   於 System.Windows.Application.RunInternal(Window window)
   於 System.Windows.Application.Run(Window window)
   於 DamageMeter.UI.App.Main()
System.Collections.ListDictionaryInternal
System.Collections.Generic.KeyNotFoundException: 指定的索引鍵不在字典中。
   於 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   於 DamageMeter.UI.EntityStats.EntityStatsMain.Update(Dictionary`2 stats)
   於 DamageMeter.UI.MainWindow.<Update>b__24_0(Int64 firstHit, Int64 lastHit, Int64 totalDamage, Dictionary`2 entities, List`1 stats, Entity currentBoss)
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
2016-02-20 14:47:11,983 [1] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### CRASH (version=0.67): #####
引動過程的目標傳回例外狀況。
   於 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   於 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   於 System.Delegate.DynamicInvokeImpl(Object[] args)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   於 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Windows.Threading.DispatcherOperation.Invoke()
   於 System.Windows.Threading.Dispatcher.ProcessQueue()
   於 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   於 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   於 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   於 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   於 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   於 System.Windows.Application.RunDispatcher(Object ignore)
   於 System.Windows.Application.RunInternal(Window window)
   於 System.Windows.Application.Run(Window window)
   於 DamageMeter.UI.App.Main()
mscorlib
System.Reflection.TargetInvocationException: 引動過程的目標傳回例外狀況。 ---> System.Collections.Generic.KeyNotFoundException: 指定的索引鍵不在字典中。
   於 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   於 DamageMeter.UI.EntityStats.EntityStatsMain.Update(Dictionary`2 stats)
   於 DamageMeter.UI.MainWindow.<Update>b__24_0(Int64 firstHit, Int64 lastHit, Int64 totalDamage, Dictionary`2 entities, List`1 stats, Entity currentBoss)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   於 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   於 System.Delegate.DynamicInvokeImpl(Object[] args)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   於 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Windows.Threading.DispatcherOperation.Invoke()
   於 System.Windows.Threading.Dispatcher.ProcessQueue()
   於 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   於 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   於 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   於 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   於 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   於 System.Windows.Application.RunDispatcher(Object ignore)
   於 System.Windows.Application.RunInternal(Window window)
   於 System.Windows.Application.Run(Window window)
   於 DamageMeter.UI.App.Main()
System.Collections.ListDictionaryInternal
System.Collections.Generic.KeyNotFoundException: 指定的索引鍵不在字典中。
   於 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   於 DamageMeter.UI.EntityStats.EntityStatsMain.Update(Dictionary`2 stats)
   於 DamageMeter.UI.MainWindow.<Update>b__24_0(Int64 firstHit, Int64 lastHit, Int64 totalDamage, Dictionary`2 entities, List`1 stats, Entity currentBoss)
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
2016-02-20 15:34:08,804 [1] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### CRASH (version=0.67): #####
引動過程的目標傳回例外狀況。
   於 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   於 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   於 System.Delegate.DynamicInvokeImpl(Object[] args)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   於 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Windows.Threading.DispatcherOperation.Invoke()
   於 System.Windows.Threading.Dispatcher.ProcessQueue()
   於 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   於 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   於 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   於 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   於 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   於 System.Windows.Application.RunDispatcher(Object ignore)
   於 System.Windows.Application.RunInternal(Window window)
   於 System.Windows.Application.Run(Window window)
   於 DamageMeter.UI.App.Main()
mscorlib
System.Reflection.TargetInvocationException: 引動過程的目標傳回例外狀況。 ---> System.Collections.Generic.KeyNotFoundException: 指定的索引鍵不在字典中。
   於 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   於 DamageMeter.UI.EntityStats.EntityStatsMain.Update(Dictionary`2 stats)
   於 DamageMeter.UI.MainWindow.<Update>b__24_0(Int64 firstHit, Int64 lastHit, Int64 totalDamage, Dictionary`2 entities, List`1 stats, Entity currentBoss)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   於 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   於 System.Delegate.DynamicInvokeImpl(Object[] args)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   於 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Windows.Threading.DispatcherOperation.Invoke()
   於 System.Windows.Threading.Dispatcher.ProcessQueue()
   於 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   於 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   於 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   於 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   於 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   於 System.Windows.Application.RunDispatcher(Object ignore)
   於 System.Windows.Application.RunInternal(Window window)
   於 System.Windows.Application.Run(Window window)
   於 DamageMeter.UI.App.Main()
System.Collections.ListDictionaryInternal
System.Collections.Generic.KeyNotFoundException: 指定的索引鍵不在字典中。
   於 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   於 DamageMeter.UI.EntityStats.EntityStatsMain.Update(Dictionary`2 stats)
   於 DamageMeter.UI.MainWindow.<Update>b__24_0(Int64 firstHit, Int64 lastHit, Int64 totalDamage, Dictionary`2 entities, List`1 stats, Entity currentBoss)
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
2016-02-20 17:38:43,086 [1] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### CRASH (version=0.67): #####
引動過程的目標傳回例外狀況。
   於 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   於 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   於 System.Delegate.DynamicInvokeImpl(Object[] args)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   於 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Windows.Threading.DispatcherOperation.Invoke()
   於 System.Windows.Threading.Dispatcher.ProcessQueue()
   於 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   於 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   於 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   於 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   於 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   於 System.Windows.Application.RunDispatcher(Object ignore)
   於 System.Windows.Application.RunInternal(Window window)
   於 System.Windows.Application.Run(Window window)
   於 DamageMeter.UI.App.Main()
mscorlib
System.Reflection.TargetInvocationException: 引動過程的目標傳回例外狀況。 ---> System.Collections.Generic.KeyNotFoundException: 指定的索引鍵不在字典中。
   於 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   於 DamageMeter.UI.EntityStats.EntityStatsMain.Update(Dictionary`2 stats)
   於 DamageMeter.UI.MainWindow.<Update>b__24_0(Int64 firstHit, Int64 lastHit, Int64 totalDamage, Dictionary`2 entities, List`1 stats, Entity currentBoss)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   於 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   於 System.Delegate.DynamicInvokeImpl(Object[] args)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   於 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Windows.Threading.DispatcherOperation.Invoke()
   於 System.Windows.Threading.Dispatcher.ProcessQueue()
   於 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   於 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   於 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   於 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   於 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   於 System.Windows.Application.RunDispatcher(Object ignore)
   於 System.Windows.Application.RunInternal(Window window)
   於 System.Windows.Application.Run(Window window)
   於 DamageMeter.UI.App.Main()
System.Collections.ListDictionaryInternal
System.Collections.Generic.KeyNotFoundException: 指定的索引鍵不在字典中。
   於 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   於 DamageMeter.UI.EntityStats.EntityStatsMain.Update(Dictionary`2 stats)
   於 DamageMeter.UI.MainWindow.<Update>b__24_0(Int64 firstHit, Int64 lastHit, Int64 totalDamage, Dictionary`2 entities, List`1 stats, Entity currentBoss)
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
