### ISSUE TITLE
Crashed with my lan card

### ISSUE THREAD

**Issue by livingmonster** [neowutran/ShinraMeter#441]
I used to use shinrameter before while my computer while I used lan cable for the Internet.

However, after I installed a intel wireless lan card - AC9260, once i open shinrameter, the network will stop working and I need to reboot my computer.

Furthermore, this also happens when I use Tera-custom-cooldowns.

Is there any cue for this issue? 

Thank you.

**Comment by Gl0** [comment]
try installing latest version of npcap, if it would behave the same - send bugreport to npcap team and switch to raw sockets (see wiki for details)
