### ISSUE TITLE
Double meter?

### ISSUE THREAD

**Issue by doesthatmatter** [neowutran/ShinraMeter#445]
For some reason this second meter I can't move or make disappear appeared in the top left of my screen, and it kinda bothers me.
![image](https://user-images.githubusercontent.com/36164267/44683341-785d8080-aa1c-11e8-967e-5af442a27241.png)
How can I make it disappear?

**Comment by neowutran** [comment]
Disable overlay in the settings

**Comment by doesthatmatter** [comment]
Oh, thanks
