### ISSUE TITLE
OBS support

### ISSUE THREAD

**Issue by Kagashini** [neowutran/ShinraMeter#45]
Can u realize obs support or mode for obs (Open Broadcast Software)? I add a new window obs and see a black square...

**Comment by Gl0** [comment]
OBS seems does not support capturing transparent wpf windows at all. We can make main window not transparent (AllowsTransparency=False) to make it visible on streams.

**Comment by Kagashini** [comment]
I think, need to add this setting in main menu. (AllowTransparency on or off)

**Comment by neowutran** [comment]
ok, will add the option for V0.70

**Comment by neowutran** [comment]
https://github.com/neowutran/ShinraMeter/wiki#obs

**Comment by Gl0** [comment]
Think it better to name this paragraph as streaming/capturing software support. OBS is not well-known acronym, and this issue may address not only OBS, but other streaming/capturing software as well.
