### ISSUE TITLE
Problem with Meter

### ISSUE THREAD

**Issue by Ashirogi98** [neowutran/ShinraMeter#451]
Hey, I use ShinraMeter since 2years and never have some issue in NA. But i move to EU and now have random damage like some guys do 300k/s dmg with SC+9, but when i see it on Moongourd they have 4m/s or smh....

This problem is like 2 week ago, and happend in all dungeons. Have random damage number and moongourd say another thing.

I download a new fresh version too.

*sorry for potato english. Thx

**Comment by Ashirogi98** [comment]
Yes Sir.
Yesterday i try without VPN and i got the same issue, so i remove fps-utils from proxy and work fine, i have similar damage than moongourd.

There no way for use fps-utils with meter? or that was for disable skills of some classes.

Thx for you help :D

**Comment by Gl0** [comment]
Probably even with not connected VPN it's driver intercepts tera traffic.
You have 2 ways to use fps-utils with meter, either remove your gaming vpn solution or properly configure it to ignore tera.exe traffic.
