### ISSUE TITLE
Focus issues, non-DX9 overlay glitches through TERA & fights for focus

### ISSUE THREAD

**Issue by Shrubbity** [neowutran/ShinraMeter#456]
I keep accidentally clicking through the DX-9 overlay and the game alt-tabs onto the more detailed UI. Do you know if there's a proper way to fix this? I'm running dwm.exe disabled and on Windows 1607, I've applied the Directx updates. For now disabling 'Show Always' and 'Stay Topmost' fixes it mostly, but the desktop still glitches through a little when Shinra is on.

**Comment by Gl0** [comment]
You are not clicking through overlay (it doesn't have click tracking at all), but clicking on main window that us supposed to be behind fullscreen tera (and not even updating if you don't have transparency disabled for streaming, which also forces software rendering).
Anyway there is clickthrough option in settings which makes it impossible to click on meter windows, and even hotkey for that option.

**Comment by Shrubbity** [comment]
Yeah true, it's manageable, I was wondering if this is specific to my configuration or if everyone gets the main window glitching through.
