### ISSUE TITLE
TW/JP/KR monsters qustion

### ISSUE THREAD

**Issue by sb032835** [neowutran/ShinraMeter#46]
zone id 759 for jp
Monster name="バーンスタイン" id="1003" isBoss="False" hp="455000000" /
zone id 759 for TW
Monster name="伯恩斯坦" id="1003" isBoss="False" hp="455000000" /
zone id 759 for KR
Monster name="번스타인" id="1003" isBoss="False" hp="455000000" /

isBoss shound be True

**Comment by neowutran** [comment]
ok ^^ 
added it here: 
https://github.com/neowutran/TeraDpsMeterData/commit/36609519c6dccb39e9cb8a410d5fa2c1969d9fc8
