### ISSUE TITLE
shinraMeter Work find with noPing but ,,,

### ISSUE THREAD

**Issue by Blackcrystal2010** [neowutran/ShinraMeter#460]
hi  ,,  how are u 
shinraMeter Work find with noPing but ,,,
 I can only see the dmg % for all players but I cant see thier crit rate or there dps Details ( for my chra is work fine - just me )
https://imgur.com/M55bTgF

**Comment by Gl0** [comment]
Remove tera.exe from noping config (not sure if it have such option).
Or remove any fps-utils like module from your tera-proxy
