### ISSUE TITLE
[Request] Adrenaline Rush notification for healers

### ISSUE THREAD

**Issue by Qilik** [neowutran/ShinraMeter#461]
Would it be possible to get adrenaline rush voice and popup notification for healers like it already does for dds?

**Comment by neowutran** [comment]
https://github.com/neowutran/ShinraMeter/blob/master/Lang/Resources/en/events-common.xml#L5

You need to modify SHINRA_FOLDER/resources/config/events/event-common.xml 
For Adrenaline rush, remove ``ignore_classes="Mystic,Priest"``
