### ISSUE TITLE
Dps Purpose?

### ISSUE THREAD

**Issue by ratchetlover00** [neowutran/ShinraMeter#462]
So, I don't really have this meter, and don't utilize it for any reason or purpose, However, I know that people who play TERA use it quite often. I have been a  victim of other people who use your meter to harass and bully other people because they can see other people's damage, Change your program so that only the person using it on THEIR OWN END can see their own damage and stats.

**Comment by Gl0** [comment]
If somebody harass you - report them to game support and they would be banned.
