### ISSUE TITLE
Global statistics page is down

### ISSUE THREAD

**Issue by eeznir** [neowutran/ShinraMeter#466]
The page that should be leading to all boss fight data is down. I just wanted to know if you guys were aware of this, and if so, when do you expect it to be back up? I really want to have a look at DPS data from KTERA players.

https://neowutran.ovh/files-storage/TeraStatistics/

**Comment by neowutran** [comment]
Hi, 
The page have been moved quite some times ago. 
The new page is here: https://neowutran.ovh/data/html/dps.html 

Sorry for the outdated doc, I just updated the link
