### ISSUE TITLE
Haymaker buff not showing correct uptime on Party members

### ISSUE THREAD

**Issue by Neuro12** [neowutran/ShinraMeter#468]
Hello,

I was looking through some runs and saw that the new haymaker buff for 1.5% dmg boost to party members only showed the correct uptime on the brawler and not other party members even if the buff was applied the whole run. I tested it out with some of my guild members and had them monitor their buff bar and they confirmed they had the buff pretty much the whole fight but when I look to the buff page on the meter breakdown, it either doesn't register at all for them or shows a value completely lower. I have some screenshots below. Thanks

![](https://image.prntscr.com/image/iLztTFh1TwOeiRYVgh7QDw.png)

![](https://image.prntscr.com/image/4YKa_7-uRZe_vg6akTKO3Q.png)

**Comment by Neuro12** [comment]
The same thing also appears on MG

![](https://image.prntscr.com/image/qzERaaWwQmmI9A8FO1h-pA.png)

![](https://image.prntscr.com/image/zx-PXoqXRh2iCG3HIoeuEg.png)

**Comment by SaltyMonkey** [comment]
Bugged serverside - clients not receiving buff info for party/raid (only your). Issue can be closed.
