### ISSUE TITLE
Shinra Meter No Server issue

### ISSUE THREAD

**Issue by Frostwaffles** [neowutran/ShinraMeter#470]
I already did a firewall exception for shinrameter and i can open programme without any problem. When i connect in game shinra meter doesnt detect the server that i am in and stays on " No Server " state. That results with dps meter is not working
![shinrameter](https://user-images.githubusercontent.com/53008583/61381995-8e826280-a8b4-11e9-9be2-980a328a2971.png)

**Comment by neowutran** [comment]
Hi 
Try to use the latest version of ShinraMeter (v2.68) with the latest version of npcap https://nmap.org/npcap/

**Comment by Frostwaffles** [comment]
I tried on both v2.67 and v2.68 , didnt work.

**Comment by Frostwaffles** [comment]
it got fixed after installing npcap from the link you gave me , thank you sir.

**Comment by neowutran** [comment]
np ^^
