### ISSUE TITLE
Gives my PC Bluescreen when exiting program.

### ISSUE THREAD

**Issue by Lavenora** [neowutran/ShinraMeter#472]
It works completely fine otherwise, but every time I Close the program or turn off my PC while the program is still running, it will bluescreen my PC 100% of the time.

**Comment by neowutran** [comment]
Such behavior should only be triggered by a bug inside npcap. 
Try updating npcap to the latest version. If it doesn't fix it, a bug report should be send to the npcap projet with every hardware details + detailled debug logs of npcap
