### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by rye219** [neowutran/ShinraMeter#475]
I have ran this program in the past, but deleted some stuff (including shinra) to try to make my laptop run faster. Now, I can't seem to get the program to stay open for more than a few seconds. I have attached the error message, any help is appreciated! Thank you!
[error.log](https://github.com/neowutran/ShinraMeter/files/3979888/error.log)

**Comment by Gl0** [comment]
Seems your meter is missing dx9_overlay.dll. May be blocked by antivirus. You can either download it again (and check that it is not deleted) or disable overlay in window.xml

**Comment by rye219** [comment]
@Gl0, Thank you for responding!
 I deleted all of the files, and re-downloaded them. The overlay file is downloaded as well, but I am still getting this error. I'm not sure what I'm doing wrong...

**Comment by Gl0** [comment]
If you download meter via internet explorer and extract archive via windows explorer, it can mark files as unsafe due to have been downloaded from internet and block it. Try downloading with other browser or unpacking via third-party archiver like 7z.

**Comment by Gl0** [comment]
Or you can right-click on dll and check "unblock" there.

**Comment by Gl0** [comment]
Also make sure that you have https://www.microsoft.com/en-us/Download/details.aspx?id=8109 installed as stated in wiki.
