### ISSUE TITLE
No sound in event dung

### ISSUE THREAD

**Issue by unlimitedgtx** [neowutran/ShinraMeter#476]
A friend told me, that he hasnt any sound notifications in event dung abscess,
Every other place its working, but only not in this dung.

**Comment by neowutran** [comment]
Need more infos 
But more likely related to boss detection than sound. 
Does the boss is detected correctly by the meter ? if so, what kind of event are not triggered ?

**Comment by unlimitedgtx** [comment]
He said no events work. No nemesis, energy stars, adrenalin rush. He get no notification sounds, but shinra isnt muted

**Comment by Gl0** [comment]
uncheck "detect bosses by hp bar (ignore db)" in settings

**Comment by unlimitedgtx** [comment]
> 
> 
> uncheck "detect bosses by hp bar (ignore db)" in settings

its unchecked but nothing changed

**Comment by unlimitedgtx** [comment]
Problem only exists in abscess hardmode. Boss is detected correctly by shinra, i see every event on boss bar, but dont get any notification sound

**Comment by Gl0** [comment]
notification popups are there too? if not - may be there is some `area_boss_blacklist` in config file.

**Comment by unlimitedgtx** [comment]
No, notification popus missing too

**Comment by unlimitedgtx** [comment]
So no idea or solution?

**Comment by Gl0** [comment]
If shinra's boss hp bar is visible for these bosses and notifications are working for other bosses - then I have the only idea mentioned above - `area_boss_blacklist` in event config files.

**Comment by unlimitedgtx** [comment]
> 
> 
> If shinra's boss hp bar is visible for these bosses and notifications are working for other bosses - then I have the only idea mentioned above - `area_boss_blacklist` in event config files.

There is no `area_boss_blacklist`, i couldnt find something in event files. And other players have the same issue.

**Comment by Gl0** [comment]
Actually rechecked the code, seems that's intended behavior, if there is no ingame boss bar for these bosses  => no events fired, despite of shinra's boss bar is shown.
Probably we need to add notifications to other bosses too.
