### ISSUE TITLE
2 windows of game

### ISSUE THREAD

**Issue by Kagashini** [neowutran/ShinraMeter#48]
Can u realize a support of 2 windows? I start the first window - no problem. I start second window and I have problems. Meter don't know this and I see Oh No... DPS? The first window? Second window? or what must I do? Oh.. Oh.. Oh.. DPS, DPS, OH >:(

**Comment by neowutran** [comment]
2 windows? 2 tera game windows?

**Comment by Kagashini** [comment]
Yes. We can start 2 tera game windows (TERA RU)

**Comment by neowutran** [comment]
When you select a server, the dps meter disconnect from any previous connection and connect itself to the server you selected ingame. 
So the dps meter SHOULD be listening to the last windows you connected to a server. (if that don't work like this, tell me, that a bug)
But didn't tested that. 

And doing a support for 2 or more windows seem is a lot of work for nearly nothing. So I won't even try to do it. If you really need to record 2 differents tera window at the same time, use the shinra meter for one window, and use the casual meter (or other) for the second window

**Comment by Kagashini** [comment]
I will check.
