### ISSUE TITLE
To run this application, you must install .NET Core.

### ISSUE THREAD

**Issue by HardManXX5** [neowutran/ShinraMeter#481]
Like the title said, when I start it, this message shows up but it is installed. Probably not supported anymore I guess?
![f](https://user-images.githubusercontent.com/69721483/90313518-7c3a8400-df0d-11ea-827b-eb124fc56117.jpg)

**Comment by Foglio1024** [comment]
As stated in the [patch notes](https://github.com/neowutran/ShinraMeter/wiki/Patch-note):

> Starting from version 2.71 meter require [latest .NET Core for **windows desktop x64**](https://dotnet.microsoft.com/download/dotnet-core/current/runtime), don't accept meter update until you install it.
