### ISSUE TITLE
Shinra stops counting elapsed time during user's death

### ISSUE THREAD

**Issue by paplusplusplus** [neowutran/ShinraMeter#486]
Hi, my Shinra  Meter stops counting elapsed fight time when I die, then continues counting after I revive. So I would like to ask if there are some ways to set the meter to always count elapsed fight time? thx

**Comment by Gl0** [comment]
Elapsed fight time shown by shinra = timestamp of last hit - timestamp of first hit (main window show fight stats, not current state). If nobody hit the boss while you are dead - timer would show same numbers.

**Comment by paplusplusplus** [comment]
> Elapsed fight time shown by shinra = timestamp of last hit - timestamp of first hit (main window show fight stats, not current state). If nobody hit the boss while you are dead - timer would show same numbers.

thank you for ur fast reply 👍 so that means timer wouldn't change while nobody hitting, but its gonna continue counting (including the lost elapsed time) when someone hit the boss, right? 
So if I die at 1:30 on timestamp > no one hit the boss for 10 sec (timer shows at 1:30) > a party member hits the boss (timer instantly changes to 1:40 and continues counting). Is this correct?

**Comment by Gl0** [comment]
yes

**Comment by paplusplusplus** [comment]
alright, many thanks 👍
