### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Kagashini** [neowutran/ShinraMeter#49]
`2016-02-27 18:25:26,084 [10] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### CRASH (version=0.70): #####
Данный ключ отсутствует в словаре.
   в System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   в DamageMeter.Abnormality.ApplyEnduranceDebuff(Int64 lastTicks)
   в DamageMeter.Abnormality.ApplyBuffDebuff(Int64 tick)
   в DamageMeter.AbnormalityTracker.DeleteAbnormality(EntityId entity, Int64 ticks)
   в DamageMeter.NetworkController.PacketAnalysisLoop()
   в System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.Collections.Generic.KeyNotFoundException: Данный ключ отсутствует в словаре.
   в System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   в DamageMeter.Abnormality.ApplyEnduranceDebuff(Int64 lastTicks)
   в DamageMeter.Abnormality.ApplyBuffDebuff(Int64 tick)
   в DamageMeter.AbnormalityTracker.DeleteAbnormality(EntityId entity, Int64 ticks)
   в DamageMeter.NetworkController.PacketAnalysisLoop()
   в System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal

TValue get_Item(TKey)
`

**Comment by neowutran** [comment]
Yep ^^ will look for that

**Comment by Kagashini** [comment]
version=0.77 repeat the bug.

**Comment by neowutran** [comment]
should be fixed now. Tell me if you see it again with the new version (0.80)
