### ISSUE TITLE
[request] Number of players

### ISSUE THREAD

**Issue by Kagashini** [neowutran/ShinraMeter#50]
Again me :dancer: I want to see a new future :+1: 
Can u realize a fast switch between 1-10 players?
Ex.: 
1) We have a party of 3-10 players but I want to see dps only for me.
2) We have a party of 3 players but I want to see dps only for 1-2 players.
3) We have a party of 10 players but I want to see dps only for 1-9 players.
4) We have a party of 10 players but I want to see dps only for me and my friend.

TY for your work!

**Comment by neowutran** [comment]
will finally add this functionnality for the raid 30. Will be able to choose how many ppl you want to see in the main windows. Scroll bar if you choose to display a lot of ppl. 
You won't be able to choose who will be displayed, this choice will be made by the software based on the dps of everyone
