### ISSUE TITLE
shinra crash

### ISSUE THREAD

**Issue by tsukiyoK** [neowutran/ShinraMeter#51]
2016-02-28 18:09:06,199 [1] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### CRASH (version=0.70): #####
Couldn’t register the hot key.
   於 DamageMeter.KeyboardHook.RegisterHotKey(ModifierKeys modifier, Keys key)
   於 DamageMeter.KeyboardHook.Register()
   於 DamageMeter.KeyboardHook.RegisterKeyboardHook()
   於 DamageMeter.UI.MainWindow.UpdateKeyboard(Object o, EventArgs args)
   於 System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   於 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Windows.Threading.DispatcherOperation.Invoke()
   於 System.Windows.Threading.Dispatcher.ProcessQueue()
   於 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   於 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   於 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   於 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   於 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   於 System.Windows.Application.RunDispatcher(Object ignore)
   於 System.Windows.Application.RunInternal(Window window)
   於 System.Windows.Application.Run(Window window)
   於 DamageMeter.UI.App.Main()
DamageMeter
System.InvalidOperationException: Couldn’t register the hot key.
   於 DamageMeter.KeyboardHook.RegisterHotKey(ModifierKeys modifier, Keys key)
   於 DamageMeter.KeyboardHook.Register()
   於 DamageMeter.KeyboardHook.RegisterKeyboardHook()
   於 DamageMeter.UI.MainWindow.UpdateKeyboard(Object o, EventArgs args)
   於 System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   於 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Windows.Threading.DispatcherOperation.Invoke()
   於 System.Windows.Threading.Dispatcher.ProcessQueue()
   於 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   於 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   於 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   於 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   於 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   於 System.Windows.Application.RunDispatcher(Object ignore)
   於 System.Windows.Application.RunInternal(Window window)
   於 System.Windows.Application.Run(Window window)
   於 DamageMeter.UI.App.Main()
System.Collections.ListDictionaryInternal

Void RegisterHotKey(ModifierKeys, System.Windows.Forms.Keys)

Hello
I can use shinra successfully at first.
But when I get into dungeon then shinra crash.
The errorlog told me 'Void RegisterHotKey(ModifierKeys, System.Windows.Forms.Keys)'
But I didn't change any hotkey :3

**Comment by neowutran** [comment]
Did you try to open another shinra meter, or a casual meter or anything that use the same hotkey as shinra meter?

**Comment by tsukiyoK** [comment]
oh thanks!
I fix it up
My music player use hotkey too.
so I can't use musicplayer and shinra together :3

Thank you very much!
very useful software!

**Comment by neowutran** [comment]
=) have fun
