### ISSUE TITLE
Unable to contact update server

### ISSUE THREAD

**Issue by NiponM** [neowutran/ShinraMeter#52]
Why does this happen?

http://oi65.tinypic.com/33418c4.jpg

When I launch Tera and hit something the dps meter dont show anything at all. I did the same steps as my friend and his dps meter works fine.

**Comment by neowutran** [comment]
What is your OS? Window 7 ? 8 ? Vista?

**Comment by neowutran** [comment]
And do you have installed .Net 4.6?

**Comment by NiponM** [comment]
Windows 7 Ultimate and yeah I installed that and Winpcap too. I dont know whats going on because as I said, I did the same steps than my friend and it did work for him. Im using another dps meter right now and it works fine :(

**Comment by neowutran** [comment]
From your picture, the version you are using is very old. I recommand you to download the latest one (V0.71)

But that indeed weird. 
If the meter doesn't detect the server (when you put the cursor over the meter icon, you will see a title "Shinra Meter V0.71"),  try to switch to raw socket, that a common issue: 
https://github.com/neowutran/ShinraMeter/wiki#network

You play on what server / region?
