### ISSUE TITLE
The meter doesn't work in DS2 uppers

### ISSUE THREAD

**Issue by Qarinna** [neowutran/ShinraMeter#54]
Hello,
the meter doesnt detect bosses in ds2 uppers, namely the queen.
It is a bit annoying, because it just detects overal dmg made, and doesn't reset when we reset queen etc.

**Comment by neowutran** [comment]
NA servers ?

**Comment by Qarinna** [comment]
Yes, I can confirm on 100% it is like that. 
I didn't check other bosses than queen, i turned it on only during floor 22.

**Comment by neowutran** [comment]
If you still have the meter, open the encounter selectbox, you will normally see something like  "number : Dreadspire". 
The number is the encounter ID, with that ID I can make a fix.

Anyway, DS2 will come out in EU tomorrow, so I will see & fix that problem by myself

**Comment by Qarinna** [comment]
No, it doesnt work like that. 
There is nothing, the as it is for example, when you just start the meter and go kill mobs (for 30s mobs quests)

I think the meter doesnt recognize the boss which is being attacked.

**Comment by neowutran** [comment]
yes, the encounter selection stay on "TOTAL", but the mobs are still selectable in the selectbox. 

And yes, from what you say, it seems that the meter doesn't count the Queen as a boss. So no auto selection of the Queen, and no reset when you reset the Queen.

**Comment by Qarinna** [comment]
It could be, honestly I have deleted the encounters yesterday and right now I don't have party to reach queen again, but this evening I can report in more detailed way, although I am sure you have identified the issue yourself. 

Thank you very much, waiting or the fix, as checking the party dps during queen is really important! :)

**Comment by neowutran** [comment]
Ok =) 
The fix will probably be ready for this weekend. Nearly nothing to change, but I need to run DS2 upper myself to check the problem & gather the needed informations to fix it ^^

**Comment by Qarinna** [comment]
Since I will run it in few hours, I can try to help you if you tell me what you need to know more.

**Comment by neowutran** [comment]
after the fight with the Queen, open the encounter selectbox. The first element of the list is the last thing you hit (so the Queen if you open the encounter selectbox just after the fight). 
This element can be "number : Dreadspire" or "manaya upper: Dreadspire", or another name idk. 
I need this "xxxx : yyyy"

**Comment by Qarinna** [comment]
Okay, i will report as soon as i have more info later on.

**Comment by Gl0** [comment]
Seems there are a bunch of bosses without agro target.
I can force isBoss for all mobs having more then 100M HP, or something else, but not sure that there no adds with such HP and no bosses with lower HP.

**Comment by Qarinna** [comment]
https://gyazo.com/b1a1ae7bbbf7e464a1ccbcf4160d6b76

This is FIHM breakdown

**Comment by neowutran** [comment]
Thanks for the data. 
What version of the meter are you using? ( put your cursor over the shinra meter icon to know that)

**Comment by Qarinna** [comment]
72. It updated yesterday

**Comment by neowutran** [comment]
ok ^^ and can you send me this file plz : "resources/data/monsters/monsters-NA.xml" ?

**Comment by Qarinna** [comment]
Where? Can I update files here?

**Comment by neowutran** [comment]
nop, you can upload file here. Maybe a link to mega. Or link to pastebin with the content of the file

**Comment by Qarinna** [comment]
http://www.megafileupload.com/vnKN/monsters-NA.xml

**Comment by neowutran** [comment]
the file is good, last check: go to "resources/config/window.xml"
what is the language ? (copy paste the file content directly here)
I think I found out your problem, but need to verify that ^^

**Comment by Qarinna** [comment]
<?xml version="1.0" encoding="utf-8"?>
<window>
  <location>
    <x>1468</x>
    <y>380</y>
  </location>
  <language>EU-EN</language>
  <opacity>
    <mainWindow>50</mainWindow>
    <skillWindow>70</skillWindow>
  </opacity>
  <autoupdate>true</autoupdate>
  <remember_position>true</remember_position>
  <winpcap>true</winpcap>
  <invisible_ui>false</invisible_ui>
  <allow_transparency>true</allow_transparency>
</window>

**Comment by Qarinna** [comment]
ye shotly its english lol

**Comment by neowutran** [comment]
Found it =) 
Replace "EU-EN" by "Auto"
Everything will work fine after that

(EU-EN means you use the European english file, DS2 and FIHM doesn't exist in EU yet)

**Comment by Qarinna** [comment]
I will try it out and report if there is a problem
Thank you

**Comment by Qarinna** [comment]
I haven't checked FI yet, but Island of dawn bosses do not show properly either (changed language)

7009: Island of Dawn
7008: Island of Dawn
7007: Island of Dawn

**Comment by neowutran** [comment]
recheck that the window.xml file is still correct. If it's correct, then I will see tomorrow on EU

**Comment by Qarinna** [comment]
Yes. 

The dps is still not working correctly


https://gyazo.com/ad1f289fe5e16780e16a0cfd189deb4f

**Comment by neowutran** [comment]
Check with the latest version (0.74), I tested it on DS2 manaya, and FIHM, no problem

**Comment by Qarinna** [comment]
There is a problem on floor 20.
The dps meter resets itself, I think it is related to the bug being invulnerable while charging lightning.

**Comment by neowutran** [comment]
Ok, will check that tonight
