### ISSUE TITLE
[request] Lock selected mob/boss

### ISSUE THREAD

**Issue by Kagashini** [neowutran/ShinraMeter#57]
Hello! Again me! :+1: I want to lock a line (TOTAL) but I can't do this. I hit 1 mob and see a damage for this mob... Sometimes I want to see a damage for all mobs not only 1 mob or I want to lock a specific mob.

**Comment by neowutran** [comment]
So, you want to be able to disable the encounter auto switch?

**Comment by Kagashini** [comment]
Yes! (Fast disable without shutdown the program)

**Comment by s2021369** [comment]
@neowutran 
Hellong. I'm sorry that I wrote this mention.
I want to contact with you on the hang-out >_<
