### ISSUE TITLE
bug 0.75

### ISSUE THREAD

**Issue by lofuy** [neowutran/ShinraMeter#59]
2016-03-10 11:06:38,354 [9] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### CRASH (version=0.75): #####
Référence à une entité non déclarée, 'nbsp'. Ligne 12937, position 35.
   à System.Xml.XmlTextReaderImpl.Throw(Exception e)
   à System.Xml.XmlTextReaderImpl.HandleGeneralEntityReference(String name, Boolean isInAttributeValue, Boolean pushFakeEntityIfNullResolver, Int32 entityStartLinePos)
   à System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   à System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   à System.Xml.XmlTextReaderImpl.ParseAttributes()
   à System.Xml.XmlTextReaderImpl.ParseElement()
   à System.Xml.XmlTextReaderImpl.ParseElementContent()
   à System.Xml.XmlTextReaderImpl.Read()
   à System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   à System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   à System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   à System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   à Data.MonsterDatabase..ctor(String folder, String language)
   à Data.TeraData..ctor(String region)
   à Data.BasicTeraData.<>c.<.ctor>b__3_0(String region)
   à System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   à Data.BasicTeraData.<>c__DisplayClass40_0`2.<Memoize>b__0(T x)
   à Data.BasicTeraData.DataForRegion(String region)
   à DamageMeter.NetworkController.HandleNewConnection(Server server, IPEndPoint serverIpEndPoint, IPEndPoint clientIpEndPoint)
   à DamageMeter.Sniffing.TeraSniffer.OnNewConnection(Server server, IPEndPoint serverIpEndPoint, IPEndPoint clientIpEndPoint)
   à DamageMeter.Sniffing.TeraSniffer.HandleTcpDataReceived(TcpConnection connection, ArraySegment`1 data)
   à NetworkSniffer.TcpConnection.OnDataReceived(ArraySegment`1 data)
   à NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment`1 data)
   à NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData)
   à NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data)
   à NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e)
   à SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p)
   à SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p)
   à SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data)
   à SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   à SharpPcap.LibPcap.PcapDevice.CaptureThread()
   à System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart()
System.Xml
System.Xml.XmlException: Référence à une entité non déclarée, 'nbsp'. Ligne 12937, position 35.
   à System.Xml.XmlTextReaderImpl.Throw(Exception e)
   à System.Xml.XmlTextReaderImpl.HandleGeneralEntityReference(String name, Boolean isInAttributeValue, Boolean pushFakeEntityIfNullResolver, Int32 entityStartLinePos)
   à System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   à System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   à System.Xml.XmlTextReaderImpl.ParseAttributes()
   à System.Xml.XmlTextReaderImpl.ParseElement()
   à System.Xml.XmlTextReaderImpl.ParseElementContent()
   à System.Xml.XmlTextReaderImpl.Read()
   à System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   à System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   à System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   à System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   à Data.MonsterDatabase..ctor(String folder, String language)
   à Data.TeraData..ctor(String region)
   à Data.BasicTeraData.<>c.<.ctor>b__3_0(String region)
   à System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   à Data.BasicTeraData.<>c__DisplayClass40_0`2.<Memoize>b__0(T x)
   à Data.BasicTeraData.DataForRegion(String region)
   à DamageMeter.NetworkController.HandleNewConnection(Server server, IPEndPoint serverIpEndPoint, IPEndPoint clientIpEndPoint)
   à DamageMeter.Sniffing.TeraSniffer.OnNewConnection(Server server, IPEndPoint serverIpEndPoint, IPEndPoint clientIpEndPoint)
   à DamageMeter.Sniffing.TeraSniffer.HandleTcpDataReceived(TcpConnection connection, ArraySegment`1 data)
   à NetworkSniffer.TcpConnection.OnDataReceived(ArraySegment`1 data)
   à NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, ArraySegment`1 data)
   à NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData)
   à NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data)
   à NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e)
   à SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p)
   à SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p)
   à SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data)
   à SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   à SharpPcap.LibPcap.PcapDevice.CaptureThread()
   à System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal

Void Throw(System.Exception)

**Comment by neowutran** [comment]
region / language?

**Comment by neowutran** [comment]
C'est un problème spécifique au language français. Je corrigerai ca pour la V0.76, mais pour le moment tu peux juste passer le dps meter en anglais et ca devrait fonctionner correctement (problème dans le fichier xml)

**Comment by neowutran** [comment]
(tu peux aussi remplacer le fichier "resources/data/monsters/monsters-EU-FR.xml" par celui la https://github.com/neowutran/TeraDpsMeterData/blob/master/monsters/monsters-EU-FR.xml)
