### ISSUE TITLE
ktera doesn't work  please help T A T

### ISSUE THREAD

**Issue by karoos12** [neowutran/ShinraMeter#62]
ktera doesn't work ! 

It can catch my server praysiar and come into action.

but,  it can't express anything into the UI...there are only empty..

  please help us, god! T A T

**Comment by neowutran** [comment]
Yep I know. With the DS3 update, Nexon make some change to the game. (packet encryption). 
Sooo, for now, no more meter for KTera until we found out the new packet encryption. And that can take time

**Comment by neowutran** [comment]
good
