### ISSUE TITLE
KR Tera I want to know the progress ㅠㅠ

### ISSUE THREAD

**Issue by KRTerameter** [neowutran/ShinraMeter#63]
I want to know the progress ㅠㅠ

KR Tera dosen't work Meter Help! T.T

i want to use shinrameter 

shinrameter is very useful program.. 

The delight of life gone.

plz! help!

I want to know the progress ㅠㅠ

**Comment by Kel331** [comment]
As it is mentioned in the previous issue page.
Nexon seems to have changed their encryption code key value.
We'll just have to wait in patience.

**Comment by neowutran** [comment]
good
