### ISSUE TITLE
help...didn't work in ktera

### ISSUE THREAD

**Issue by heurinbada** [neowutran/ShinraMeter#67]
os : windows 10 x64
cpu : i7 - 2670QM
gpu : NVIDIA GeForce GTX 560M
ram : 8gb
SSD : Samsung SSD 850 PRO 512GB

using wifi
(i try change lan or wifi, but same problem appear ) 

detailed screen shot 
http://gall.dcinside.com/board/view/?id=tera&no=1033487

1. Win10Pcap setup completed

2. NET Frame work 4.6  setup completed
(message : NET Framework 4.6 or higher version is already installed)

3. windows firewall and defender off
(i try add a firewall exception(https://github.com/neowutran/ShinraMeter/wiki/Window-firewall) but didn't work
 than off the firewall, didn't work)

4. ShinraMeterV0.77 download

5. ShinraMeterV0.77 start

6. ktera start

7. windowed(fullscreen) 

8. Shinra Meter V0.77 : No server

9. didn't work.....

----------------------------------------------------------
another ktera player are work well..
i have same problem at another version...

**Comment by neowutran** [comment]
try raw socket then: 
https://github.com/neowutran/ShinraMeter/wiki#network
winpcap doesn't work for everyone

***

Are you using a VPN?
Check with a ethernet connexion

**Comment by heurinbada** [comment]
^_^ good..... thank you!!! // p.s i don't know manner about github, if you want hide or delete this page or do labels or anythig... tell me what can i do for you

**Comment by neowutran** [comment]
=)

**Comment by hsluoyz** [comment]
Hi,

You would like to try Npcap: https://github.com/nmap/npcap

It's a update to original WinPcap

**Comment by neowutran** [comment]
Hi, 
thanks for the link, I didn't know about this project =)
