### ISSUE TITLE
Korea tera meter block

### ISSUE THREAD

**Issue by KRTerameter** [neowutran/ShinraMeter#70]
Korea tera shinramter block

maybe xigncode3 block

shinrameter is very useful program!

It is to use the pleasures of my life sinrameter

help !! i love NEOWUTRAN !

help !! T.T

**Comment by luka7** [comment]
it's process blocked

**Comment by neowutran** [comment]
huehuehue x) 
They use a signature detection blocking => probably something like that: 
They download the official, publicly available release, hash "ShinraMeter.exe" and add the hash to xigncode3. 

To make it work, you need a ShinraMeter.exe who is different than the official release. 
If you had some programming knowledge, download the source of the ShinraMeter
Add a random line in the DamageMeter.UI project
(
Exemple: 
Add 'Console.WriteLine("lol")' here https://github.com/neowutran/ShinraMeter/blob/master/DamageMeter.UI/MainWindow.xaml.cs#L58
)
Then compile the project, and xigncode3 won't be able to detect the ShinraMeter

If I want to make an automated way to bypass that block, that not really hard, but that take time and not very fun => boring

**Comment by Gl0** [comment]
Next logical step from Nexion is to block user accounts when dpsmeter detected by updated game protection.

**Comment by neowutran** [comment]
Yup, they can. From what I know, using a 3rd party software on KTera is a bannable offense. So instead of making the game crash when they detect the meter, they can ban the account if they want

**Comment by Gl0** [comment]
BTW, no need to change something, just compile latest source, which in 99% times is changed after release due to active development.=)

**Comment by Gl0** [comment]
It's also interesting, whether they track other public forks with KTera support.

**Comment by Kel331** [comment]
KTera did make an annoucement about the DPS meter early this month.
They don't stop you from using it but they won't take responsibility for any problems made with it.
Also they will ban your account if you use it to make trouble in the community.
SO, for now, they won't ban you for using it but they could change their mind at any time.

**Comment by Gl0** [comment]
This statement sounds like all other region publishers position. But in other regions they do not attempt to prevent it from running.

**Comment by luka7** [comment]
I understood.
Obviously the use directly after compiling works very well.
thx. X)

**Comment by neowutran** [comment]
Thanks for the info @Kel331 , I didn't know
