### ISSUE TITLE
Compile questions

### ISSUE THREAD

**Issue by citCompile** [neowutran/ShinraMeter#71]
The build error pops up when building a DPS meter.
Whether you are using any compiler

I'm currently in use** VS 2013** compiler

Some Error List.
ShinraMeter-master \ Tera Common \ Game \ Angle.cs (15,31,15,33): error CS1002:; required.
ShinraMeter-master\TeraCommon\Game\Angle.cs(15,39,15,40): error CS1519: class, you have the wrong '(' token in the struct, or interface member declaration.
ShinraMeter-master\TeraCommon\Game\Angle.cs(15,49,15,50): error CS1519: class, there is a wrong '/' token in a struct, or interface member declaration.
ShinraMeterV0.76\ShinraMeter-master\TeraCommon\Game\Player.cs(78,20,78,21): error CS1056: Unexpected '$' character.
ShinraMeterV0.76\ShinraMeter-master\TeraCommon\Game\Player.cs(15,30,15,32): error CS1002:; is required.
ShinraMeter-master\TeraCommon\Game\Player.cs(15,46,15,47): error CS1519: class, struct, or interface members declared invalid on the ';' There is a token.
ShinraMeter-master\TeraCommon\Game\Player.cs(16,30,16,32): error CS1002:; is required.
ShinraMeter-master\TeraCommon\Game\Player.cs(16,46,16,47): error CS1519: class, struct, or interface members declared invalid on the ';' There is a token.
ShinraMeter-master\TeraCommon\Game\Player.cs(18,28,18,30): error CS1002:; is required.
ShinraMeter-master\TeraCommon\Game\Player.cs(18,40,18,41): error CS1519: class, struct, or interface members declared invalid on the ';' There is a token.
ShinraMeter-master\TeraCommon\Game\Player.cs(19,30,19,32): error CS1002:; is required.
ShinraMeter-master\TeraCommon\Game\Player.cs(19,39,19,41): error CS1519: class, there is a wrong '==' token in the struct, or interface member declaration.

**Comment by neowutran** [comment]
We use this kind of thing: https://msdn.microsoft.com/en-us/library/dn961160.aspx
so, VS 2015 required to compile

**Comment by Gl0** [comment]
btw, not sure, whether it worth to port Tera.Core back to VS2013 compatible format to bring back the ability to compile gothos version with it.

**Comment by neowutran** [comment]
don't really see any reason to port the project back to VS2013
