### ISSUE TITLE
Wont capture

### ISSUE THREAD

**Issue by EscobarTony** [neowutran/ShinraMeter#72]
I launch the meter before launching tera or the launcher and it opens on the newest version but when I DPS something it doesnt work. Please help.

**Comment by Gl0** [comment]
try to use raw sockets https://github.com/neowutran/ShinraMeter/wiki#network

**Comment by EscobarTony** [comment]
Sorry kinda of a noob but where do I find the windows.xml to change to raw socket

**Comment by neowutran** [comment]
./resources/config/window.xml

**Comment by EscobarTony** [comment]
that did not work. I allowed it with windows firewall and changed it to raw socket but it still doesnt work.

**Comment by neowutran** [comment]
hum, weird
You launch the dps meter and after you lauch the game? 

You play on what region? NA, EU ? what server? 

What kind of internet connexion do you have? (ethernet? wifi? usb 3g? )

You use any kind of VPN? 

What is your OS? (windows 7, 8, 10 ? )

**Comment by EscobarTony** [comment]
I launch the DPS meter before I launch the launcher or the game itself.

I play on NA

WIFI

No VPN

Windows 10

**Comment by Gl0** [comment]
Double check that window.xml contains `<winpcap>false<winpcap>`
If you changed it while meter was running - it had been overwrited on meter exit.

**Comment by EscobarTony** [comment]
I see what you mean however it still doesnt work

**Comment by EscobarTony** [comment]
Is there anything else I can try

**Comment by Gl0** [comment]
You may try to make network bridge between wifi and ethernet adapter.

**Comment by EscobarTony** [comment]
Should I launch the meter before or after I launch the game

**Comment by Gl0** [comment]
Before

**Comment by EscobarTony** [comment]
Also I made a network bridge and it didnt work.

**Comment by EscobarTony** [comment]
Yeah thats what I normally do.

**Comment by neowutran** [comment]
Not many idea left. 
You can try installing this pcap driver: https://github.com/nmap/npcap/releases 
and set 
> <winpcap>true</winpcap>

Not even sure if that can work, but not many idea left

**Comment by EscobarTony** [comment]
Thank you for helping me. It is no fixed with that pcap driver.

**Comment by neowutran** [comment]
weird, sry, no idea left ^^ You can try other meter like casual meter, but the result should be the same

**Comment by hsluoyz** [comment]
Actually, I don't know much use about the meter. But you can always run ``net start npf`` to see if Npcap is normally working or not.

**Comment by q848899** [comment]
Hi 
TW server Updated version the pugin is Not work please update thanks
