### ISSUE TITLE
JTera blocked

### ISSUE THREAD

**Issue by balamquan** [neowutran/ShinraMeter#74]
Anyway to get past the jtera block? It worked for a shot while and got blocked a week ago.

**Comment by neowutran** [comment]
They did a new update on JTera? if so, someone need to send me the new opcodes (& patch note, maybe it the patch where they modify the crypto key exchange)

**Comment by badgon** [comment]
[JTera Opcodes](https://drive.google.com/folderview?id=0Bzkk4M4rVzwSLXJZaUJ0OVNEbXc&usp=sharing)

**Comment by Gl0** [comment]
Again no changes. If it does not connect at all - problem is not with opcodes, but with traffic encryption.
Opcodes needed when it successfully connects but don't count.

**Comment by neowutran** [comment]
traffic encryption

**Comment by balamquan** [comment]
How can I got around the traffic encryption?

**Comment by neowutran** [comment]
@badgon or @balamquan  try with ShinraMeterVJ 
https://cloud.neowutran.ovh/index.php/s/e7arRRxkHEIkzU1
(I have not checked if it work and needing to write a japanese captcha every time I want to check something on JTera is not funny)

**Comment by balamquan** [comment]
I tried it but it didn't work.  Still getting blocked by xingcode.

**Comment by neowutran** [comment]
fatal error? aka => more details about the error?

**Comment by neowutran** [comment]
what crashed? The game? The meter? what error message?

**Comment by balamquan** [comment]
The meter crashed. 
[error1.txt](https://github.com/neowutran/ShinraMeter/files/188575/error1.txt)

**Comment by Gl0** [comment]
Need to update database, this bug [is fixed](https://github.com/neowutran/TeraDpsMeterData/commit/2c2ea4b51211aedb9711656db9d4889765339216)

**Comment by Gl0** [comment]
https://github.com/neowutran/ShinraMeter/commit/5018cf6ae0a4f529d9b780b2a5f461e940a4b3a0

**Comment by neowutran** [comment]
ok thx gl0, 
@balamquan  retry with ShinraMeterVJ2 & post if errors

**Comment by neowutran** [comment]
& another try => ShinraMeterVJ3
If that doesn't work, I will need to go to JTera dig in the assembly

**Comment by balamquan** [comment]
Thanks!

The VJ2 worked fine. VJ3 didn't work though - no error, managed to connect to the server but it didn't capture. Both crashed during autoupdate.

**Comment by neowutran** [comment]
VJ2: 
same opcode
same traffic encryption

The only difference is some line of code => signature based block?

**Comment by neowutran** [comment]
I close the issue. When I will release the V0.78, a new program will be embedded
https://github.com/neowutran/ShinraMeter/wiki/Signature-based-blocking-%28KR-&-JP%29

**Comment by Gl0** [comment]
btw, can you give us ServerId's of JP servers? It can be either sniffed all together in http xml exchange between launcher and server, either seen one by one in tooltip of the player.
