### ISSUE TITLE
[ui idea] 

### ISSUE THREAD

**Issue by neowutran** [neowutran/ShinraMeter#76]
http://media-curse.cursecdn.com/attachments/0/595/b814ccda2d1f3892ee2d018b2008ca63.jpg
http://media-curse.cursecdn.com/attachments/0/593/fd2fcf8c866e3a7a21765eda692f2192.jpg
http://media-curse.cursecdn.com/attachments/1/472/a12725b1ba9855880504bb525ae43af6.png

~~ too much data for the current ui, probably need new ui

**Comment by sb032835** [comment]
wow
add DBM...
