### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by tsukiyoK** [neowutran/ShinraMeter#79]
2016-04-01 21:22:30,944 [10] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### CRASH (version=0.78): #####
並未將物件參考設定為物件的執行個體。
   於 DamageMeter.SkillResult..ctor(Boolean abnormality, Int32 amount, Boolean isCritical, Boolean isHp, Int32 skillId, EntityId source, EntityId target, EntityTracker entityRegistry)
   於 DamageMeter.NetworkController.ForgeSkillResult(Boolean abnormality, Int32 amount, Boolean isCritical, Boolean isHeal, Int32 skillId, EntityId source, EntityId target)
   於 DamageMeter.NetworkController.PacketAnalysisLoop()
   於 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Threading.ThreadHelper.ThreadStart()
DamageMeter
System.NullReferenceException: 並未將物件參考設定為物件的執行個體。
   於 DamageMeter.SkillResult..ctor(Boolean abnormality, Int32 amount, Boolean isCritical, Boolean isHp, Int32 skillId, EntityId source, EntityId target, EntityTracker entityRegistry)
   於 DamageMeter.NetworkController.ForgeSkillResult(Boolean abnormality, Int32 amount, Boolean isCritical, Boolean isHeal, Int32 skillId, EntityId source, EntityId target)
   於 DamageMeter.NetworkController.PacketAnalysisLoop()
   於 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal

Void .ctor(Boolean, Int32, Boolean, Boolean, Int32, Tera.Game.EntityId, Tera.Game.EntityId, Tera.Game.EntityTracker)

Can you hlep me to fix it?

**Comment by Gl0** [comment]
https://github.com/neowutran/ShinraMeter/commit/0bcb1e35bb87f5ebbb5669ad1e6399b15eee3be4

**Comment by Gl0** [comment]
Can't find warrior's Smoke Aggressor skill icon using "Shadow" pet name. Seems to be the only skill without icon now.
