### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by sb032835** [neowutran/ShinraMeter#80]
2016-04-01 22:59:26,716 [10] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### CRASH (version=0.79): #####
並未將物件參考設定為物件的執行個體。
   於 DamageMeter.SkillResult..ctor(Boolean abnormality, Int32 amount, Boolean isCritical, Boolean isHp, Int32 skillId, EntityId source, EntityId target, EntityTracker entityRegistry)
   於 DamageMeter.NetworkController.ForgeSkillResult(Boolean abnormality, Int32 amount, Boolean isCritical, Boolean isHeal, Int32 skillId, EntityId source, EntityId target)
   於 DamageMeter.NetworkController.PacketAnalysisLoop()
   於 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Threading.ThreadHelper.ThreadStart()
DamageMeter
System.NullReferenceException: 並未將物件參考設定為物件的執行個體。
   於 DamageMeter.SkillResult..ctor(Boolean abnormality, Int32 amount, Boolean isCritical, Boolean isHp, Int32 skillId, EntityId source, EntityId target, EntityTracker entityRegistry)
   於 DamageMeter.NetworkController.ForgeSkillResult(Boolean abnormality, Int32 amount, Boolean isCritical, Boolean isHeal, Int32 skillId, EntityId source, EntityId target)
   於 DamageMeter.NetworkController.PacketAnalysisLoop()
   於 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal

Void .ctor(Boolean, Int32, Boolean, Boolean, Int32, Tera.Game.EntityId, Tera.Game.EntityId, Tera.Game.EntityTracker)
2016-04-01 23:38:52,185 [9] ERROR DamageMeter.AutoUpdate.Program [(null)] - ##### CRASH (version=0.79): #####
並未將物件參考設定為物件的執行個體。
   於 DamageMeter.SkillResult..ctor(Boolean abnormality, Int32 amount, Boolean isCritical, Boolean isHp, Int32 skillId, EntityId source, EntityId target, EntityTracker entityRegistry)
   於 DamageMeter.NetworkController.ForgeSkillResult(Boolean abnormality, Int32 amount, Boolean isCritical, Boolean isHeal, Int32 skillId, EntityId source, EntityId target)
   於 DamageMeter.NetworkController.PacketAnalysisLoop()
   於 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Threading.ThreadHelper.ThreadStart()
DamageMeter
System.NullReferenceException: 並未將物件參考設定為物件的執行個體。
   於 DamageMeter.SkillResult..ctor(Boolean abnormality, Int32 amount, Boolean isCritical, Boolean isHp, Int32 skillId, EntityId source, EntityId target, EntityTracker entityRegistry)
   於 DamageMeter.NetworkController.ForgeSkillResult(Boolean abnormality, Int32 amount, Boolean isCritical, Boolean isHeal, Int32 skillId, EntityId source, EntityId target)
   於 DamageMeter.NetworkController.PacketAnalysisLoop()
   於 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal

Void .ctor(Boolean, Int32, Boolean, Boolean, Int32, Tera.Game.EntityId, Tera.Game.EntityId, Tera.Game.EntityTracker)

**Comment by Gl0** [comment]
Duplicate #79
