### ISSUE TITLE
dps question

### ISSUE THREAD

**Issue by neowutran** [neowutran/ShinraMeter#83]
@Gl0 there is a event on tera ru? like HUUGE CDR?

**Comment by Gl0** [comment]
No, all CDR buffs (include event ones) should be seen in export.

**Comment by Gl0** [comment]
But not shown on web site, @kiritsuzu , may be add CDR buffs to durations list? And may be critrate/critpower ones. Or at least show all buff icons instead of empty places.

**Comment by neowutran** [comment]
hum, weird then. 
http://teradps.io/party/rank/XgStLJkZKFbYBTWeD
without a event buff like 90% CDR, I don't understand how such DPS is even possible

**Comment by Gl0** [comment]
Hm, don't see anything on this link, as well as on some previously posted.

**Comment by neowutran** [comment]
the site is dying, took 2min to load

**Comment by Gl0** [comment]
Seems it died at all.=)
Need to implement slaying state uptime, may be that's the key?

**Comment by kiritsuzu** [comment]
yeah, a friend informed me that there is 80% cdr event going on in russia now, i'll be mapping out the cdr buffs to be displayed soon

slaying uptime would be helpful too

**Comment by Gl0** [comment]
yeah, found announce, 11:00 - 13:00 & 20:00 - 22:00 this weekend 80% CDR. 
Was not in game and haven't seen it.

**Comment by Gl0** [comment]
abnormality id 25-28

**Comment by neowutran** [comment]
(slaying uptime? )

**Comment by Gl0** [comment]
Track party HP and count time when it is lower than 50%. should be not hard to do by forging abnormality like I've done with enrage.

**Comment by kiritsuzu** [comment]
ok, I just made it so 80% cdr buff parties are denied by api entirely =)

**Comment by Gl0** [comment]
You may ban all encounters with abnormal id < 37, or even <47 (this will also ban buff "Increases Attack Power, Attack Speed and Recovery ability by 2%. The abnormality while playing from PC cafes.").
New promo/test buffs may appear later with id <100, but not sure. For now first non-promo buff have id = 101.

**Comment by kiritsuzu** [comment]
Ok I added that filter in,

also right now i'm experimenting with rejecting all encounters with partydps of lower than 2,000,000. i think it's reasonable, because most sub 2m encounters look like pretty trash (some dps died 5++ times, or doing 100k-200k dps)

hopefully it will help only make it so more high quality encounters are let through
