### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by books96** [neowutran/ShinraMeter#84]
Whenever I open the meter, a few seconds after I open it, a window pops up saying "a fatal error has been found, please see the error.log file for more informations."  [Here](http://pastebin.com/XnaF3Tbx) is a copy of what is in the error file.

**Comment by neowutran** [comment]
That means that you have another program running who use the same hotkeys as the ShinraMeter. Maybe another ShinraMeter instance.

**Comment by books96** [comment]
I see. Thank you.
