### ISSUE TITLE
raw sockets doesn't work

### ISSUE THREAD

**Issue by OutlanderZOR** [neowutran/ShinraMeter#86]
I followed all the instructions on the wiki, also running shinra as admin, but still doesn't work.

Winpcap works fine, but as stated on documentation, it does not support proxy, which is why the main reason I'm trying to use raw sockets.

I'm using version 0.82 on windows 10.

**Comment by neowutran** [comment]
you added an exception to the firewall? 
https://github.com/neowutran/ShinraMeter/wiki/Window-firewall

**Comment by OutlanderZOR** [comment]
Yes.

**Comment by Gl0** [comment]
You can't get it working with proxy, or with direct connection too?
What proxy and which type of internet connection you are using?

**Comment by OutlanderZOR** [comment]
I tried to use raw sockets without any proxy at first, just to check if it works, but it didn't.

The meter works fine using winpcap without proxy, but when I switch to raw sockets <winpcap>false</winpcap>, it doesn't detect the game connection at the character selection screen like it usually does.

I have 2 ISP, tried on both, nothing.
I'm also not using PPPoE in case you guys are wondering.

**Comment by Gl0** [comment]
When you are trying to connect via ssh-proxy like wowping.ru, it can work even if direct connection is not working, since it intercepting localhost traffic.
PPPoE direct connection is also working well in raw sockets mode (it's not working with winpcap=).
Haven't tested this things on win10, but on earlier systems (7-8.1) I cant get it not working in any probed setup (if configured correctly, of cause).

**Comment by OutlanderZOR** [comment]
I just tried now using a proxy (battleping), it also didn't work too.
I think battleping works differently, it doesn't use localhost, see here http://i.imgur.com/gLb2XFP.png

I tried again, but added the server IP on resources\data\servers.txt, "65.60.2.234 NA  BPCH".
Same thing, character selection comes up, but nothing happens.

**Comment by Gl0** [comment]
Tested with Germany 3 server, added 
`5.199.142.200 RU  battle
`
to servers.txt, successfully connected

**Comment by Gl0** [comment]
Don't forget to restart meter after changing servers.txt

**Comment by OutlanderZOR** [comment]
Finally found out what was wrong, it seems to be an issue issue on the program path on firewall rules.

If you have the meter files on a special folder like your desktop, when you add a rule to your firewall the default path goes like this: %USERPROFILE%\Desktop\Shinra\ShinraMeterV0.82\ShinraMeter.exe

I had to manually change the path after adding the new rule to: C:\Users\[MyUserName]\Desktop\Shinra\ShinraMeterV0.82\ShinraMeter.exe

It works now, sorry for the trouble.
