### ISSUE TITLE
[found in debug.txt] network error?

### ISSUE THREAD

**Issue by neowutran** [neowutran/ShinraMeter#94]
O deslocamento e o comprimento estavam fora dos limites para a matriz ou a contagem Ã© superior ao nÃºmero de elementos desde o Ã­ndice atÃ© ao fim da colecÃ§Ã£o de origem.
   em System.ArraySegment`1..ctor(T[] array, Int32 offset, Int32 count)
   em NetworkSniffer.Packets.Ip4Packet.get_Payload()
   em NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData)
   em NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data)
   em NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e)
   em SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p)
   em SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p)
   em SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data)
   em SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   em SharpPcap.LibPcap.PcapDevice.CaptureThread()
   em System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.ArgumentException: O deslocamento e o comprimento estavam fora dos limites para a matriz ou a contagem Ã© superior ao nÃºmero de elementos desde o Ã­ndice atÃ© ao fim da colecÃ§Ã£o de origem.
   em System.ArraySegment`1..ctor(T[] array, Int32 offset, Int32 count)
   em NetworkSniffer.Packets.Ip4Packet.get_Payload()
   em NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData)
   em NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data)
   em NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e)
   em SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p)
   em SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p)
   em SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data)
   em SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   em SharpPcap.LibPcap.PcapDevice.CaptureThread()
   em System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal

no idea

**Comment by Gl0** [comment]
Seen something like this long time ago on RU forum, may be packet loss handling issue.

**Comment by neowutran** [comment]
^^any idea on how to handle that?

**Comment by Gl0** [comment]
More likely it's not packet loss, but malformed/corrupted packet received, with TotalLength < HeaderLength or something like that.

**Comment by neowutran** [comment]
TCP + corrupted packet ? 
huuu so that means the packet payload + the packet checksum got corrupted, and that the corrupted payload checksum is the same as the corrupted checksum? 

The guy better not play lottery

**Comment by Gl0** [comment]
Not sure, whether checksum verification is done by winpcap, but wireshark do it on top of received from winpcap data, we - don't. 
Btw, we are listening in promiscuous mode, that is overkill for our purposes.

**Comment by neowutran** [comment]
hum, I need to read more about it. From my understanding, checking TCP checksum must be done at a very low level.
and yep, promiscuous can be disabled

**Comment by neowutran** [comment]
(do you have a link for that: "wireshark do it on top of received from winpcap data" ?  )

**Comment by Gl0** [comment]
https://github.com/boundary/wireshark/blob/master/epan/dissectors/packet-tcp.c#L4414

**Comment by neowutran** [comment]
thanks =)

**Comment by Gl0** [comment]
May be I misunderstood this code, but seems there is no need to do checksum validation if you can not receive something bad.=)

**Comment by neowutran** [comment]
I found this, it s seems linked to the code you send 
https://wiki.wireshark.org/CaptureSetup/Offloading

**Comment by Gl0** [comment]
Offloading is the easiest way to get bad checksum when sending data, but it may really be corrupted while receiving via wifi.

**Comment by neowutran** [comment]
I try to understand, not familiar with networking. 

That means winpcap doesn't do any tcp checksum and we can't rely on tcp checksum even on our side? 
So If we want to "fix" that ... we need to do a try-catch block with a empty catch to just ignore weird packets? 
But that also means we can possibly receive and accept a packet with originally 1.000.000 damage in it, *network corruption happen*, and now that 100.000.000 damage?

**Comment by Gl0** [comment]
Btw, this error is not on tcp level, it's ip...
We can force ip header checksum validation by changing [IpPacket](https://github.com/neowutran/ShinraMeter/blob/master/NetworkSniffer/IpSnifferWinPcap.cs#L103) to IPv4Packet

**Comment by Gl0** [comment]
At least we can do it and check, whether it helps.

**Comment by neowutran** [comment]
Yup, we can try & see if the bug is gone 
(btw, the online debug file is here: http://diclah.com/~yukikoo/debug/debug.txt )
(& I don't have any computer with window on it this WE, so I won't do anything before late sunday / monday )

**Comment by Gl0** [comment]
```
##### CRASH (version=0.88): #####
配列のオフセットおよび長さが範囲を超えているか、カウンターがソース コレクションのインデックスから最後までの要素の数より大きい値です。
   場所 System.ArraySegment`1..ctor(T[] array, Int32 offset, Int32 count)
   場所 NetworkSniffer.Packets.Ip4Packet.get_Payload()
   場所 NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData)
   場所 NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data)
   場所 NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e)
   場所 SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p)
   場所 SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p)
   場所 SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data)
   場所 SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   場所 SharpPcap.LibPcap.PcapDevice.CaptureThread()
   場所 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   場所 System.Threading.ThreadHelper.ThreadStart()
```
Still happening, even with checksum validation. May be problem with outgoing packets?

**Comment by neowutran** [comment]
-_-' no idea. Outgoing packet... They haven't reached the network card yet and they are already corrupted? That must be another problem

**Comment by Gl0** [comment]
May be add check for the length, and throw exception with detailed bad packet info?

**Comment by neowutran** [comment]
^^ maybe, have fun =p

**Comment by Gl0** [comment]
```
System.Exception: Wrong packet TotalLength:1420 headerLength:20 Packet.Array.Length:62 SourceIp:3415077080 DestinationIp:3232235779
   場所 NetworkSniffer.Packets.Ip4Packet.get_Payload()
   場所 NetworkSniffer.TcpSniffer.Receive(ArraySegment`1 ipData)
   場所 NetworkSniffer.IpSniffer.OnPacketReceived(ArraySegment`1 data)
   場所 NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e)
   場所 SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p)
   場所 SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p)
   場所 SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data)
   場所 SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   場所 SharpPcap.LibPcap.PcapDevice.CaptureThread()
   場所 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   場所 System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal
```
It's incoming packet from JP server, with totallength set to something like MTU, but actual received data is much smaller...

**Comment by neowutran** [comment]
yup weird. Just drop them ?

**Comment by Gl0** [comment]
Not sure, whether ip fragments reassembly is ready at the moment of the receive event. And what we receive if one of them is lost on his way.

**Comment by Gl0** [comment]
Or there is no ip fragments reassembly at all and we should do it ourself. But we can't, cause we are receiving bad length/fragmentoffset due to the bug in sharppcap.
